using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Packspire {
public class ItemAnalysis { public bool active=true; public Dictionary<Element,int> matches=new(); public List<Vector2Int> cells=new(); }
public class DeckBuildResult { public List<CardInstance> roleCards=new(),candidates=new(),deck=new(); public Dictionary<Element,int> colors=new(); public List<string> links=new(); }

public static class BackpackSystem {
 public const int Width=6,Height=4,EquipmentCardLimit=8;
 public static List<(Vector2Int pos,int original,Element element,int value)> Layout(ItemDef item,int rotation,ItemInstance instance=null){
  var raw=item.cells.Select((c,i)=>(p:new Vector2Int(c.x,c.y),original:i,element:instance!=null&&instance.colors!=null&&i<instance.colors.Count?instance.colors[i]:c.element,value:c.value)).ToList();
  for(int r=0;r<rotation%4;r++)raw=raw.Select(x=>(p:new Vector2Int(-x.p.y,x.p.x),original:x.original,element:x.element,value:x.value)).ToList();
  int minX=raw.Min(x=>x.p.x),minY=raw.Min(x=>x.p.y);
  return raw.Select(x=>(x.p-new Vector2Int(minX,minY),x.original,x.element,x.value)).ToList();
 }
 public static bool CanPlace(RunState run,ItemInstance item,int anchor,int rotation,string ignoreUid=null){var occupied=new HashSet<int>();foreach(var p in run.placements.Where(x=>x.itemUid!=ignoreUid)){var inst=run.inventory.FirstOrDefault(x=>x.uid==p.itemUid);if(inst==null)continue;foreach(var c in Layout(GameCatalog.Items[inst.templateId],p.rotation,inst))occupied.Add(p.anchor+c.pos.y*Width+c.pos.x);}int ax=anchor%Width,ay=anchor/Width;foreach(var c in Layout(GameCatalog.Items[item.templateId],rotation,item)){int x=ax+c.pos.x,y=ay+c.pos.y;if(x<0||x>=Width||y<0||y>=Height||occupied.Contains(y*Width+x))return false;}return true;}
 public static ItemAnalysis Analyze(ItemInstance instance,Placement p){var def=GameCatalog.Items[instance.templateId];var a=new ItemAnalysis();int ax=p.anchor%Width,ay=p.anchor/Width;foreach(var c in Layout(def,p.rotation,instance)){int x=ax+c.pos.x,y=ay+c.pos.y,index=y*Width+x;a.cells.Add(new Vector2Int(x,y));if(GameCatalog.Board[index]==c.element)a.matches[c.element]=a.matches.GetValueOrDefault(c.element)+c.value;}return a;}
 public static bool Adjacent(RunState run,Placement a,Placement b){var ia=run.inventory.First(x=>x.uid==a.itemUid);var ib=run.inventory.First(x=>x.uid==b.itemUid);var ca=Analyze(ia,a).cells;var cb=Analyze(ib,b).cells;return ca.Any(x=>cb.Any(y=>Mathf.Abs(x.x-y.x)+Mathf.Abs(x.y-y.y)==1));}
 public static DeckBuildResult Build(RunState run){
  var result=new DeckBuildResult{roleCards=RoleCards(run.role)};foreach(Element e in System.Enum.GetValues(typeof(Element)))result.colors[e]=0;
  var analyses=new Dictionary<string,ItemAnalysis>();foreach(var p in run.placements){var item=run.inventory.FirstOrDefault(x=>x.uid==p.itemUid);if(item==null||!GameCatalog.Items.ContainsKey(item.templateId))continue;var analysis=Analyze(item,p);analyses[item.uid]=analysis;foreach(var pair in analysis.matches)result.colors[pair.Key]+=pair.Value;}
  foreach(var p in run.placements){var item=run.inventory.FirstOrDefault(x=>x.uid==p.itemUid);if(item==null)continue;var def=GameCatalog.Items[item.templateId];var neighbors=run.placements.Where(other=>other!=p&&Adjacent(run,p,other)).Select(other=>run.inventory.First(x=>x.uid==other.itemUid).templateId).ToList();var ids=(def.cardIds?.Length>0?def.cardIds:new[]{def.cardId}).ToArray();if(def.id=="sword"&&neighbors.Contains("ember"))ids=ids.Select(x=>x=="slash"?"inferno":x).ToArray();if(def.id=="shield"&&neighbors.Contains("crystal"))ids=ids.Select(x=>x=="guard"?"echoWall":x).ToArray();if(def.id=="bomb"&&neighbors.Contains("flask"))ids=new[]{"starBomb"};for(int copy=0;copy<ids.Length;copy++){var card=FromDef(GameCatalog.Cards[ids[copy]],def.name,item.uid);card.slotKey=$"{item.uid}:{ids[copy]}:{copy}";result.candidates.Add(card);}}
  ApplyLinks(run,result.candidates,result.links);
  foreach(var card in result.candidates){if(card.damage>0)card.damage+=result.colors[Element.Fire];if(card.block>0)card.block+=result.colors[Element.Water];if(card.heal>0)card.heal+=(result.colors[Element.Water]+1)/2;if(result.colors[Element.Wind]>=3)card.cost=Mathf.Max(0,card.cost-1);if(result.colors[Element.Earth]>=2)card.block+=result.colors[Element.Earth]/2;var item=run.inventory.FirstOrDefault(x=>x.uid==card.sourceItemUid);if(item!=null){card.damage+=item.damageTemper();card.block+=item.blockTemper();card.heal+=item.healTemper();if(item.durability<=0){card.damage=(card.damage+1)/2;card.block=(card.block+1)/2;}}}
  var valid=result.candidates.Select(x=>x.slotKey).ToHashSet();run.selectedCardSlots=run.selectedCardSlots.Where(valid.Contains).Take(EquipmentCardLimit).ToList();if(run.selectedCardSlots.Count==0&&result.candidates.Count>0)run.selectedCardSlots=result.candidates.Take(EquipmentCardLimit).Select(x=>x.slotKey).ToList();var selected=run.selectedCardSlots.ToHashSet();result.deck.AddRange(result.roleCards);result.deck.AddRange(result.candidates.Where(x=>selected.Contains(x.slotKey)));return result;
 }
 public static List<CardInstance> BuildDeck(RunState run)=>Build(run).deck;
 static void ApplyLinks(RunState run,List<CardInstance> cards,List<string> log){foreach(var a in run.placements)foreach(var b in run.placements.Where(x=>string.CompareOrdinal(x.itemUid,a.itemUid)>0&&Adjacent(run,a,x))){var ia=run.inventory.First(x=>x.uid==a.itemUid);var ib=run.inventory.First(x=>x.uid==b.itemUid);var pair=new[]{ia.templateId,ib.templateId};var types=new[]{GameCatalog.Items[pair[0]].type,GameCatalog.Items[pair[1]].type};IEnumerable<CardInstance> Own(string uid)=>cards.Where(x=>x.sourceItemUid==uid);if(pair.Contains("sword")&&pair.Contains("shield")){foreach(var c in Own(pair[0]=="sword"?ia.uid:ib.uid))if(c.damage>0)c.damage++;foreach(var c in Own(pair[0]=="shield"?ia.uid:ib.uid))if(c.block>0)c.block+=2;log.Add("剣×盾");}if(pair.Contains("ember")&&types.Contains(ItemType.Weapon)){var uid=types[0]==ItemType.Weapon?ia.uid:ib.uid;foreach(var c in Own(uid))if(c.damage>0)c.damage+=2;log.Add("熾火×武器");}if(pair.Contains("crystal")){var uid=pair[0]=="crystal"?ib.uid:ia.uid;foreach(var c in Own(uid))c.cost=Mathf.Max(0,c.cost-1);log.Add("結晶×装備");}}}
 static List<CardInstance> RoleCards(string role){string archetype=new[]{"guardian","bulwark","anchor_knight","iron_vanguard","pack_saint"}.Contains(role)?"guardian":new[]{"scout","hunter","quickblade","grid_dancer","spore_druid"}.Contains(role)?"scout":new[]{"artificer","grand_artificer","rune_weaver","siege_channeler","guild_factor"}.Contains(role)?"artificer":"warrior";string[] ids=archetype=="guardian"?new[]{"basicStrike","basicGuard","basicGuard","basicGuard"}:archetype=="scout"?new[]{"basicStrike","basicStrike","basicStrike","basicTactic"}:archetype=="artificer"?new[]{"basicStrike","basicGuard","basicTactic","basicTactic"}:new[]{"basicStrike","basicStrike","basicGuard","basicGuard"};return ids.Select((id,i)=>{var c=FromDef(GameCatalog.Cards[id],GameCatalog.Roles.GetValueOrDefault(role)?.name+"の基本技","role-"+i);c.roleCard=true;return c;}).ToList();}
 public static CardInstance FromDef(CardDef d,string source,string uid){var card=new CardInstance{id=d.id,name=d.name,text=d.text,type=d.type,cost=d.cost,damage=d.damage,block=d.block,heal=d.heal,buff=d.buff,energy=d.energy,selfDamage=d.selfDamage,exhaust=d.exhaust,source=source,sourceItemUid=uid};card.effects=ContentDatabase.CardEffects(d.id);return card;}
 static int damageTemper(this ItemInstance item)=>item.temper;
 static int blockTemper(this ItemInstance item)=>item.temper;
 static int healTemper(this ItemInstance item)=>item.temper;
}
}
