using System.Collections.Generic;
using System.Linq;
using UnityEngine;
namespace Packspire {
public class ItemAnalysis { public bool active; public Dictionary<Element,int> matches=new(); public List<Vector2Int> cells=new(); }
public static class BackpackSystem {
 public const int Width=6,Height=4;
 public static List<(Vector2Int pos,int original,Element element,int value)> Layout(ItemDef item,int rotation){var raw=item.cells.Select((c,i)=>(p:new Vector2Int(c.x,c.y),i,c.element,c.value)).ToList();for(int r=0;r<rotation%4;r++)raw=raw.Select(x=>(new Vector2Int(-x.p.y,x.p.x),x.i,x.element,x.value)).ToList();int minX=raw.Min(x=>x.p.x),minY=raw.Min(x=>x.p.y);return raw.Select(x=>(x.p-new Vector2Int(minX,minY),x.i,x.element,x.value)).ToList();}
 public static bool CanPlace(RunState run,ItemInstance item,int anchor,int rotation,string ignoreUid=null){var occupied=new HashSet<int>();foreach(var p in run.placements.Where(x=>x.itemUid!=ignoreUid)){var inst=run.inventory.FirstOrDefault(x=>x.uid==p.itemUid);if(inst==null)continue;foreach(var c in Layout(GameCatalog.Items[inst.templateId],p.rotation))occupied.Add(p.anchor+c.pos.y*Width+c.pos.x);}int ax=anchor%Width,ay=anchor/Width;foreach(var c in Layout(GameCatalog.Items[item.templateId],rotation)){int x=ax+c.pos.x,y=ay+c.pos.y;if(x<0||x>=Width||y<0||y>=Height||occupied.Contains(y*Width+x))return false;}return true;}
 public static ItemAnalysis Analyze(ItemInstance instance,Placement p){var def=GameCatalog.Items[instance.templateId];var layout=Layout(def,p.rotation);var a=new ItemAnalysis();int ax=p.anchor%Width,ay=p.anchor/Width;foreach(var c in layout){int x=ax+c.pos.x,y=ay+c.pos.y,index=y*Width+x;a.cells.Add(new Vector2Int(x,y));if(GameCatalog.Board[index]==c.element)a.matches[c.element]=a.matches.GetValueOrDefault(c.element)+c.value;if(c.original==def.handle)a.active=x==0||x==Width-1||y==0||y==Height-1;}return a;}
 public static List<CardInstance> BuildDeck(RunState run){var result=RoleCards(run.role);foreach(var p in run.placements){var inst=run.inventory.FirstOrDefault(x=>x.uid==p.itemUid);if(inst==null)continue;var def=GameCatalog.Items[inst.templateId];var a=Analyze(inst,p);if(!a.active)continue;string cardId=def.cardId;if(def.id=="sword"&&a.matches.GetValueOrDefault(Element.Fire)>=2)cardId="inferno";if(def.id=="shield"&&a.matches.GetValueOrDefault(Element.Earth)>=2)cardId="echoWall";if(def.id=="bomb"&&a.matches.GetValueOrDefault(Element.Fire)>=2)cardId="starBomb";var card=FromDef(GameCatalog.Cards[cardId],def.name,inst.uid);int fire=a.matches.GetValueOrDefault(Element.Fire),water=a.matches.GetValueOrDefault(Element.Water),wind=a.matches.GetValueOrDefault(Element.Wind),earth=a.matches.GetValueOrDefault(Element.Earth);if(card.damage>0)card.damage+=fire*2;if(card.block>0)card.block+=water*2;if(card.heal>0)card.heal+=water*2;if(wind>0)card.cost=Mathf.Max(0,card.cost-1);if(wind>=2)card.draw=1;if(water>=2)card.recycle=true;if(earth>=2)card.durabilityFree=true;if(inst.temper>0){if(card.damage>0)card.damage+=inst.temper;if(card.block>0)card.block+=inst.temper;if(card.heal>0)card.heal+=inst.temper;}if(inst.durability<=0){card.damage=(card.damage+1)/2;card.block=(card.block+1)/2;}result.Add(card);}return result;}
 static List<CardInstance> RoleCards(string role){string archetype=new[]{"guardian","bulwark","anchor_knight","iron_vanguard","pack_saint"}.Contains(role)?"guardian":new[]{"scout","hunter","quickblade","grid_dancer","spore_druid"}.Contains(role)?"scout":new[]{"artificer","grand_artificer","rune_weaver","siege_channeler","guild_factor"}.Contains(role)?"artificer":"warrior";string[] ids=archetype=="guardian"?new[]{"basicStrike","basicGuard","basicGuard","basicGuard"}:archetype=="scout"?new[]{"basicStrike","basicStrike","basicStrike","basicTactic"}:archetype=="artificer"?new[]{"basicStrike","basicGuard","basicTactic","basicTactic"}:new[]{"basicStrike","basicStrike","basicGuard","basicGuard"};return ids.Select((id,i)=>FromDef(GameCatalog.Cards[id],GameCatalog.Roles.GetValueOrDefault(role)?.name+"の基本技","role-"+i)).ToList();}
 public static CardInstance FromDef(CardDef d,string source,string uid)=>new(){id=d.id,name=d.name,text=d.text,type=d.type,cost=d.cost,damage=d.damage,block=d.block,heal=d.heal,buff=d.buff,energy=d.energy,selfDamage=d.selfDamage,exhaust=d.exhaust,source=source,sourceItemUid=uid};
}
}
