const ITEMS = {
  sword:{name:'欠けた剣',icon:'⚔',type:'weapon',shape:[[0,0],[0,1]],desc:'斬撃を2枚生成',rule:'盾に隣接：斬撃+1',cards:['slash','slash']},
  shield:{name:'旅人の盾',icon:'⬟',type:'armor',shape:[[0,0],[1,0]],desc:'防御を2枚生成',rule:'武器に隣接：防御+2',cards:['guard','guard']},
  ember:{name:'熾火のルーン',icon:'✦',type:'rune',shape:[[0,0]],desc:'火花を生成',rule:'武器に隣接：その攻撃+2',cards:['spark']},
  herb:{name:'薬草袋',icon:'❧',type:'supply',shape:[[0,0]],desc:'応急手当を生成',rule:'上端に配置：回復+3',cards:['mend']},
  dagger:{name:'連撃の短剣',icon:'†',type:'weapon',shape:[[0,0]],desc:'刺突を2枚生成',rule:'他の武器に隣接：刺突+2',cards:['stab','stab']},
  plate:{name:'古い胸当て',icon:'▣',type:'armor',shape:[[0,0],[1,0],[0,1]],desc:'堅牢を生成',rule:'下端に接触：防御+5',cards:['brace']},
  crystal:{name:'共鳴結晶',icon:'◇',type:'rune',shape:[[0,0],[0,1]],desc:'整流を生成',rule:'隣接装備のカードコスト-1',cards:['focus']},
  bomb:{name:'煤けた爆弾',icon:'●',type:'supply',shape:[[0,0]],desc:'使い切りの大ダメージ',rule:'右端に配置：爆薬+5',cards:['bomb']},
  spear:{name:'折畳み槍',icon:'↟',type:'weapon',shape:[[0,0],[0,1],[0,2]],desc:'貫通突きを生成',rule:'上端から縦置き：威力+6',cards:['pierce']},
  buckler:{name:'歯車の小盾',icon:'◉',type:'armor',shape:[[0,0]],desc:'受け流しを生成',rule:'ルーンに隣接：防御+3',cards:['parry']},
  flask:{name:'錬金フラスコ',icon:'⚗',type:'supply',shape:[[0,0],[1,0]],desc:'酸液を生成',rule:'爆弾に隣接：酸液+4',cards:['acid']},
  charm:{name:'風読みの護符',icon:'☘',type:'rune',shape:[[0,0]],desc:'追い風を生成',rule:'左端に配置：追い風を強化',cards:['tailwind']},
  cursed_blade:{name:'飢えた呪剣',icon:'☠',type:'weapon',shape:[[0,0],[0,1]],desc:'強力だが周囲を蝕む',rule:'外せない・周囲のカードコスト+1',cards:['devour']}
};
const CARDS={
 slash:{name:'斬撃',type:'attack',cost:1,text:'敵に7ダメージ。',damage:7},
 guard:{name:'防御',type:'skill',cost:1,text:'6ブロックを得る。',block:6},
 spark:{name:'火花',type:'power',cost:1,text:'4ダメージ。次の攻撃+3。',damage:4,buff:3},
 mend:{name:'応急手当',type:'skill',cost:1,text:'HPを4回復する。',heal:4},
 stab:{name:'刺突',type:'attack',cost:0,text:'敵に3ダメージ。',damage:3},
 brace:{name:'堅牢',type:'skill',cost:2,text:'13ブロックを得る。',block:13},
 focus:{name:'整流',type:'power',cost:0,text:'エネルギーを1得る。',energy:1},
 bomb:{name:'爆薬',type:'attack',cost:2,text:'敵に15ダメージ。',damage:15,exhaust:true},
 pierce:{name:'貫通突き',type:'attack',cost:2,text:'敵に11ダメージ。',damage:11},
 parry:{name:'受け流し',type:'skill',cost:0,text:'3ブロックを得る。',block:3},
 acid:{name:'酸液',type:'attack',cost:1,text:'敵に6ダメージ。',damage:6},
 tailwind:{name:'追い風',type:'power',cost:1,text:'エネルギーを1得て4ブロック。',energy:1,block:4},
 devour:{name:'貪食斬り',type:'attack',cost:1,text:'敵に13ダメージ。自身に2ダメージ。',damage:13,selfDamage:2},
 inferno:{name:'焔断ち',type:'attack',cost:2,text:'敵に18ダメージ。',damage:18},
 echoWall:{name:'反響障壁',type:'skill',cost:1,text:'12ブロックを得る。',block:12},
 starBomb:{name:'星喰い爆薬',type:'attack',cost:2,text:'敵に24ダメージ。',damage:24,exhaust:true},
 geometry:{name:'陣形戦術',type:'skill',cost:1,text:'配置に応じて攻撃と防御。',damage:0,block:0}
};
const ENEMIES=[
 {floor:1,name:'鉄殻の番兵',hp:34,moves:[{label:'⚔ 8 ダメージ',damage:8},{label:'⬟ 構えて ⚔ 5',damage:5,armor:6}]},
 {floor:1,name:'洞穴ネズミの群れ',hp:29,moves:[{label:'⚔ 4 × 2',damage:8},{label:'⚔ 6 ダメージ',damage:6}]},
 {floor:1,name:'錆びた荷運び人形',hp:38,moves:[{label:'⚔ 10 ダメージ',damage:10},{label:'… 様子を見る',damage:0}]},
 {floor:2,name:'胞子の魔術師',hp:45,moves:[{label:'⚔ 7 ダメージ',damage:7},{label:'☠ 11 ダメージ',damage:11}]},
 {floor:2,name:'鎧喰い虫',hp:50,moves:[{label:'⚔ 9 ダメージ',damage:9},{label:'⚔ 5 × 2',damage:10}]},
 {floor:2,name:'虚ろな騎士',hp:54,moves:[{label:'⚔ 13 ダメージ',damage:13},{label:'⬟ 構えて ⚔ 6',damage:6,armor:8}]},
 {floor:3,boss:true,name:'荷喰らい',hp:72,moves:[{label:'⚔ 12 ダメージ',damage:12},{label:'⚔ 6 × 2',damage:12},{label:'☠ 17 ダメージ',damage:17}]}
];
const EVOLUTIONS={sword:{need:100,name:'黒鉄の百斬剣',bonus:'斬撃の基礎威力+3'},dagger:{need:75,name:'千手の短剣',bonus:'刺突の基礎威力+2'},spear:{need:60,name:'天穿つ折畳み槍',bonus:'貫通突きのコスト-1'}};
const ROLES={
 warrior:{name:'戦士',icon:'⚔',kind:'基本職',desc:'すべての武器攻撃+1。最大HP+2。',hp:2},
 guardian:{name:'守護兵',icon:'⬟',kind:'基本職',desc:'防御カード+2。最大HP+2。',hp:2},
 scout:{name:'斥候',icon:'➶',kind:'基本職',desc:'短剣と槍の攻撃+2。初期ゴールド+5。',gold:5},
 artificer:{name:'工匠',icon:'⚙',kind:'基本職',desc:'道具由来の数値効果+2。',effect:2},
 blade_master:{name:'剣聖',icon:'♰',kind:'上級職',desc:'剣と短剣の攻撃+4。最大HP+3。',hp:3,advanced:true},
 bulwark:{name:'城塞騎士',icon:'▦',kind:'上級職',desc:'防御カード+5。最大HP+4。',hp:4,advanced:true},
 hunter:{name:'魔獣狩り',icon:'⌁',kind:'上級職',desc:'短剣と槍の攻撃+4。初期ゴールド+8。',gold:8,advanced:true},
 grand_artificer:{name:'錬装術師',icon:'⚗',kind:'上級職',desc:'道具由来の数値効果+5。最大HP+2。',hp:2,advanced:true},
 arsenal_lord:{name:'万兵の王',icon:'♛',kind:'隠し職',desc:'全武器攻撃+3。初期ゴールド+5。',gold:5,hidden:true,hint:'三種の刃を一度に所有する'},
 pack_saint:{name:'不動の聖者',icon:'✜',kind:'隠し職',desc:'防御+4、回復+3。最大HP+5。',hp:5,hidden:true,hint:'三種の盾を同時に詰める'},
 rune_weaver:{name:'境界の織手',icon:'⌘',kind:'隠し職',desc:'ルーン由来カードがコスト0。最大HP+2。',hp:2,hidden:true,hint:'対角の隅を二つのルーンで結ぶ'},
 grid_dancer:{name:'盤上舞踏家',icon:'※',kind:'隠し職',desc:'0コストカードの攻撃・防御+3。',hidden:true,hint:'四つの異種装備で中央の正方形を作る'},
 iron_vanguard:{name:'鉄盟前衛',icon:'▰',kind:'勢力限定職',desc:'防具カードの防御を強化する。',hidden:true,hint:'鉄殻軍で騎士階級へ到達する'},
 spore_druid:{name:'胞子森導師',icon:'♧',kind:'勢力限定職',desc:'回復カードと薬草を強化する。',hidden:true,hint:'胞子教団で導師階級へ到達する'},
 guild_factor:{name:'荷造商務官',icon:'♜',kind:'勢力限定職',desc:'道具カードを強化する。',hidden:true,hint:'荷造り師組合で商務官へ到達する'},
 void_apostle:{name:'虚無の使徒',icon:'◉',kind:'勢力限定職',desc:'呪い武器の攻撃を強化する。',hidden:true,hint:'虚無の巡礼者で使徒階級へ到達する'},
 quickblade:{name:'瞬刃士',icon:'≋',kind:'複合職',desc:'早撃の攻撃カードを強化する。',hidden:true,hint:'戦士と斥候の基礎を修める'},
 anchor_knight:{name:'定錨騎士',icon:'⌑',kind:'複合職',desc:'安定の防御カードを強化する。',hidden:true,hint:'戦士と守護兵の基礎を修める'},
 siege_channeler:{name:'攻城導師',icon:'◈',kind:'複合職',desc:'溜めカードの高出力をさらに伸ばす。',hidden:true,hint:'工匠と戦士の技を重ねる'},
 right_hand_swordsman:{name:'片手剣鬼',icon:'◐',kind:'配置隠し職',desc:'右側の剣・短剣を大幅に強化する。',hidden:true,hint:'右側に片手武器だけを構える'}
};
const BACKPACKS={standard:{name:'探索者の鞄',desc:'癖のない標準型。中央の4マスが安全。',safe:[8,9,14,15]},merchant:{name:'行商人の鞄',desc:'商店価格20%引き。左上のL字が安全。',shop:.8,safe:[0,1,6]},arcane:{name:'魔導鞄',desc:'ルーン由来カードの数値効果+2。四隅が安全。',rune:2,safe:[0,5,18,23]},coffin:{name:'棺型ケース',desc:'下端のカードの数値効果+2。右端の縦列が安全。',bottom:2,safe:[5,11,17,23]},living:{name:'生きている鞄',desc:'戦闘後に装備がランダム回転。中央縦2マスが安全。',living:true,safe:[8,14]}};
const DUNGEONS=[{id:'old_spire',name:'古塔パックスパイア',desc:'基準となる最初のダンジョン。全5戦。',rooms:5,hp:1,damage:0,armor:0,gold:1},{id:'ash_forge',name:'灰熱の鋳造坑',desc:'敵のHPが35%増加し、攻撃も鋭い。全6戦。',rooms:6,hp:1.35,damage:2,armor:1,gold:1.25},{id:'hollow_archive',name:'虚ろなる大記憶庫',desc:'敵が大幅に強化された最深部。全8戦。',rooms:8,hp:1.7,damage:4,armor:2,gold:1.55}];
const SCAR_TYPES={fury:{name:'血気の傷',desc:'攻撃+2、防御-1',damage:2,block:-1},guard:{name:'庇護の傷',desc:'防御+2、攻撃-1',damage:-1,block:2},haste:{name:'焦燥の傷',desc:'コスト-1、数値効果-1',cost:-1,all:-1},burden:{name:'重圧の傷',desc:'コスト+1、数値効果+3',cost:1,all:3},mercy:{name:'慈悲の傷',desc:'回復+3、攻撃-1',damage:-1,heal:3},focus:{name:'研磨の傷',desc:'攻撃・防御+1、回復-1',damage:1,block:1,heal:-1}};
const CONTRACTS={fury:{name:'焦燥の契約',desc:'敵の攻撃+2 / 報酬金+50%',enemyDamage:2,gold:1.5},blind:{name:'盲目の契約',desc:'敵の一部行動予告を隠す',blind:true},fragile:{name:'脆弱の契約',desc:'最大HP-8 / 契約ポイント+1',hp:-8},no_sort:{name:'封印の契約',desc:'戦闘中整理禁止 / 報酬金+30%',noSort:true,gold:1.3}};
const SUPPLY_KITS={blade:{name:'剣士支給品',desc:'粗製剣と薬草。遠征終了時に返却される。',items:['sword','herb']},guard:{name:'守備支給品',desc:'木盾と薬草。遠征終了時に返却される。',items:['shield','herb']},craft:{name:'工匠支給品',desc:'熾火と薬草。遠征終了時に返却される。',items:['ember','herb']},none:{name:'支給不要',desc:'支給品なし。初期ゴールド+10G。',items:[],gold:10}};
const FACTIONS=[{id:'iron',name:'鉄殻軍',rankNames:['従士','兵士','騎士','鉄将'],desc:'防具カードの防御が階級に応じて増加。'},{id:'spore',name:'胞子教団',rankNames:['芽吹き','培養士','導師','森の代行者'],desc:'戦闘勝利後のHP回復量が階級に応じて増加。'},{id:'guild',name:'荷造り師組合',rankNames:['見習い','組合員','商務官','大番頭'],desc:'商店価格が階級に応じて安くなる。'},{id:'void',name:'虚無の巡礼者',rankNames:['迷い子','巡礼者','使徒','深淵卿'],desc:'獲得ゴールドが増えるが、呪い装備も出現する。'}];
const RUMORS=[['剣と火','欠けた刃を熾火へ寄せれば、存在しない一枚が生まれる。',0],['反響する壁','盾と紫の結晶は、互いの不足を埋める。',15],['星を喰う調合','爆薬の隣でフラスコを傾けよ。',30],['境界線','ルーンには向きがある。矢印の先へ魔力が流れる。',5],['不動の者','三種の防具を同時に収めた者へ、聖者は応える。',40],['四角形の舞','異なる四分類の基点で正方形を作れ。',60],['対角の織手','二つのルーンで鞄の対角を結べ。',75],['呪いの市場','虚無の巡礼者が支配する階では、重さのない剣に注意せよ。',20]];
const PROMOTIONS={warrior:'blade_master',guardian:'bulwark',scout:'hunter',artificer:'grand_artificer'};
const ITEM_ART={sword:[0,0],shield:[1,0],ember:[2,0],herb:[3,0],dagger:[0,1],plate:[1,1],crystal:[2,1],bomb:[3,1],spear:[0,2],buckler:[1,2],flask:[2,2],charm:[3,2],cursed_blade:[0,1]};
const ROLE_ART={warrior:[0,0],guardian:[1,0],scout:[2,0],artificer:[3,0],blade_master:[0,1],bulwark:[1,1],hunter:[2,1],grand_artificer:[3,1],arsenal_lord:[0,2],pack_saint:[1,2],rune_weaver:[2,2],grid_dancer:[3,2],quickblade:[2,1],anchor_knight:[1,1],siege_channeler:[3,1],right_hand_swordsman:[0,1],iron_vanguard:[1,1],spore_druid:[2,2],guild_factor:[3,1],void_apostle:[0,2]};
const ENEMY_ART={'鉄殻の番兵':['600% 200%','0% 0%'],'洞穴ネズミの群れ':['600% 200%','20% 0%'],'錆びた荷運び人形':['600% 200%','40% 0%'],'胞子の魔術師':['600% 200%','60% 0%'],'鎧喰い虫':['300% 200%','0% 100%'],'虚ろな騎士':['300% 200%','50% 100%'],'荷喰らい':['300% 100%','100% 50%']};
const CHARACTER_PRESETS=['男性・細身','男性・大柄','女性・活動的','女性・細身'];
const HAIR_PRESETS=['短髪','ミディアム','結び髪'];
const CHARACTER_IMAGE=new Image();CHARACTER_IMAGE.src='assets/character-creator-sheet.png';
const COSTUME_IMAGE=new Image();COSTUME_IMAGE.src='assets/role-costume-sheet.png';
let characterDraft={body:0,hair:0};
function costumeRow(role){let kind=roleVisualClass(role);return kind==='armor'?1:kind==='craft'?2:kind==='magic'?3:0}
const COSTUME_FIT=[{scale:.82,x:0,y:.215},{scale:.87,x:0,y:.205},{scale:.81,x:0,y:.22},{scale:.79,x:0,y:.225}];
const HEAD_MASKS=[{cx:.5,cy:.19,rx:.255,ry:.245,neck:.43},{cx:.5,cy:.19,rx:.265,ry:.25,neck:.44},{cx:.5,cy:.19,rx:.245,ry:.245,neck:.43},{cx:.5,cy:.19,rx:.24,ry:.24,neck:.425}];
const HEAD_FIT=[{scale:.84,y:.047},{scale:.88,y:.04},{scale:.83,y:.05},{scale:.81,y:.054}];
function drawBustUnderlay(canvas,body,hair){let ctx=canvas.getContext('2d'),sw=CHARACTER_IMAGE.naturalWidth/4,sh=CHARACTER_IMAGE.naturalHeight/3,fit=HEAD_FIT[body]||HEAD_FIT[0],w=canvas.width,h=canvas.height,dw=w*fit.scale,dh=h*fit.scale,dx=(w-dw)/2,dy=h*fit.y,cx=w/2;ctx.save();ctx.beginPath();ctx.moveTo(cx-dw*.11,dy+dh*.26);ctx.quadraticCurveTo(cx-dw*.18,dy+dh*.39,cx-dw*.255,dy+dh*.62);ctx.lineTo(cx+dw*.255,dy+dh*.62);ctx.quadraticCurveTo(cx+dw*.18,dy+dh*.39,cx+dw*.11,dy+dh*.26);ctx.closePath();ctx.clip();ctx.drawImage(CHARACTER_IMAGE,body*sw,hair*sh,sw,sh,dx,dy,dw,dh);ctx.restore()}
function drawHeadLayer(canvas,body,hair){let ctx=canvas.getContext('2d'),sw=CHARACTER_IMAGE.naturalWidth/4,sh=CHARACTER_IMAGE.naturalHeight/3,m=HEAD_MASKS[body]||HEAD_MASKS[0],fit=HEAD_FIT[body]||HEAD_FIT[0],w=canvas.width,h=canvas.height,dw=w*fit.scale,dh=h*fit.scale,dx=(w-dw)/2,dy=h*fit.y,cx=dx+dw*m.cx,cy=dy+dh*m.cy,rx=dw*m.rx,ry=dh*m.ry,neck=dy+dh*m.neck;ctx.save();ctx.beginPath();ctx.ellipse(cx,cy,rx,ry,0,0,Math.PI*2);ctx.moveTo(cx-rx*.34,dy+dh*.31);ctx.lineTo(cx+rx*.34,dy+dh*.31);ctx.lineTo(cx+rx*.22,neck);ctx.lineTo(cx-rx*.22,neck);ctx.closePath();ctx.clip();ctx.drawImage(CHARACTER_IMAGE,body*sw,hair*sh,sw,sh,dx,dy,dw,dh);ctx.restore()}
function drawCostume(canvas,body,hair,role){if(!role)return;let paint=()=>{let ctx=canvas.getContext('2d'),sw=COSTUME_IMAGE.naturalWidth/4,sh=COSTUME_IMAGE.naturalHeight/4,fit=COSTUME_FIT[body]||COSTUME_FIT[0],dw=canvas.width*fit.scale,dh=canvas.height*fit.scale,dx=(canvas.width-dw)/2+canvas.width*fit.x,dy=canvas.height*fit.y;ctx.drawImage(COSTUME_IMAGE,body*sw,costumeRow(role)*sh,sw,sh,dx,dy,dw,dh);drawHeadLayer(canvas,body,hair)};if(COSTUME_IMAGE.complete&&COSTUME_IMAGE.naturalWidth)paint();else COSTUME_IMAGE.addEventListener('load',paint,{once:true})}
function drawCharacter(canvas,body,hair,role=null){if(!canvas)return;let draw=()=>{let ctx=canvas.getContext('2d'),sw=CHARACTER_IMAGE.naturalWidth/4,sh=CHARACTER_IMAGE.naturalHeight/3;canvas.width=Math.round(sw);canvas.height=Math.round(sh);ctx.clearRect(0,0,canvas.width,canvas.height);if(role){drawBustUnderlay(canvas,body,hair);drawCostume(canvas,body,hair,role)}else ctx.drawImage(CHARACTER_IMAGE,body*sw,hair*sh,sw,sh,0,0,canvas.width,canvas.height)};if(CHARACTER_IMAGE.complete&&CHARACTER_IMAGE.naturalWidth)draw();else CHARACTER_IMAGE.addEventListener('load',draw,{once:true})}
function sheetPos([x,y],cols=4,rows=3){return `${x/(cols-1)*100}% ${y/(rows-1)*100}%`}
function itemArtStyle(id){return `background-position:${sheetPos(ITEM_ART[id])}`}
function roleArtStyle(id){let p=ROLE_ART[id]||[0,0];return `--role-x:${p[0]/3*100}%;--role-y:${p[1]/2*100}%`}
let ITEM_SERIAL=0;
function makeItem(templateId,data={}){return{uid:data.uid||`item-${Date.now().toString(36)}-${(++ITEM_SERIAL).toString(36)}`,templateId,durability:data.durability??6,uses:data.uses??0,heirloom:!!data.heirloom,heirloomCertified:!!data.heirloomCertified,origin:data.origin||'loot',evolution:data.evolution||null,scars:Array.isArray(data.scars)?data.scars:[],insured:!!data.insured}}
function normalizeItem(value){return typeof value==='string'?makeItem(value):makeItem(value.templateId,value)}
function itemAt(index){return state.inventory[index]}
function templateAt(index){return itemAt(index)?.templateId}
function defAt(index){return ITEMS[templateAt(index)]}
function hasTemplate(id){return state.inventory.some(item=>item.templateId===id)}
function repairAllItems(){state.inventory.forEach(item=>item.durability=6)}
const SECRETS=[
 {id:'first_card',name:'最初の一手',hint:'カードを初めて使用する',reward:'秘密の記録を解禁'},
 {id:'blade_100',name:'百斬の記憶',hint:'欠けた剣を100回使用する',reward:'欠けた剣が恒久進化'},
 {id:'dagger_75',name:'千の手数',hint:'連撃の短剣を75回使用する',reward:'短剣が恒久進化'},
 {id:'spear_60',name:'天を穿つ',hint:'折畳み槍を60回使用する',reward:'槍が恒久進化'},
 {id:'first_win',name:'荷喰らいの沈黙',hint:'ランを初めて踏破する',reward:'初期最大HP+3'},
 {id:'three_wins',name:'熟練の荷造り師',hint:'3回踏破する',reward:'初期ゴールド+10'},
 {id:'rotator',name:'四次元の詰め方',hint:'アイテムを50回回転する',reward:'初期ゴールド+2'},
 {id:'merchant',name:'上得意',hint:'商品を5個購入する',reward:'初期ゴールド+5'},
 {id:'eventer',name:'好奇心は身を救う',hint:'イベントを10回経験する',reward:'初期最大HP+2'},
 {id:'organizer',name:'戦場の荷造り師',hint:'戦闘中整理を20回行う',reward:'初期最大HP+2'},
 {id:'perfect_weight',name:'一分の隙間もなく',hint:'24マスを完全に埋めて出発する',reward:'初期ゴールド+3'},
 {id:'collector',name:'持てるだけの記憶',hint:'一度に装備を10種類所有する',reward:'初期最大HP+1'},
 {id:'minimalist',name:'軽装踏破',hint:'装備2個以下でボスを倒す',reward:'初期ゴールド+7'},
 {id:'last_stand',name:'紙一重',hint:'HP1でボスを倒す',reward:'初期最大HP+3'},
 {id:'edge_master',name:'四辺の儀式',hint:'バックパックの四辺すべてに装備を触れさせる',reward:'初期最大HP+2'},
 {id:'first_forge',name:'火花を継ぐ者',hint:'保管装備を初めて鍛錬する',reward:'秘密の鍛冶記録'},
 {id:'scarred_relic',name:'三度死なず',hint:'一つの装備に傷跡を3個刻む',reward:'初期最大HP+2'},
 {id:'job_25',name:'重ねた肩書',hint:'累計役職レベル25へ到達する',reward:'初期ゴールド+5'},
 {id:'deepest_clear',name:'記憶庫の最奥',hint:'虚ろなる大記憶庫を踏破する',reward:'初期最大HP+4'},
 {id:'vault_master',name:'蒐集家の城',hint:'保管庫を最大まで拡張する',reward:'初期ゴールド+5'},
 {id:'whisper',name:'塔はこちらを見ている',hint:'タイトルに秘密がある',reward:'初期ゴールド+1'}
];
function loadMeta(){try{return JSON.parse(localStorage.getItem('packspire_meta_v1'))||{}}catch{return{}}}
function migrateMeta(meta){meta=meta&&typeof meta==='object'?meta:{};meta.stash=(Array.isArray(meta.stash)?meta.stash:[]).filter(x=>typeof x==='string'||x?.templateId).map(normalizeItem);meta.baseGold=Math.max(0,meta.baseGold||0);meta.dungeonsUnlocked=Math.max(1,Math.min(DUNGEONS.length,meta.dungeonsUnlocked||1));meta.dungeonClears=meta.dungeonClears&&typeof meta.dungeonClears==='object'?meta.dungeonClears:{};meta.jobLevels=meta.jobLevels&&typeof meta.jobLevels==='object'?meta.jobLevels:{};meta.currentRole=ROLES[meta.currentRole]?meta.currentRole:null;meta.factions=Object.assign({iron:true,spore:true,guild:true,void:false},meta.factions||{});meta.factionContribution=Object.assign({iron:0,spore:0,guild:0,void:0},meta.factionContribution||{});meta.currentFaction=meta.factions[meta.currentFaction]?meta.currentFaction:'iron';meta.selectedBackpack=BACKPACKS[meta.selectedBackpack]?meta.selectedBackpack:'standard';meta.selectedHeirloomUid=meta.stash.some(item=>item.uid===meta.selectedHeirloomUid)?meta.selectedHeirloomUid:null;meta.discoveredItems=meta.discoveredItems&&typeof meta.discoveredItems==='object'?meta.discoveredItems:{};['sword','shield','ember','herb',...meta.stash.map(item=>item.templateId)].forEach(id=>meta.discoveredItems[id]=true);meta.discoveredEnemies=meta.discoveredEnemies&&typeof meta.discoveredEnemies==='object'?meta.discoveredEnemies:{};meta.character=meta.character&&Number.isInteger(meta.character.body)&&Number.isInteger(meta.character.hair)?{body:Math.max(0,Math.min(3,meta.character.body)),hair:Math.max(0,Math.min(2,meta.character.hair))}:null;meta.vaultLevel=Math.max(0,Math.min(3,meta.vaultLevel??Math.ceil(Math.max(0,meta.stash.length-4)/4)));meta.version=10;return meta}
function vaultCapacity(){return 4+(META.vaultLevel||0)*4}
let META=migrateMeta(loadMeta());META.mastery=META.mastery||{};META.unlocked=META.unlocked||{};META.roles=Object.assign({warrior:true,guardian:true,scout:true,artificer:true},META.roles||{});META.stats=Object.assign({runs:0,wins:0,cards:0,rotations:0,shopBuys:0,events:0,organizes:0},META.stats||{});META.selectedSupplyKit=SUPPLY_KITS[META.selectedSupplyKit]?META.selectedSupplyKit:'blade';META.selectedCarryUids=(Array.isArray(META.selectedCarryUids)?META.selectedCarryUids:[]).filter(uid=>META.stash.some(item=>item.uid===uid)).slice(0,3);if(!META.stash.some(item=>item.uid===META.selectedHeirloomUid&&item.heirloomCertified))META.selectedHeirloomUid=null;META.version=11;
function saveMeta(){try{localStorage.setItem('packspire_meta_v1',JSON.stringify(META))}catch{}}
function unlock(id){if(META.unlocked[id])return;META.unlocked[id]=Date.now();saveMeta();let s=SECRETS.find(x=>x.id===id);if(s)toast(`秘密発見「${s.name}」— ${s.reward}`)}
function isEvolved(id){return !!EVOLUTIONS[id]&&(META.mastery[id]||0)>=EVOLUTIONS[id].need}
function metaMaxHp(){return 42+(META.unlocked.first_win?3:0)+(META.unlocked.eventer?2:0)+(META.unlocked.organizer?2:0)+(META.unlocked.collector?1:0)+(META.unlocked.last_stand?3:0)+(META.unlocked.edge_master?2:0)+(META.unlocked.scarred_relic?2:0)+(META.unlocked.deepest_clear?4:0)}
function metaGold(){return 24+(META.unlocked.three_wins?10:0)+(META.unlocked.merchant?5:0)+(META.unlocked.perfect_weight?3:0)+(META.unlocked.minimalist?7:0)+(META.unlocked.whisper?1:0)+(META.unlocked.rotator?2:0)+(META.unlocked.job_25?5:0)+(META.unlocked.vault_master?5:0)}
function checkMeta(){if(META.stats.cards>=1)unlock('first_card');if((META.mastery.sword||0)>=100)unlock('blade_100');if((META.mastery.dagger||0)>=75)unlock('dagger_75');if((META.mastery.spear||0)>=60)unlock('spear_60');if(META.stats.wins>=1)unlock('first_win');if(META.stats.wins>=3)unlock('three_wins');if(META.stats.rotations>=50)unlock('rotator');if(META.stats.shopBuys>=5)unlock('merchant');if(META.stats.events>=10)unlock('eventer');if(META.stats.organizes>=20)unlock('organizer');if(totalJobLevels()>=25)unlock('job_25');if((META.dungeonClears.hollow_archive||0)>=1){unlock('deepest_clear');unlockFaction('void','虚ろなる大記憶庫を踏破した')}if(META.vaultLevel>=3)unlock('vault_master');if(META.stash.some(item=>item.scars.length>=3))unlock('scarred_relic');saveMeta()}
function unlockRole(id,reason){if(META.roles[id])return;META.roles[id]=true;saveMeta();toast(`隠し役職「${ROLES[id].name}」解禁 — ${reason}`)}
function unlockFaction(id,reason){if(META.factions[id])return;META.factions[id]=true;saveMeta();toast(`新勢力「${factionById(id).name}」解禁 — ${reason}`)}
function jobMax(id){return ROLES[id]?.hidden?15:10}
function jobLevel(id){return Math.max(0,Math.min(jobMax(id),META.jobLevels[id]||0))}
function totalJobLevels(){return Object.keys(ROLES).reduce((n,id)=>n+jobLevel(id),0)}
function factionById(id){return FACTIONS.find(f=>f.id===id)||FACTIONS[0]}
function factionContribution(id){return META.factionContribution[id]||0}
function factionRank(id){let n=factionContribution(id);return n>=50?4:n>=25?3:n>=10?2:1}
function factionRankName(id){let faction=factionById(id);return faction.rankNames[factionRank(id)-1]}
function gainFactionContribution(id,amount=1){META.factionContribution[id]=(META.factionContribution[id]||0)+amount;let rank=factionRank(id);if(rank>=3){let roles={iron:'iron_vanguard',spore:'spore_druid',guild:'guild_factor',void:'void_apostle'};unlockRole(roles[id],`${factionById(id).name}で${factionRankName(id)}へ昇格した`)}saveMeta();return rank}
function gainJobLevel(id,amount=1){if(!id)return 0;let before=jobLevel(id),room=Math.max(0,100-totalJobLevels()),gain=Math.min(amount,jobMax(id)-before,room);if(gain>0){META.jobLevels[id]=before+gain;saveMeta();checkJobCombinations()}return gain}
function checkJobCombinations(){if(jobLevel('warrior')>=5&&jobLevel('scout')>=5)unlockRole('arsenal_lord','戦士Lv.5と斥候Lv.5を修めた');if(jobLevel('guardian')>=5&&jobLevel('artificer')>=5)unlockRole('pack_saint','守護兵Lv.5と工匠Lv.5を修めた');if(jobLevel('artificer')>=7&&jobLevel('scout')>=3)unlockRole('rune_weaver','工匠Lv.7と斥候Lv.3を修めた');if(['warrior','guardian','scout','artificer'].every(id=>jobLevel(id)>=3))unlockRole('grid_dancer','四基本職をすべてLv.3まで修めた');if(jobLevel('warrior')>=3&&jobLevel('scout')>=3)unlockRole('quickblade','戦士Lv.3と斥候Lv.3を修めた');if(jobLevel('warrior')>=3&&jobLevel('guardian')>=3)unlockRole('anchor_knight','戦士Lv.3と守護兵Lv.3を修めた');if(jobLevel('artificer')>=5&&jobLevel('warrior')>=3)unlockRole('siege_channeler','工匠Lv.5と戦士Lv.3を修めた')}
let state;
const $=s=>document.querySelector(s);
function makeRunState(){let maxHp=metaMaxHp();return{floor:1,hp:maxHp,maxHp,gold:metaGold(),role:null,dungeon:DUNGEONS[0].id,backpack:META.selectedBackpack||'standard',contracts:[],carryUids:[],supplyKit:'blade',heirloomUid:META.selectedHeirloomUid||null,faction:factionById(META.currentFaction),inventory:[],placed:{},jammed:[],selected:null,selectedPlaced:null,rotations:{},drag:null,organizing:false,organizeUsed:false,organizesRun:0,enemy:null,draw:[],discard:[],hand:[],energy:3,block:0,attackBuff:0,move:0,metaReturn:'hubScreen'}}
function currentDungeon(){return DUNGEONS.find(d=>d.id===state.dungeon)||DUNGEONS[0]}
function encounterTier(){let dungeon=currentDungeon();if(state.floor>=dungeon.rooms)return 3;return state.floor<=Math.floor((dungeon.rooms-1)/2)?1:2}
function stashInfo(item){let level=item.evolution?.level||0,scars=item.scars.map(s=>SCAR_TYPES[s.type]?.name).filter(Boolean).join('、')||'なし';return{level,scars,name:ITEMS[item.templateId]?.name||item.templateId,icon:ITEMS[item.templateId]?.icon||'?'}}
function renderCharacterCreator(){drawCharacter($('#creatorCanvas'),characterDraft.body,characterDraft.hair);$('#bodyChoices').innerHTML=CHARACTER_PRESETS.map((name,i)=>`<button class="appearance-choice ${characterDraft.body===i?'selected':''}" data-body="${i}">${name}</button>`).join('');$('#hairChoices').innerHTML=HAIR_PRESETS.map((name,i)=>`<button class="appearance-choice ${characterDraft.hair===i?'selected':''}" data-hair="${i}">${name}</button>`).join('');document.querySelectorAll('[data-body]').forEach(button=>button.onclick=()=>{characterDraft.body=+button.dataset.body;renderCharacterCreator()});document.querySelectorAll('[data-hair]').forEach(button=>button.onclick=()=>{characterDraft.hair=+button.dataset.hair;renderCharacterCreator()});show('characterScreen')}
function roleVisualClass(id){if(['guardian','bulwark','anchor_knight','iron_vanguard'].includes(id))return'armor';if(['artificer','grand_artificer','guild_factor'].includes(id))return'craft';if(['rune_weaver','spore_druid','void_apostle'].includes(id))return'magic';return'blade'}
function renderHubCharacter(){let character=META.character||{body:0,hair:0},faction=META.currentFaction||'iron',role=META.currentRole,atmospheres={iron:'炉火と軍旗に包まれた鉄殻軍の拠点',spore:'発光菌と古樹が息づく胞子教団の庭',guild:'商人と職人の灯りが集う荷造り師組合',void:'星屑と静寂が漂う虚無の巡礼地'};drawCharacter($('#hubCharacter'),character.body,character.hair,role);$('#hubScreen').className=`screen hub-screen faction-${faction}`;$('#hubHero').className=`hub-hero faction-${faction}`;$('#hubAtmosphere').textContent=atmospheres[faction];$('#hubRoleAura').className=`hub-role-aura ${roleVisualClass(role)}`;$('#hubRolePlate').innerHTML=role?`<b>${ROLES[role].icon} ${ROLES[role].name}</b><small>Lv.${jobLevel(role)}　${factionRankName(faction)}</small>`:'<b>未就職</b>';let heirloom=(META.stash||[]).find(item=>item.uid===META.selectedHeirloomUid);$('#hubGear').innerHTML=heirloom?`<span class="selected-heirloom" title="家宝：${ITEMS[heirloom.templateId]?.name}">${ITEMS[heirloom.templateId]?.icon||'?'}</span>`:''}
function enterHub(){state=state||makeRunState();if(!META.character){characterDraft={body:0,hair:0};renderCharacterCreator();return}state.metaReturn='hubScreen';$('#roleName').textContent=META.currentRole?ROLES[META.currentRole].name:'未就職';$('#floor').textContent='-';$('#maxFloor').textContent='-';$('#playerHp').textContent='-';$('#gold').textContent=META.baseGold;$('#hubGold').textContent=META.baseGold;$('#facilityModal').classList.add('hidden');show('hubScreen');renderHubCharacter()}
const FACTION_CHANGE_COST=30;
function renderBaseLoadout(){$('#hubBackpackChoices').innerHTML=Object.entries(BACKPACKS).map(([id,p])=>`<button class="pack-choice ${META.selectedBackpack===id?'selected':''}" data-id="${id}"><b>${p.name}</b><small>${p.desc}</small></button>`).join('');document.querySelectorAll('#hubBackpackChoices .pack-choice').forEach(button=>button.onclick=()=>{META.selectedBackpack=button.dataset.id;saveMeta();renderBaseLoadout();toast(`${BACKPACKS[button.dataset.id].name}を遠征用に設定した`)});$('#hubHeirloomChoices').innerHTML=`<button class="heirloom-choice ${META.selectedHeirloomUid===null?'selected':''}" data-uid=""><b>家宝なし</b><small>保管装備を持ち込まない</small></button>`+(META.stash||[]).map(item=>`<button class="heirloom-choice ${META.selectedHeirloomUid===item.uid?'selected':''}" data-uid="${item.uid}"><b>${ITEMS[item.templateId]?.icon||'?'} ${ITEMS[item.templateId]?.name||item.templateId}</b><small>使用 ${item.uses} / 耐久 ${item.durability}</small></button>`).join('');document.querySelectorAll('#hubHeirloomChoices .heirloom-choice').forEach(button=>button.onclick=()=>{META.selectedHeirloomUid=button.dataset.uid||null;saveMeta();renderBaseLoadout();toast(META.selectedHeirloomUid?'家宝を設定した':'家宝を外した')});$('#factionChangeNote').textContent=`所属変更には${FACTION_CHANGE_COST}G必要です。現在：${factionById(META.currentFaction).name}／${factionRankName(META.currentFaction)}`;$('#hubFactionChoices').innerHTML=FACTIONS.map(f=>{let open=META.factions[f.id],active=META.currentFaction===f.id,rank=factionRank(f.id),value=factionContribution(f.id),next=[10,25,50,null][rank-1];return `<button class="faction-choice ${active?'selected':''} ${open?'':'locked'}" data-id="${f.id}" ${open?'':'disabled'}><span>${open?f.name:'未発見の勢力'}</span><b>${open?`${f.rankNames[rank-1]}${active?'・所属中':''}`:'LOCKED'}</b><small>${open?f.desc:'イベントや条件達成で発見できる'}</small><em>${open?(next?`貢献度 ${value}/${next}`:`貢献度 ${value}・最高階級`):'？？？'}</em></button>`}).join('');document.querySelectorAll('#hubFactionChoices .faction-choice:not(.locked)').forEach(button=>button.onclick=()=>changeBaseFaction(button.dataset.id));$('#gold').textContent=META.baseGold}
const renderBaseLoadoutCore=renderBaseLoadout;
renderBaseLoadout=function(){renderBaseLoadoutCore();let certified=(META.stash||[]).filter(item=>item.heirloomCertified);$('#hubHeirloomChoices').innerHTML=`<button class="heirloom-choice ${META.selectedHeirloomUid===null?'selected':''}" data-uid=""><b>家宝なし</b><small>家宝枠を空けて出発する</small></button>`+certified.map(item=>`<button class="heirloom-choice ${META.selectedHeirloomUid===item.uid?'selected':''}" data-uid="${item.uid}"><b>★ ${ITEMS[item.templateId].name}</b><small>使用 ${item.uses}／鍛錬 +${item.evolution?.level||0}／必ず帰還</small></button>`).join('');document.querySelectorAll('#hubHeirloomChoices .heirloom-choice').forEach(button=>button.onclick=()=>{META.selectedHeirloomUid=button.dataset.uid||null;META.selectedCarryUids=META.selectedCarryUids.filter(uid=>uid!==META.selectedHeirloomUid);saveMeta();renderBaseLoadout();toast(META.selectedHeirloomUid?'家宝を設定した':'家宝を外した')});let carryable=(META.stash||[]).filter(item=>item.uid!==META.selectedHeirloomUid);$('#carryCount').textContent=`${META.selectedCarryUids.length} / 3`;$('#hubCarryChoices').innerHTML=carryable.map(item=>`<button class="heirloom-choice ${META.selectedCarryUids.includes(item.uid)?'selected':''}" data-carry="${item.uid}"><b>${ITEMS[item.templateId].icon} ${ITEMS[item.templateId].name}</b><small>死亡時、安全マス外なら喪失／使用 ${item.uses}</small></button>`).join('')||'<p class="empty-state">持ち込める保管装備がありません。</p>';document.querySelectorAll('[data-carry]').forEach(button=>button.onclick=()=>{let uid=button.dataset.carry;if(META.selectedCarryUids.includes(uid))META.selectedCarryUids=META.selectedCarryUids.filter(x=>x!==uid);else if(META.selectedCarryUids.length<3)META.selectedCarryUids.push(uid);else{toast('持込保管装備は3個まで');return}saveMeta();renderBaseLoadout()});$('#hubSupplyChoices').innerHTML=Object.entries(SUPPLY_KITS).map(([id,kit])=>`<button class="pack-choice ${META.selectedSupplyKit===id?'selected':''}" data-supply="${id}"><b>${kit.name}</b><small>${kit.desc}</small></button>`).join('');document.querySelectorAll('[data-supply]').forEach(button=>button.onclick=()=>{META.selectedSupplyKit=button.dataset.supply;saveMeta();renderBaseLoadout()})}
function changeBaseFaction(id){if(id===META.currentFaction){toast('すでに所属している勢力です');return}if(META.baseGold<FACTION_CHANGE_COST){toast(`所属変更には${FACTION_CHANGE_COST}G必要です`);return}META.baseGold-=FACTION_CHANGE_COST;META.currentFaction=id;saveMeta();$('#hubGold').textContent=META.baseGold;toast(`${factionById(id).name}へ所属を変更した（-${FACTION_CHANGE_COST}G）`)}
function roleMilestones(id){let r=ROLES[id],max=jobMax(id),levels=[1,4,7,10,...(max>10?[13]:[])];return levels.filter(level=>level<=max).map(level=>({level,text:level===1?r.desc:id==='rune_weaver'?'コスト0効果は完成済み。累計役職レベルとして蓄積':id==='siege_channeler'?`攻撃・防御の溜め効果が基礎値から+${Math.floor((level-1)/3)*2}、回復は+${Math.floor((level-1)/3)}`:`対象カードの主要数値が基礎値から+${Math.floor((level-1)/3)}`}))}
function renderStatus(){let learned=Object.keys(ROLES).filter(id=>jobLevel(id)>0),current=META.currentRole,heirloom=(META.stash||[]).find(item=>item.uid===META.selectedHeirloomUid);$('#statusJobSummary').textContent=`累計役職レベル ${totalJobLevels()} / 100　習得 ${learned.length}職`;$('#currentBuildSummary').innerHTML=`<div><small>現在の役職</small><b>${current?`${ROLES[current].icon} ${ROLES[current].name} Lv.${jobLevel(current)}`:'未就職'}</b></div><div><small>所属勢力</small><b>${factionById(META.currentFaction).name}・${factionRankName(META.currentFaction)}</b></div><div><small>バックパック</small><b>${BACKPACKS[META.selectedBackpack].name}</b></div><div><small>家宝</small><b>${heirloom?`${ITEMS[heirloom.templateId].icon} ${ITEMS[heirloom.templateId].name}`:'なし'}</b></div>`;$('#jobProgressList').innerHTML=learned.map(id=>{let r=ROLES[id],level=jobLevel(id);return `<article class="job-progress ${id===current?'current':''}"><div class="job-progress-head"><span class="role-icon">${r.icon}</span><div><small>${r.kind}</small><h3>${r.name}</h3></div><b>Lv.${level} / ${jobMax(id)}</b></div><p>${r.desc}</p><div class="job-level-bar"><i style="width:${level/jobMax(id)*100}%"></i></div><div class="job-milestones">${roleMilestones(id).map(m=>`<div class="job-milestone ${level>=m.level?'reached':'future'}"><b>Lv.${m.level}</b><span>${m.text}</span></div>`).join('')}</div></article>`}).join('')||'<p class="empty-state">習得済みの役職はまだありません。</p>';show('statusScreen')}
let compendiumTab='roles';
function discoverItem(id){if(!META.discoveredItems[id]){META.discoveredItems[id]=true;saveMeta()}}
function discoverEnemy(name){if(!META.discoveredEnemies[name]){META.discoveredEnemies[name]=true;saveMeta()}}
function renderCompendium(tab=compendiumTab){compendiumTab=tab;document.querySelectorAll('#compendiumTabs button').forEach(button=>button.classList.toggle('selected',button.dataset.tab===tab));let entries=[],found=0,total=0;if(tab==='roles'){total=Object.keys(ROLES).length;entries=Object.entries(ROLES).map(([id,r])=>{let open=!!META.roles[id];if(open)found++;return `<article class="compendium-entry ${open?'':'unknown'}"><span class="compendium-icon">${open?r.icon:'？'}</span><div><small>${open?r.kind:'未発見'}</small><h3>${open?r.name:'？？？？？？'}</h3><p>${open?`${r.desc}<br>最大Lv.${jobMax(id)}${r.hint?`／手掛かり：${r.hint}`:''}`:'条件を満たすと情報が記録される'}</p></div></article>`})}else if(tab==='items'){total=Object.keys(ITEMS).length;entries=Object.entries(ITEMS).map(([id,item])=>{let open=!!META.discoveredItems[id];if(open)found++;return `<article class="compendium-entry ${open?'':'unknown'}"><span class="compendium-icon ${open?'art-icon':''}" ${open?`style="${itemArtStyle(id)}"`:''}>${open?item.icon:'？'}</span><div><small>${open?`${item.type}・${item.shape.length}マス`:'未発見'}</small><h3>${open?item.name:'？？？？？？'}</h3><p>${open?`${item.desc}<br>${item.rule}`:'入手すると形状と能力が記録される'}</p></div></article>`})}else{let unique=[...new Map(ENEMIES.map(enemy=>[enemy.name,enemy])).values()];total=unique.length;entries=unique.map(enemy=>{let open=!!META.discoveredEnemies[enemy.name],art=ENEMY_ART[enemy.name];if(open)found++;return `<article class="compendium-entry enemy-entry ${open?'':'unknown'}"><span class="compendium-icon enemy-book-art" ${open&&art?`style="background-size:${art[0]};background-position:${art[1]}"`:''}>${open?'':'？'}</span><div><small>${open?enemy.boss?'BOSS':`危険度 ${enemy.floor}`:'未遭遇'}</small><h3>${open?enemy.name:'？？？？？？'}</h3><p>${open?`基礎HP ${enemy.hp}<br>${enemy.moves.map(move=>move.label).join('／')}`:'戦闘で遭遇すると情報が記録される'}</p></div></article>`})}$('#compendiumSummary').textContent=`発見 ${found} / ${total}`;$('#compendiumEntries').innerHTML=entries.join('');show('compendiumScreen')}
function renderForge(){let stash=META.stash||[];$('#forgeItems').innerHTML=stash.map(item=>{let info=stashInfo(item),repair=(6-item.durability)*3,temper=30*(info.level+1);return `<article class="facility-item stash-entry" data-uid="${item.uid}"><span class="stash-icon">${info.icon}</span><div><b>${info.name} +${info.level}</b><small>耐久 ${item.durability}/6　使用 ${item.uses}</small><small>傷：${info.scars}</small></div><div class="item-actions"><button class="stash-repair" ${repair<=0?'disabled':''}>修理 <em>${repair}G</em></button><button class="stash-temper" ${info.level>=5?'disabled':''}>鍛錬 <em>${info.level>=5?'MAX':temper+'G'}</em></button></div></article>`}).join('');document.querySelectorAll('#forgeItems .stash-repair').forEach(button=>button.onclick=()=>forgeRepair(button.closest('.stash-entry').dataset.uid));document.querySelectorAll('#forgeItems .stash-temper').forEach(button=>button.onclick=()=>forgeTemper(button.closest('.stash-entry').dataset.uid));$('#emptyForge').classList.toggle('hidden',stash.length>0);$('#gold').textContent=META.baseGold;show('forgeScreen')}
function renderVault(){let stash=META.stash||[];$('#hubStash').innerHTML=stash.map(item=>{let info=stashInfo(item);return `<article class="facility-item"><span class="stash-icon">${info.icon}</span><div><b>${info.name} +${info.level}</b><small>耐久 ${item.durability}/6　使用 ${item.uses}</small><small>傷：${info.scars}</small></div></article>`}).join('');$('#emptyStash').classList.toggle('hidden',stash.length>0);let cost=50*(META.vaultLevel+1);$('#vaultStatus').textContent=`${stash.length} / ${vaultCapacity()}枠`;$('#vaultUpgradeText').textContent=META.vaultLevel>=3?'最大まで拡張済み':`次の拡張：${vaultCapacity()+4}枠 / ${cost}G`;$('#upgradeVault').disabled=META.vaultLevel>=3;$('#gold').textContent=META.baseGold;show('vaultScreen')}
const renderVaultCore=renderVault;
renderVault=function(){renderVaultCore();document.querySelectorAll('#hubStash .facility-item').forEach((entry,index)=>{let item=META.stash[index],level=item.evolution?.level||0,eligible=item.uses>=100||level>=3,button=document.createElement('button');button.className='facility-button heirloom-certify';button.dataset.uid=item.uid;button.disabled=item.heirloomCertified||!eligible||META.baseGold<50;button.textContent=item.heirloomCertified?'★ 家宝認定済み':eligible?'50Gで家宝認定':`家宝条件：使用${item.uses}/100 または鍛錬+${level}/3`;entry.appendChild(button)});document.querySelectorAll('.heirloom-certify:not(:disabled)').forEach(button=>button.onclick=()=>certifyHeirloom(button.dataset.uid))}
function certifyHeirloom(uid){let item=META.stash.find(x=>x.uid===uid),level=item?.evolution?.level||0;if(!item||item.heirloomCertified||item.uses<100&&level<3||META.baseGold<50)return;META.baseGold-=50;item.heirloomCertified=true;saveMeta();renderVault();toast(`${ITEMS[item.templateId].name}を家宝として認定した`)}
function renderVaultHub(){let stash=META.stash||[],cost=50*(META.vaultLevel+1);$('#hubVaultStatus').textContent=`${stash.length} / ${vaultCapacity()}枠　保管金 ${META.baseGold}G`;$('#upgradeHubVault').disabled=META.vaultLevel>=3||META.baseGold<cost;$('#upgradeHubVault').textContent=META.vaultLevel>=3?'最大拡張済み':`${cost}Gで${vaultCapacity()+4}枠へ拡張`;$('#hubVaultItems').innerHTML=stash.map(item=>{let info=stashInfo(item),level=item.evolution?.level||0,eligible=item.uses>=100||level>=3;return `<article class="facility-item stash-entry"><span class="stash-icon">${info.icon}</span><div><b>${item.heirloomCertified?'★ ':''}${info.name} +${info.level}</b><small>耐久 ${item.durability}/6　使用 ${item.uses}　傷：${info.scars}</small></div><button class="facility-button vault-certify" data-uid="${item.uid}" ${item.heirloomCertified||!eligible||META.baseGold<50?'disabled':''}>${item.heirloomCertified?'家宝認定済み':eligible?'50Gで家宝認定':`使用${item.uses}/100・鍛錬+${level}/3`}</button></article>`}).join('');$('#emptyHubVault').classList.toggle('hidden',stash.length>0);document.querySelectorAll('.vault-certify:not(:disabled)').forEach(button=>button.onclick=()=>{let item=META.stash.find(x=>x.uid===button.dataset.uid);if(!item||META.baseGold<50)return;META.baseGold-=50;item.heirloomCertified=true;saveMeta();renderVaultHub();toast(`${ITEMS[item.templateId].name}を家宝認定した`)});$('#hubBackpackChoices').innerHTML=Object.entries(BACKPACKS).map(([id,p])=>`<button class="pack-choice ${META.selectedBackpack===id?'selected':''}" data-pack="${id}"><b>${p.name}</b><small>${p.desc}</small></button>`).join('');document.querySelectorAll('[data-pack]').forEach(button=>button.onclick=()=>{META.selectedBackpack=button.dataset.pack;saveMeta();renderVaultHub()});let certified=stash.filter(item=>item.heirloomCertified);$('#hubHeirloomChoices').innerHTML=`<button class="heirloom-choice ${META.selectedHeirloomUid===null?'selected':''}" data-heirloom=""><b>家宝なし</b><small>家宝枠を空ける</small></button>`+certified.map(item=>`<button class="heirloom-choice ${META.selectedHeirloomUid===item.uid?'selected':''}" data-heirloom="${item.uid}"><b>★ ${ITEMS[item.templateId].name}</b><small>使用 ${item.uses}／鍛錬+${item.evolution?.level||0}</small></button>`).join('');document.querySelectorAll('[data-heirloom]').forEach(button=>button.onclick=()=>{META.selectedHeirloomUid=button.dataset.heirloom||null;saveMeta();renderVaultHub();toast(META.selectedHeirloomUid?'家宝を設定した':'家宝を外した')});$('#gold').textContent=META.baseGold;show('loadoutScreen')}
function renderFactionFacility(){$('#factionChangeNote').textContent=`所属変更には${FACTION_CHANGE_COST}G必要です。現在：${factionById(META.currentFaction).name}／${factionRankName(META.currentFaction)}`;$('#hubFactionChoices').innerHTML=FACTIONS.map(f=>{let open=META.factions[f.id],active=META.currentFaction===f.id,rank=factionRank(f.id),value=factionContribution(f.id),next=[10,25,50,null][rank-1];return `<button class="faction-choice ${active?'selected':''} ${open?'':'locked'}" data-faction="${f.id}" ${open?'':'disabled'}><span>${open?f.name:'未発見の勢力'}</span><b>${open?`${f.rankNames[rank-1]}${active?'・所属中':''}`:'LOCKED'}</b><small>${open?f.desc:'イベントや条件達成で発見できる'}</small><em>${open?(next?`貢献度 ${value}/${next}`:`貢献度 ${value}・最高階級`):'？？？'}</em></button>`}).join('');document.querySelectorAll('[data-faction]:not(:disabled)').forEach(button=>button.onclick=()=>{changeBaseFaction(button.dataset.faction);renderFactionFacility()});$('#gold').textContent=META.baseGold;show('factionScreen')}
function upgradeVault(){if(META.vaultLevel>=3)return;let cost=50*(META.vaultLevel+1);if(META.baseGold<cost){toast('拠点の保管金が足りない');return}META.baseGold-=cost;META.vaultLevel++;checkMeta();saveMeta();renderVault();toast(`保管庫を${vaultCapacity()}枠へ拡張した`)}
function forgeRepair(uid){let item=META.stash.find(x=>x.uid===uid),cost=item?(6-item.durability)*3:0;if(!item||cost<=0)return;if(META.baseGold<cost){toast('拠点の保管金が足りない');return}META.baseGold-=cost;item.durability=6;saveMeta();renderForge();toast('装備を完全修理した')}
function forgeTemper(uid){let item=META.stash.find(x=>x.uid===uid),level=item?.evolution?.level||0,cost=30*(level+1);if(!item||level>=5)return;if(META.baseGold<cost){toast('拠点の保管金が足りない');return}META.baseGold-=cost;item.evolution={...(item.evolution||{}),level:level+1};unlock('first_forge');saveMeta();renderForge();toast(`${ITEMS[item.templateId].name}を+${level+1}へ鍛錬した`)}
function applyActiveRole(id){state.role=id;let r=ROLES[id];state.maxHp+=r.hp||0;state.hp=state.maxHp;state.gold+=r.gold||0}
function reset(){Object.entries(ITEMS).forEach(([id,x])=>{if(x.baseName===undefined)x.baseName=x.name;x.name=isEvolved(id)?EVOLUTIONS[id].name:x.baseName});META.stats.runs++;saveMeta();state=makeRunState();if(META.currentRole&&META.roles[META.currentRole]){applyActiveRole(META.currentRole);renderDungeonSelection();show('dungeonScreen')}else{renderRoles();show('roleScreen')}renderAll()}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$('#'+id).classList.remove('hidden')}
function renderAll(){
 $('#floor').textContent=state.floor;$('#maxFloor').textContent=currentDungeon().rooms;$('#playerHp').textContent=state.hp;$('#gold').textContent=state.gold;$('#roleName').textContent=state.role?`${ROLES[state.role].name} Lv.${jobLevel(state.role)}`:'未選択';
 $('#inventory').innerHTML=state.inventory.map((instance,i)=>{let id=instance.templateId,x=ITEMS[id],placed=Object.values(state.placed).some(p=>p.index===i),shape=getShape(x,state.rotations[i]||0),tags=[instance.uid===state.heirloomUid?'家宝':'',instance.insured?'保険':'',instance.scars.length?`傷${instance.scars.length}`:''].filter(Boolean).join('・');return `<div class="inventory-item ${state.selected===i?'selected':''} ${placed?'placed':''}" data-i="${i}" draggable="${!placed}"><div class="item-icon art-icon" style="${itemArtStyle(id)}">${x.icon}</div><div class="item-info"><b>${x.name}</b>${tags?`<small class="item-tags">${tags}</small>`:''}<small>${x.desc}</small><small class="item-rule">${x.rule}</small><small>個体 ${instance.uid.slice(-5)} / 使用 ${instance.uses}</small></div><div>${shapeHtml(shape,x.type)}<div class="item-size">${x.shape.length}マス</div></div></div>`}).join('');
 document.querySelectorAll('.inventory-item').forEach(x=>{x.onclick=()=>{let i=+x.dataset.i;if(Object.values(state.placed).some(p=>p.index===i))return;state.selected=state.selected===i?null:i;state.selectedPlaced=null;renderAll()};x.ondragstart=e=>{let i=+x.dataset.i;if(x.classList.contains('placed')){e.preventDefault();return}state.drag={kind:'inventory',index:i};state.selected=i;state.selectedPlaced=null;e.dataTransfer.effectAllowed='move'}});
 renderPack();renderDeck();$('#startBattle').innerHTML=state.organizing?'整理を確定 <span>↩</span>':'戦闘を開始 <span>→</span>';
}
function renderRoles(){let order=Object.keys(ROLES);$('#jobSummary').textContent=`累計役職レベル ${totalJobLevels()} / 100　選択した役職は戦闘勝利で成長し、習得済み役職の効果はすべて重なります。`;$('#roleChoices').innerHTML=order.map(id=>{let r=ROLES[id],open=META.roles[id],level=jobLevel(id);return `<div class="role-card ${open?'':'locked'}" data-role="${id}">${open?`<div class="role-art" style="${roleArtStyle(id)}"></div>`:''}<span class="role-kind">${open?r.kind:'UNKNOWN'}</span><div class="role-icon ${open?'has-art':''}">${open?r.icon:'？'}</div><h3>${open?r.name:'未発見の役職'}</h3><p>${open?r.desc:(r.advanced?'転職によって解禁される':'特殊な条件で解禁される')}</p>${open?`<span class="role-level">Lv.${level} / ${jobMax(id)}　${level>=jobMax(id)?'MASTER':'育成役職に選択'}</span>`:''}</div>`}).join('');document.querySelectorAll('.role-card:not(.locked)').forEach(el=>el.onclick=()=>chooseRole(el.dataset.role))}
function chooseRole(id){if(META.currentRole)return;META.currentRole=id;if(jobLevel(id)===0)gainJobLevel(id);saveMeta();applyActiveRole(id);renderDungeonSelection();show('dungeonScreen');renderAll();toast(`${ROLES[id].name}に就いた。変更には継職の祭壇が必要`)}
function renderDungeonSelection(){$('#dungeonChoices').innerHTML=DUNGEONS.map((d,i)=>{let open=i<META.dungeonsUnlocked,clears=META.dungeonClears[d.id]||0;return `<button class="dungeon-choice destination-card ${open?'':'locked'}" data-id="${d.id}" ${open?'':'disabled'}><span class="destination-number">0${i+1}</span><div><b>${open?d.name:'未解禁'}</b><small>${open?d.desc:'前のダンジョンを踏破すると解禁'}</small><em>${open?`踏破 ${clears}回　報酬 ×${d.gold.toFixed(2)}`:'LOCKED'}</em></div><span class="destination-arrow">→</span></button>`}).join('');document.querySelectorAll('.destination-card:not(.locked)').forEach(button=>button.onclick=()=>{state.dungeon=button.dataset.id;openExpeditionPreparation()})}
function openExpeditionPreparation(){renderExpedition();$('#selectedDungeonSummary').innerHTML=`選択中：<b>${currentDungeon().name}</b><br>${currentDungeon().desc}`;show('expeditionScreen')}
function renderExpedition(){$('#carryCount').textContent=`${state.carryUids.length} / 3`;$('#hubCarryChoices').innerHTML=(META.stash||[]).filter(item=>item.uid!==state.heirloomUid).map(item=>`<button class="heirloom-choice ${state.carryUids.includes(item.uid)?'selected':''}" data-run-carry="${item.uid}"><b>${ITEMS[item.templateId].icon} ${ITEMS[item.templateId].name}</b><small>敗北時、安全マス外なら喪失／使用 ${item.uses}</small></button>`).join('')||'<p class="empty-state">持ち込める保管装備がありません。</p>';document.querySelectorAll('[data-run-carry]').forEach(button=>button.onclick=()=>{let uid=button.dataset.runCarry;if(state.carryUids.includes(uid))state.carryUids=state.carryUids.filter(x=>x!==uid);else if(state.carryUids.length<3)state.carryUids.push(uid);else{toast('持込保管装備は3個まで');return}renderExpedition()});$('#hubSupplyChoices').innerHTML=Object.entries(SUPPLY_KITS).map(([id,kit])=>`<button class="pack-choice ${state.supplyKit===id?'selected':''}" data-run-supply="${id}"><b>${kit.name}</b><small>${kit.desc}</small></button>`).join('');document.querySelectorAll('[data-run-supply]').forEach(button=>button.onclick=()=>{state.supplyKit=button.dataset.runSupply;renderExpedition()});$('#contractChoices').innerHTML=Object.entries(CONTRACTS).map(([id,c])=>`<div class="contract-choice ${state.contracts.includes(id)?'selected':''}" data-id="${id}"><b>${c.name}</b><small>${c.desc}</small></div>`).join('');document.querySelectorAll('.contract-choice').forEach(el=>el.onclick=()=>{let id=el.dataset.id;state.contracts=state.contracts.includes(id)?state.contracts.filter(x=>x!==id):[...state.contracts,id];renderExpedition()});let heirloom=(META.stash||[]).find(item=>item.uid===state.heirloomUid);$('#factionPreview').innerHTML=`探索先：<b>${currentDungeon().name}</b><br>所属勢力：<b>${state.faction.name}／${factionRankName(state.faction.id)}</b><br>バックパック：<b>${BACKPACKS[state.backpack].name}</b><br>家宝：<b>${heirloom?ITEMS[heirloom.templateId].name:'なし'}</b>`}
function beginPreparedExpedition(){let kit=SUPPLY_KITS[state.supplyKit]||SUPPLY_KITS.blade,selected=new Set([state.heirloomUid,...state.carryUids].filter(Boolean)),departing=META.stash.filter(item=>selected.has(item.uid));if(!departing.length&&!kit.items.length){toast('装備か支給品を最低1個用意してください');return}let hp=state.contracts.reduce((n,id)=>n+(CONTRACTS[id].hp||0),0);state.maxHp=Math.max(12,state.maxHp+hp);state.hp=Math.min(state.hp,state.maxHp);META.stash=META.stash.filter(item=>!selected.has(item.uid));state.inventory=departing.map(item=>{let carried=normalizeItem(item);carried.heirloom=carried.uid===state.heirloomUid;carried.origin=carried.heirloom?'heirloom':'vault';return carried});state.departingCarryUids=departing.filter(item=>item.uid!==state.heirloomUid).map(item=>item.uid);state.inventory.push(...kit.items.map(id=>makeItem(id,{origin:'supply'})));state.gold+=kit.gold||0;META.stats.contractPoints=(META.stats.contractPoints||0)+state.contracts.length;saveMeta();show('prepScreen');renderAll();toast(`${state.faction.name}と共に遠征開始／${kit.name}`)}
$('#beginExpedition').onclick=beginPreparedExpedition;
function renderPack(){
 let safe=new Set(BACKPACKS[state.backpack].safe||[]);$('#pack').innerHTML=Array.from({length:24},(_,i)=>{let y=Math.floor(i/6),mode=y===0?'quick':y===3?'charge':'stable',label=i%6===0?`<span class="pace-mark">${mode==='quick'?'早撃':mode==='stable'?'安定':'溜め'}</span>`:'';return `<div class="cell pace-${mode} ${safe.has(i)?'safe-cell':''}" data-cell="${i}">${label}${safe.has(i)?'<span class="safe-mark">SAFE</span>':''}</div>`}).join('');
 Object.entries(state.placed).forEach(([anchor,p])=>{let instance=itemAt(p.index),id=instance.templateId,item=ITEMS[id],shape=getShape(item,p.rotation||0),dur=instance.durability;shape.forEach((pos,j)=>{let c=(+anchor)+pos[1]*6+pos[0],el=document.querySelector(`[data-cell="${c}"]`);el.innerHTML=`<div draggable="true" class="placed-item ${item.type} ${j===0?'art-piece':''} ${dur<=0?'broken':''} ${state.jammed.includes(p.index)?'jammed':''} ${state.selectedPlaced===anchor?'selected-piece':''}" style="${j===0?itemArtStyle(id):''}" data-anchor="${anchor}" data-dx="${pos[0]}" data-dy="${pos[1]}">${j===0?'':item.icon}<small>${j===0?item.name:''}</small>${j===0?`<small class="durability">耐久 ${dur}/6</small><span class="connector-arrow">${['↑','→','↓','←'][p.rotation||0]}</span>`:''}</div>`})});
 document.querySelectorAll('.cell').forEach(c=>{c.onclick=e=>{let piece=e.target.closest('.placed-item');if(piece){state.selectedPlaced=piece.dataset.anchor;state.selected=null;renderAll();return}placeAt(+c.dataset.cell)};c.ondragover=e=>{e.preventDefault();c.classList.add('drag-over')};c.ondragleave=()=>c.classList.remove('drag-over');c.ondrop=e=>{e.preventDefault();c.classList.remove('drag-over');dropAt(+c.dataset.cell)}});
 document.querySelectorAll('.placed-item').forEach(p=>{p.ondragstart=e=>{state.drag={kind:'placed',anchor:p.dataset.anchor,dx:+p.dataset.dx,dy:+p.dataset.dy};state.selectedPlaced=p.dataset.anchor;e.dataTransfer.effectAllowed='move'};p.oncontextmenu=e=>{e.preventDefault();let q=state.placed[p.dataset.anchor];if(q&&templateAt(q.index)==='cursed_blade'){message('呪いが絡みつき、取り外せません');return}delete state.placed[p.dataset.anchor];state.selectedPlaced=null;message('アイテムを取り外しました');renderAll()}});
 $('#rotateItem').disabled=state.selected===null&&state.selectedPlaced===null;
}
function getShape(item,rotation=0){let pts=item.shape.map(([x,y])=>[x,y]);for(let n=0;n<rotation%4;n++)pts=pts.map(([x,y])=>[-y,x]);let minX=Math.min(...pts.map(p=>p[0])),minY=Math.min(...pts.map(p=>p[1]));return pts.map(([x,y])=>[x-minX,y-minY])}
function shapeHtml(shape,type){let w=Math.max(...shape.map(p=>p[0]))+1,h=Math.max(...shape.map(p=>p[1]))+1,set=new Set(shape.map(p=>p.join(','))),cells='';for(let y=0;y<h;y++)for(let x=0;x<w;x++)cells+=`<i class="shape-pixel ${set.has(x+','+y)?'on '+type:''}"></i>`;return `<div class="shape-preview" title="${w}×${h} / ${shape.length}マス" style="grid-template-columns:repeat(${w},9px)">${cells}</div>`}
function canPlace(cell,index,rotation,ignoreAnchor=null){let item=defAt(index),shape=getShape(item,rotation),x=cell%6,y=Math.floor(cell/6),occupied=new Set();Object.entries(state.placed).forEach(([a,p])=>{if(a===String(ignoreAnchor))return;getShape(defAt(p.index),p.rotation||0).forEach(o=>occupied.add(+a+o[1]*6+o[0]))});let cells=shape.map(o=>[x+o[0],y+o[1]]);return !cells.some(([a,b])=>a<0||b<0||a>5||b>3||occupied.has(b*6+a))}
function placeAt(cell){if(state.selected===null)return;let rotation=state.rotations[state.selected]||0;if(!canPlace(cell,state.selected,rotation)){message('そこには入りません');return}state.placed[cell]={index:state.selected,rotation};state.selected=null;state.selectedPlaced=String(cell);message('配置しました');renderAll()}
function dropAt(cell){if(!state.drag)return;if(state.drag.kind==='inventory'){state.selected=state.drag.index;placeAt(cell)}else{let old=state.drag.anchor,p=state.placed[old],anchor=cell-state.drag.dy*6-state.drag.dx;if(p&&anchor>=0&&canPlace(anchor,p.index,p.rotation||0,old)){delete state.placed[old];state.placed[anchor]=p;state.selectedPlaced=String(anchor);message('移動しました');renderAll()}else message('そこには移動できません')}state.drag=null}
function message(text){$('#packMessage').textContent=text}
function recordRotation(){META.stats.rotations++;checkMeta()}
$('#rotateItem').onclick=()=>{if(state.selected!==null){state.rotations[state.selected]=((state.rotations[state.selected]||0)+1)%4;recordRotation();message('配置前のアイテムを回転しました');renderAll();return}if(state.selectedPlaced!==null){let a=state.selectedPlaced,p=state.placed[a],next=((p.rotation||0)+1)%4;if(canPlace(+a,p.index,next,a)){p.rotation=next;recordRotation();message('アイテムを回転しました');renderAll()}else message('この位置では回転できません')}};
function itemCells(anchor,p){return getShape(defAt(p.index),p.rotation||0).map(([x,y])=>({x:(+anchor)%6+x,y:Math.floor((+anchor)/6)+y}))}
function placementMode(anchor,p){let cells=itemCells(anchor,p),center=cells.reduce((n,c)=>n+c.y,0)/cells.length;return center<1?'quick':center>=3?'charge':'stable'}
function areAdjacent(a,pa,b,pb){return itemCells(a,pa).some(c=>itemCells(b,pb).some(d=>Math.abs(c.x-d.x)+Math.abs(c.y-d.y)===1))}
function deckData(){
 let cards=[],synergy=[],activeAnchors=new Set(),entries=Object.entries(state.placed);
 entries.forEach(([a,p])=>{let instance=itemAt(p.index),sourceId=instance.templateId,item=ITEMS[sourceId];item.cards.forEach(id=>cards.push({...CARDS[id],id,source:item.name,sourceId,sourceUid:instance.uid,sourceAnchor:a}))});
 const own=(a)=>cards.filter(c=>c.sourceAnchor===a), activate=(a,text)=>{activeAnchors.add(a);synergy.push({active:true,text})}, inactive=(item)=>synergy.push({active:false,text:`${item.icon} ${item.rule}`});
 entries.forEach(([a,p])=>{
  let id=templateAt(p.index),item=ITEMS[id],neighbors=entries.filter(([b,q])=>b!==a&&areAdjacent(a,p,b,q)),active=false;
  if(id==='sword'&&neighbors.some(([,q])=>templateAt(q.index)==='shield')){own(a).forEach(c=>c.damage+=1);activate(a,'⚔ 剣 × 盾：斬撃 +1');active=true}
  if(id==='shield'&&neighbors.some(([,q])=>defAt(q.index).type==='weapon')){own(a).forEach(c=>c.block+=2);activate(a,'⬟ 盾 × 武器：防御 +2');active=true}
  if(id==='ember'){let weapons=neighbors.filter(([,q])=>defAt(q.index).type==='weapon');weapons.forEach(([b])=>{own(b).forEach(c=>{if(c.damage)c.damage+=2});activeAnchors.add(b)});if(weapons.length){activate(a,`✦ 熾火：隣接武器 ${weapons.length}個を強化`);active=true}}
  if(id==='herb'&&itemCells(a,p).some(c=>c.y===0)){own(a).forEach(c=>c.heal+=3);activate(a,'❧ 取り出し口：回復 +3');active=true}
  if(id==='dagger'&&neighbors.some(([,q])=>defAt(q.index).type==='weapon')){own(a).forEach(c=>c.damage+=2);activate(a,'† 武器連携：刺突 +2');active=true}
  if(id==='plate'&&itemCells(a,p).some(c=>c.y===3)){own(a).forEach(c=>c.block+=5);activate(a,'▣ 重心安定：防御 +5');active=true}
  if(id==='crystal'){if(neighbors.length){neighbors.forEach(([b])=>{own(b).forEach(c=>c.cost=Math.max(0,c.cost-1));activeAnchors.add(b)});activate(a,`◇ 共鳴：隣接装備 ${neighbors.length}個を軽量化`);active=true}}
  if(id==='bomb'&&itemCells(a,p).some(c=>c.x===5)){own(a).forEach(c=>c.damage+=5);activate(a,'● 即応配置：爆薬 +5');active=true}
  if(id==='spear'&&itemCells(a,p).some(c=>c.y===0)&&getShape(item,p.rotation||0).every(c=>c.x===0)){own(a).forEach(c=>c.damage+=6);activate(a,'↟ 縦貫通：貫通突き +6');active=true}
  if(id==='buckler'&&neighbors.some(([,q])=>defAt(q.index).type==='rune')){own(a).forEach(c=>c.block+=3);activate(a,'◉ 魔力受け：防御 +3');active=true}
  if(id==='flask'&&neighbors.some(([,q])=>templateAt(q.index)==='bomb')){own(a).forEach(c=>c.damage+=4);activate(a,'⚗ 爆薬調合：酸液 +4');active=true}
  if(id==='charm'&&itemCells(a,p).some(c=>c.x===0)){own(a).forEach(c=>{if(c.block)c.block+=3;c.cost=0});activate(a,'☘ 風の通り道：コスト0・防御+3');active=true}
  if(!active)inactive(item);
 });
 entries.forEach(([a,p])=>{let id=templateAt(p.index);if(!isEvolved(id))return;if(id==='sword')own(a).forEach(c=>{if(c.damage)c.damage+=3});if(id==='dagger')own(a).forEach(c=>{if(c.damage)c.damage+=2});if(id==='spear')own(a).forEach(c=>c.cost=Math.max(0,c.cost-1));activate(a,`★ ${EVOLUTIONS[id].name}：${EVOLUTIONS[id].bonus}`)});
 entries.forEach(([a,p])=>{let level=itemAt(p.index).evolution?.level||0;if(!level)return;own(a).forEach(c=>{if(c.damage)c.damage+=level;if(c.block)c.block+=level;if(c.heal)c.heal+=level});activate(a,`鍛錬 +${level}：${ITEMS[templateAt(p.index)].name}`)});
 entries.forEach(([a,p])=>{let scars=itemAt(p.index).scars||[];scars.forEach(scar=>{let effect=SCAR_TYPES[scar.type];if(!effect)return;own(a).forEach(c=>{if(effect.cost)c.cost=Math.max(0,c.cost+effect.cost);if(c.damage)c.damage=Math.max(1,c.damage+(effect.damage||0)+(effect.all||0));if(c.block)c.block=Math.max(1,c.block+(effect.block||0)+(effect.all||0));if(c.heal)c.heal=Math.max(1,c.heal+(effect.heal||0)+(effect.all||0))});activate(a,`${effect.name}：${effect.desc}`)})});
 const find=id=>entries.find(([,p])=>templateAt(p.index)===id), fuse=(a,b,card,name)=>{let x=find(a),y=find(b);if(x&&y&&areAdjacent(x[0],x[1],y[0],y[1])){let instance=itemAt(x[1].index);cards.push({...CARDS[card],id:card,source:name,sourceId:a,sourceUid:instance.uid,sourceAnchor:x[0]});synergy.push({active:true,text:`合成発動：${name}`});activeAnchors.add(x[0]);activeAnchors.add(y[0])}};
 fuse('sword','ember','inferno','焔断ち');fuse('shield','crystal','echoWall','反響障壁');fuse('bomb','flask','starBomb','星喰い爆薬');
 let topWeapons=entries.filter(([a,p])=>defAt(p.index).type==='weapon'&&itemCells(a,p).some(c=>c.y===0)).length,edgeArmor=entries.filter(([a,p])=>defAt(p.index).type==='armor'&&itemCells(a,p).some(c=>c.x===0||c.x===5)).length;
 if(entries.length){cards.push({...CARDS.geometry,id:'geometry',source:'バックパック陣形',sourceId:'formation',damage:topWeapons*2,block:edgeArmor*2,text:`上段武器×${topWeapons}で${topWeapons*2}ダメージ、端の防具×${edgeArmor}で${edgeArmor*2}ブロック。`})}
 entries.forEach(([a,p])=>{let id=templateAt(p.index),dur=itemAt(p.index).durability;if(dur<=0)own(a).forEach(c=>{if(c.damage)c.damage=Math.ceil(c.damage/2);if(c.block)c.block=Math.ceil(c.block/2)});if(state.jammed.includes(p.index))own(a).forEach(c=>c.cost+=1);if(id==='cursed_blade'){entries.filter(([b,q])=>b!==a&&areAdjacent(a,p,b,q)).forEach(([b])=>own(b).forEach(c=>c.cost+=1))}});
 entries.filter(([,p])=>defAt(p.index).type==='rune').forEach(([a,p])=>{let cell=itemCells(a,p)[0],dir=[[0,-1],[1,0],[0,1],[-1,0]][p.rotation||0],tx=cell.x+dir[0],ty=cell.y+dir[1],target=entries.find(([b,q])=>itemCells(b,q).some(c=>c.x===tx&&c.y===ty));if(target){own(target[0]).forEach(c=>{if(c.damage)c.damage+=2;if(c.block)c.block+=2});activate(a,'接続方向一致：対象カード+2')}});
 let bag=BACKPACKS[state.backpack];cards.forEach(c=>{let sourceEntry=entries.find(([,p])=>itemAt(p.index).uid===c.sourceUid);if(bag.rune&&ITEMS[c.sourceId]?.type==='rune'){if(c.damage)c.damage+=bag.rune;if(c.block)c.block+=bag.rune}if(bag.bottom&&sourceEntry&&itemCells(sourceEntry[0],sourceEntry[1]).some(x=>x.y===3)){if(c.damage)c.damage+=bag.bottom;if(c.block)c.block+=bag.bottom}if(sourceEntry){let cells=itemCells(sourceEntry[0],sourceEntry[1]),mode=placementMode(sourceEntry[0],sourceEntry[1]);c.mode=mode;c.rightSide=cells.every(cell=>cell.x>=4);if(mode==='quick'){c.cost=Math.max(0,c.cost-1);if(c.damage)c.damage=Math.max(1,c.damage-1);if(c.block)c.block=Math.max(1,c.block-1);if(c.heal)c.heal=Math.max(1,c.heal-1)}else if(mode==='stable'){if(c.damage)c.damage+=1;if(c.block)c.block+=1;if(c.heal)c.heal+=1}else{c.cost+=1;if(c.damage)c.damage=Math.ceil(c.damage*1.5);if(c.block)c.block=Math.ceil(c.block*1.5);if(c.heal)c.heal=Math.ceil(c.heal*1.5)}}});
 if(state.faction.id==='iron'){let bonus=factionRank('iron');cards.forEach(c=>{if(ITEMS[c.sourceId]?.type==='armor'&&c.block)c.block+=bonus})}
 entries.forEach(([a,p])=>{let mode=placementMode(a,p),name=ITEMS[templateAt(p.index)].name;synergy.push({active:true,text:`${mode==='quick'?'早撃':mode==='stable'?'安定':'溜め'}：${name}`})});
 applyRoleBonuses(cards);
 cards.forEach(c=>{if(c.damage)c.text=c.text.replace(/\d+ダメージ/,c.damage+'ダメージ');if(c.block)c.text=c.text.replace(/\d+ブロック/,c.block+'ブロック');if(c.heal)c.text=c.text.replace(/HPを\d+回復/,`HPを${c.heal}回復`)});
 return{cards,synergy,activeAnchors}
}
function applyRoleBonuses(cards){let learned=Object.keys(ROLES).filter(id=>jobLevel(id)>0),weapon=c=>ITEMS[c.sourceId]?.type==='weapon',armor=c=>ITEMS[c.sourceId]?.type==='armor',supply=c=>ITEMS[c.sourceId]?.type==='supply',rune=c=>ITEMS[c.sourceId]?.type==='rune';learned.forEach(role=>{let lvl=Math.floor((jobLevel(role)-1)/3);cards.forEach(c=>{
 if(role==='warrior'&&weapon(c)&&c.damage)c.damage+=1+lvl;
 if(role==='guardian'&&c.block)c.block+=2+lvl;
 if(role==='scout'&&['dagger','spear'].includes(c.sourceId)&&c.damage)c.damage+=2+lvl;
 if(role==='artificer'&&supply(c)){if(c.damage)c.damage+=2+lvl;if(c.block)c.block+=2+lvl;if(c.heal)c.heal+=2+lvl}
 if(role==='blade_master'&&['sword','dagger'].includes(c.sourceId)&&c.damage)c.damage+=4+lvl;
 if(role==='bulwark'&&c.block)c.block+=5+lvl;
 if(role==='hunter'&&['dagger','spear'].includes(c.sourceId)&&c.damage)c.damage+=4+lvl;
 if(role==='grand_artificer'&&supply(c)){if(c.damage)c.damage+=5+lvl;if(c.block)c.block+=5+lvl;if(c.heal)c.heal+=5+lvl}
 if(role==='arsenal_lord'&&weapon(c)&&c.damage)c.damage+=3+lvl;
 if(role==='pack_saint'){if(c.block)c.block+=4+lvl;if(c.heal)c.heal+=3+lvl}
 if(role==='rune_weaver'&&rune(c))c.cost=0;
 if(role==='grid_dancer'&&c.cost===0){if(c.damage)c.damage+=3+lvl;if(c.block)c.block+=3+lvl}
 if(role==='quickblade'&&c.mode==='quick'&&c.damage)c.damage+=2+lvl;
 if(role==='anchor_knight'&&c.mode==='stable'&&c.block)c.block+=3+lvl;
 if(role==='siege_channeler'&&c.mode==='charge'){if(c.damage)c.damage+=4+lvl*2;if(c.block)c.block+=4+lvl*2;if(c.heal)c.heal+=2+lvl}
 if(role==='right_hand_swordsman'&&c.rightSide&&['sword','dagger'].includes(c.sourceId)&&c.damage)c.damage+=5+lvl;
 if(role==='iron_vanguard'&&armor(c)&&c.block)c.block+=3+lvl;
 if(role==='spore_druid'&&c.heal)c.heal+=3+lvl;
 if(role==='guild_factor'&&supply(c)){if(c.damage)c.damage+=2+lvl;if(c.block)c.block+=2+lvl;if(c.heal)c.heal+=2+lvl}
 if(role==='void_apostle'&&c.sourceId==='cursed_blade'&&c.damage)c.damage+=6+lvl;
 })})}
function renderDeck(){let d=deckData();$('#deckCount').textContent=d.cards.length;$('#deckPreview').innerHTML=d.cards.map(c=>`<div class="mini-card ${c.type}"><span>${c.name}</span><b>${c.cost} ◈</b></div>`).join('')||'<p class="hint">装備からカードが生成されます</p>';$('#synergies').innerHTML=d.synergy.map(s=>`<div class="synergy-line ${s.active?'':'inactive'}">${s.active?'LINK! ':'○ '}${s.text}</div>`).join('');document.querySelectorAll('.placed-item').forEach(el=>el.classList.toggle('active-link',d.activeAnchors.has(el.dataset.anchor)))}
$('#clearPack').onclick=()=>{state.placed=Object.fromEntries(Object.entries(state.placed).filter(([,p])=>templateAt(p.index)==='cursed_blade'));state.selected=null;state.selectedPlaced=null;message(Object.keys(state.placed).length?'呪い装備だけは外せません':'すべて取り外しました');renderAll()};
$('#startBattle').onclick=()=>{let d=deckData(),cursed=state.inventory.map((item,i)=>item.templateId==='cursed_blade'?i:-1).filter(i=>i>=0);if(cursed.some(i=>!Object.values(state.placed).some(p=>p.index===i))){message('呪い装備が出発を拒んでいます。必ず配置してください');return}if(d.cards.length<4){message('最低4枚のカードが必要です');return}let cells=Object.entries(state.placed).flatMap(([a,p])=>itemCells(a,p));if(new Set(cells.map(c=>`${c.x},${c.y}`)).size===24)unlock('perfect_weight');if(cells.some(c=>c.x===0)&&cells.some(c=>c.x===5)&&cells.some(c=>c.y===0)&&cells.some(c=>c.y===3))unlock('edge_master');checkRoleUnlocks();if(state.organizing){finishOrganize(d.cards);return}startBattle(d.cards)};
function startBattle(cards){show('battleScreen');let tier=encounterTier(),pool=ENEMIES.filter(e=>e.floor===tier),base=pool[Math.floor(Math.random()*pool.length)],dungeon=currentDungeon(),progress=1+(state.floor-1)*.04,scaledHp=Math.round(base.hp*dungeon.hp*progress),contractDamage=state.contracts.reduce((n,id)=>n+(CONTRACTS[id].enemyDamage||0),0);state.enemy={...base,moves:base.moves.map(m=>({...m,damage:m.damage+contractDamage+dungeon.damage+Math.floor((state.floor-1)/3),armor:(m.armor||0)+dungeon.armor})),hp:scaledHp,maxHp:scaledHp,block:0};discoverEnemy(state.enemy.name);state.jammed=[];state.draw=shuffle(cards.map((c,i)=>({...c,uid:Date.now()+i})));state.discard=[];state.hand=[];state.energy=3;state.block=0;state.move=0;state.organizeUsed=false;draw(5);toast(`${dungeon.name} ${state.floor}/${dungeon.rooms}：${state.enemy.name}が現れた`);renderBattle()}
function finishOrganize(cards){state.organizing=false;state.organizeUsed=true;state.hand=[];state.discard=[];state.draw=shuffle(cards.map((c,i)=>({...c,uid:Date.now()+i})));draw(5);show('battleScreen');toast('荷物を組み替え、デッキを再構築した');renderBattle()}
function shuffle(a){return a.sort(()=>Math.random()-.5)}
function draw(n){while(n--){if(!state.draw.length){state.draw=shuffle(state.discard);state.discard=[]}if(state.draw.length)state.hand.push(state.draw.pop())}}
function renderBattle(){let e=state.enemy,move=e.moves[state.move%e.moves.length],ea=ENEMY_ART[e.name]||ENEMY_ART['鉄殻の番兵'];$('#battleScreen').classList.remove('dungeon-floor-1','dungeon-floor-2','dungeon-floor-3');$('#battleScreen').classList.add('battle-screen-art',`dungeon-floor-${state.floor}`);$('#playerPortrait').setAttribute('style',roleArtStyle(state.role));$('#enemyPortrait').style.backgroundSize=ea[0];$('#enemyPortrait').style.backgroundPosition=ea[1];$('#battlePlayerHp').textContent=state.hp;$('#playerBlock').textContent=state.block;$('#playerBar').style.width=state.hp/state.maxHp*100+'%';$('#enemyName').textContent=e.name;$('#enemyType').textContent=`FLOOR ${state.floor}${e.boss?' — BOSS':''} / ${state.faction.name}`;$('#enemyHp').textContent=Math.max(0,e.hp);$('#enemyMaxHp').textContent=e.maxHp;$('#enemyBar').style.width=Math.max(0,e.hp/e.maxHp*100)+'%';let hidden=state.contracts.includes('blind')&&state.move%2===1;$('#intent').textContent=hidden?'次の行動: ？？？':('次の行動: '+move.label+(e.block?`　◆${e.block}`:''));$('#energy').textContent=state.energy;$('#drawCount').textContent=state.draw.length;$('#discardCount').textContent=state.discard.length;$('#organizePack').disabled=state.organizeUsed||state.energy<1||state.contracts.includes('no_sort');$('#hand').innerHTML=state.hand.map((c,i)=>`<div class="card ${c.type} ${c.cost>state.energy?'disabled':''}" data-i="${i}"><span class="cost">${c.cost}</span><b>${c.name}</b><p>${c.text}</p><em>${c.source}</em></div>`).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>playCard(+c.dataset.i))}
const renderBattleBase=renderBattle;
renderBattle=function(){renderBattleBase();let e=state.enemy,dungeon=currentDungeon(),visual=Math.min(3,Math.ceil(state.floor/dungeon.rooms*3));drawCharacter($('#playerPortrait'),META.character?.body||0,META.character?.hair||0,state.role);$('#battleScreen').classList.remove('dungeon-floor-1','dungeon-floor-2','dungeon-floor-3',`dungeon-floor-${state.floor}`);$('#battleScreen').classList.add(`dungeon-floor-${visual}`);$('#enemyType').textContent=`${dungeon.name}　${state.floor}/${dungeon.rooms}${e.boss?' — BOSS':''}　/　${state.faction.name}`}
function registerUse(id){META.stats.cards++;if(id){META.mastery[id]=(META.mastery[id]||0)+1;if(isEvolved(id)&&EVOLUTIONS[id])ITEMS[id].name=EVOLUTIONS[id].name}checkMeta()}
function playCard(i){let c=state.hand[i];if(!c||c.cost>state.energy)return;state.energy-=c.cost;registerUse(c.sourceId);let instance=state.inventory.find(item=>item.uid===c.sourceUid),justBroke=false;if(instance&&c.sourceId!=='formation'){instance.uses++;instance.durability=Math.max(0,instance.durability-1);justBroke=instance.durability===0}let msg=c.name+'：';if(c.damage){let raw=c.damage+state.attackBuff,absorbed=Math.min(raw,state.enemy.block||0),dmg=raw-absorbed;state.enemy.block=Math.max(0,(state.enemy.block||0)-raw);state.attackBuff=0;state.enemy.hp-=dmg;msg+=`${dmg}ダメージ `;pulse('.enemy-card','hit')}if(c.block){state.block+=c.block;msg+=`${c.block}防御 `}if(c.heal){let old=state.hp;state.hp=Math.min(state.maxHp,state.hp+c.heal);msg+=`${state.hp-old}回復 `}if(c.selfDamage){state.hp=Math.max(1,state.hp-c.selfDamage);msg+=`反動${c.selfDamage} `}if(c.buff){state.attackBuff+=c.buff;msg+='次の攻撃強化 '}if(c.energy){state.energy+=c.energy;msg+=`エネルギー+${c.energy} `}if(justBroke){[...state.hand,...state.draw,...state.discard].filter(x=>x.sourceUid===c.sourceUid).forEach(x=>{if(x.damage)x.damage=Math.ceil(x.damage/2);if(x.block)x.block=Math.ceil(x.block/2)});msg+='【装備破損】 '}state.hand.splice(i,1);if(!c.exhaust)state.discard.push(c);$('#battleLog').textContent=msg;if(state.enemy.hp<=0){winBattle();return}renderBattle()}
$('#organizePack').onclick=()=>{if(state.organizeUsed||state.energy<1||state.contracts.includes('no_sort'))return;state.energy--;state.organizing=true;state.organizesRun++;META.stats.organizes++;checkMeta();show('prepScreen');renderAll();message('戦闘中整理：配置を変更して「整理を確定」してください')};
function adjustJammedCost(delta){let uids=state.jammed.map(i=>itemAt(i)?.uid);[...state.hand,...state.draw,...state.discard].forEach(c=>{if(uids.includes(c.sourceUid))c.cost=Math.max(0,c.cost+delta)})}
$('#endTurn').onclick=()=>{let move=state.enemy.moves[state.move%state.enemy.moves.length],hit=Math.max(0,move.damage-state.block);state.hp-=hit;state.block=0;state.enemy.block=move.armor||0;state.discard.push(...state.hand);state.hand=[];state.move++;state.organizeUsed=false;adjustJammedCost(-1);let equipped=Object.values(state.placed);state.jammed=[];if(equipped.length&&Math.random()<.65){let victim=equipped[Math.floor(Math.random()*equipped.length)];state.jammed=[victim.index]}pulse('.player-card','hit');if(state.hp<=0){endGame(false);return}state.energy=3;draw(5);adjustJammedCost(1);$('#battleLog').textContent=`${state.enemy.name}の攻撃。${hit}ダメージ。${state.jammed.length?'装備1個が妨害された。':''}`;renderBattle()};
function winBattle(){let factionGold=state.faction.id==='void'?1+factionRank('void')*.05:1,mult=state.contracts.reduce((n,id)=>n*(CONTRACTS[id].gold||1),1)*factionGold*currentDungeon().gold;state.gold+=Math.round((12+state.floor*3)*mult);state.hp=Math.min(state.maxHp,state.hp+3+(state.faction.id==='spore'?factionRank('spore'):0));gainFactionContribution(state.faction.id,state.floor===currentDungeon().rooms?3:1);let gained=gainJobLevel(state.role);if(gained)toast(`${ROLES[state.role].name} Lv.${jobLevel(state.role)}へ成長`);if(state.floor===currentDungeon().rooms){endGame(true);return}show('rewardScreen');let pool=['dagger','plate','crystal','bomb','spear','buckler','flask','charm',...(state.faction.id==='void'?['cursed_blade']:[])].filter(x=>!hasTemplate(x));if(state.faction.id==='iron')pool.push('plate','buckler');let opts=[...new Set(shuffle(pool))].slice(0,3);$('#rewards').innerHTML=opts.map(id=>{let x=ITEMS[id];return `<div class="reward" data-id="${id}"><div class="big-icon art-reward" style="--item-x:${ITEM_ART[id][0]/3*100}%;--item-y:${ITEM_ART[id][1]/2*100}%"></div><h3>${x.name}</h3><p>${x.desc}<br>${x.rule}<br>${x.shape.length}マス</p></div>`}).join('');document.querySelectorAll('.reward').forEach(r=>r.onclick=()=>{discoverItem(r.dataset.id);state.inventory.push(makeItem(r.dataset.id));checkCollector();state.floor++;if(BACKPACKS[state.backpack].living)Object.entries(state.placed).forEach(([a,p])=>{let next=Math.floor(Math.random()*4);if(canPlace(+a,p.index,next,a))p.rotation=next});state.selectedPlaced=null;showMap()})}
const winBattleBase=winBattle;
winBattle=function(){winBattleBase();if($('#rewardScreen').classList.contains('hidden')||document.querySelector('#rewards .reward'))return;$('#rewards').innerHTML='<div class="reward" id="fallbackReward"><div class="big-icon">◈</div><h3>補給金</h3><p>装備候補を集め切ったため、代わりに20Gを得る。</p></div>';$('#fallbackReward').onclick=()=>{state.gold+=20;state.floor++;state.selectedPlaced=null;showMap()}}
const ROUTES={event:{icon:'?',name:'未知の物音',desc:'利益か災いか'},shop:{icon:'♜',name:'行商人',desc:'ゴールドで装備を購入'},rest:{icon:'♨',name:'野営地',desc:'HPを回復'},scavenge:{icon:'✧',name:'崩れた保管庫',desc:'HPを賭けて物資を探す'},guild:{icon:'♝',name:'継職の祭壇',desc:'役職変更・修練・上級職解禁'}};
function showMap(){show('mapScreen');let finalApproach=state.floor===currentDungeon().rooms,types=finalApproach?['guild',...shuffle(['event','shop','rest','scavenge']).slice(0,2)]:shuffle(['event','shop','rest','scavenge','guild']).slice(0,3);$('#mapNodes').innerHTML=types.map(t=>{let r=ROUTES[t];return `<div class="map-node" data-type="${t}"><div class="node-icon">${r.icon}</div><b>${r.name}</b><small>${r.desc}</small></div>`}).join('');document.querySelectorAll('.map-node').forEach(n=>n.onclick=()=>enterRoute(n.dataset.type))}
function enterRoute(type){if(type==='guild'){openGuild();return}if(type==='shop'){openShop();return}if(type==='rest'){let heal=Math.min(12,state.maxHp-state.hp);state.hp+=heal;repairAllItems();toast(`${heal} HP回復し、全装備を修理した`);continueRun();return}if(type==='scavenge'){state.hp=Math.max(1,state.hp-6);state.gold+=24;toast('6 HPを失い、24Gを発見した');continueRun();return}openEvent()}
function changeRoleAtShrine(id){if(!META.roles[id]||id===state.role)return;let old=ROLES[state.role],next=ROLES[id];state.maxHp=Math.max(1,state.maxHp-(old.hp||0)+(next.hp||0));state.hp=Math.min(state.hp,state.maxHp);state.role=id;META.currentRole=id;if(jobLevel(id)===0)gainJobLevel(id);saveMeta();toast(`${next.name}へ転職した`);continueRun()}
function showRoleChangeChoices(){let roles=Object.keys(ROLES).filter(id=>META.roles[id]&&id!==state.role);$('#eventText').textContent='ここでのみ現在の役職を変更できる。習得済みレベルはすべて残る。';$('#eventChoices').innerHTML=roles.map(id=>`<button class="event-choice role-change" data-role="${id}">${ROLES[id].icon} ${ROLES[id].name} Lv.${jobLevel(id)}</button>`).join('')+'<button class="event-choice" id="cancelRoleChange">戻る</button>';document.querySelectorAll('.role-change').forEach(button=>button.onclick=()=>changeRoleAtShrine(button.dataset.role));$('#cancelRoleChange').onclick=openGuild}
function openGuild(){show('eventScreen');$('#eventIcon').textContent='♝';$('#eventTitle').textContent='継職の祭壇';let next=PROMOTIONS[state.role],level=jobLevel(state.role),canPromote=next&&level>=5&&!META.roles[next];$('#eventText').textContent=canPromote?`${ROLES[state.role].name} Lv.${level}の経験が、上級職への道を開いている。`:'役職の変更、または現在の役職の修練を行える。';$('#eventChoices').innerHTML=`${canPromote?`<button class="event-choice" id="promoteRole">${ROLES[next].icon} ${ROLES[next].name}を解禁</button>`:''}<button class="event-choice" id="changeRole">役職を変更する</button><button class="event-choice" id="trainRole">${ROLES[state.role].name}を修練する</button>`;if(canPromote)$('#promoteRole').onclick=()=>{META.roles[next]=true;gainJobLevel(next);saveMeta();toast(`上級職「${ROLES[next].name}」を解禁した`);openGuild()};$('#changeRole').onclick=showRoleChangeChoices;$('#trainRole').onclick=()=>{let gain=gainJobLevel(state.role);toast(gain?'役職レベルが1上がった':'合計または役職レベルが上限に達している');continueRun()}}
const EVENTS=[
 {icon:'☽',title:'囁く井戸',text:'底から「重いものを寄越せ」と声が響く。',choices:[{label:'10Gを投げる',effect:()=>{if(state.gold<10)return false;state.gold-=10;state.maxHp+=5;state.hp+=5;toast('最大HP +5') }},{label:'立ち去る',effect:()=>toast('何も起こらなかった')}]},
 {icon:'⚙',title:'壊れた昇降機',text:'危険な近道と、遠回りの階段がある。',choices:[{label:'昇降機を使う（50%）',effect:()=>{if(Math.random()<.5){state.gold+=30;toast('30Gを発見した')}else{state.hp=Math.max(1,state.hp-9);toast('落下して9ダメージ')}}},{label:'階段を使う（HP+4）',effect:()=>{state.hp=Math.min(state.maxHp,state.hp+4);toast('慎重に進み4HP回復')}}]},
 {icon:'✦',title:'荷造り師の亡霊',text:'亡霊は装備の傷を見つめ、手を差し出した。',choices:[{label:'8Gで全装備を修理',effect:()=>{if(state.gold<8)return false;state.gold-=8;repairAllItems();toast('全装備の耐久度が回復した')}},{label:'断る',effect:()=>toast('亡霊は消えた')}]},
 {icon:'♞',title:'ライバル探索者',text:'同じ戦利品を狙う探索者が道を塞いだ。',choices:[{label:'決闘する（HP-5、35G）',effect:()=>{state.hp=Math.max(1,state.hp-5);state.gold+=35;toast('ライバルを退けた')}},{label:'物資を交換する（15G）',effect:()=>{if(state.gold<15)return false;state.gold-=15;repairAllItems();toast('装備を修理してもらった')}}]},
 {icon:'⌘',title:'灰印の保険屋',text:'「どれか一つなら、塔の外まで必ず回収してみせよう」',choices:[{label:'12Gで未保険の装備1個に保険',effect:()=>{if(state.gold<12)return false;let pool=state.inventory.filter(item=>!item.insured&&item.uid!==state.heirloomUid);if(!pool.length){toast('保険を付けられる装備がない');return}state.gold-=12;let item=pool[Math.floor(Math.random()*pool.length)];item.insured=true;toast(`${ITEMS[item.templateId].name}に保険タグが付いた`)}},{label:'立ち去る',effect:()=>toast('契約を見送った')}]},
 {icon:'◉',title:'名を失った巡礼者',text:'紫の外套をまとった者が、存在しない道への同行を求めている。',choices:[{label:'最大HPを3捧げ、虚無の巡礼者を発見',effect:()=>{if(META.factions.void){toast('虚無の巡礼者はすでに発見済み');return}state.maxHp=Math.max(12,state.maxHp-3);state.hp=Math.min(state.hp,state.maxHp);unlockFaction('void','名を失った巡礼者と契約した')}},{label:'目を合わせず立ち去る',effect:()=>toast('巡礼者は闇へ消えた')}]}];
function openEvent(){show('eventScreen');let e=EVENTS[Math.floor(Math.random()*EVENTS.length)];$('#eventIcon').textContent=e.icon;$('#eventTitle').textContent=e.title;$('#eventText').textContent=e.text;$('#eventChoices').innerHTML=e.choices.map((c,i)=>`<button class="event-choice" data-i="${i}">${c.label}</button>`).join('');document.querySelectorAll('.event-choice').forEach(b=>b.onclick=()=>{let ok=e.choices[+b.dataset.i].effect();if(ok===false){toast('ゴールドが足りない');return}META.stats.events++;checkMeta();continueRun()})}
function checkCollector(){if(state.inventory.length>=10)unlock('collector');if(['sword','dagger','spear'].every(hasTemplate))unlockRole('arsenal_lord','剣・短剣・槍を一度に集めた')}
function checkRoleUnlocks(){let entries=Object.entries(state.placed),ids=entries.map(([,p])=>templateAt(p.index));if(['shield','plate','buckler'].every(id=>ids.includes(id)))unlockRole('pack_saint','三種の防具を同時に配置した');let runes=entries.filter(([,p])=>['ember','crystal'].includes(templateAt(p.index)));if(runes.length===2){let corners=[[0,0],[5,3],[5,0],[0,3]],hits=runes.map(([a,p])=>itemCells(a,p).filter(c=>corners.some(k=>k[0]===c.x&&k[1]===c.y)));if(hits[0].some(a=>hits[1].some(b=>a.x+b.x===5&&a.y+b.y===3)))unlockRole('rune_weaver','二つのルーンで対角線を結んだ')}let byAnchor=new Map(entries.map(([a,p])=>[+a,defAt(p.index).type]));for(let y=0;y<3;y++)for(let x=0;x<5;x++){let q=y*6+x,square=[q,q+1,q+6,q+7];if(square.every(n=>byAnchor.has(n))&&new Set(square.map(n=>byAnchor.get(n))).size===4)unlockRole('grid_dancer','異種装備の基点で2×2の正方形を作った')}let weapons=entries.filter(([,p])=>defAt(p.index).type==='weapon');if(weapons.length===1&&['sword','dagger'].includes(templateAt(weapons[0][1].index))&&itemCells(weapons[0][0],weapons[0][1]).every(c=>c.x>=4))unlockRole('right_hand_swordsman','右2列に片手武器だけを構えた')}
function openShop(){show('shopScreen');let ids=shuffle(Object.keys(ITEMS).filter(id=>!hasTemplate(id)&&id!=='cursed_blade')).slice(0,3),factionDiscount=state.faction.id==='guild'?1-factionRank('guild')*.05:1,discount=(BACKPACKS[state.backpack].shop||1)*factionDiscount;$('#shopItems').innerHTML=ids.map(id=>{let x=ITEMS[id],price=Math.round((14+x.shape.length*4)*discount);return `<button type="button" class="reward shop-item" data-id="${id}" data-price="${price}"><div class="big-icon art-reward" style="--item-x:${ITEM_ART[id][0]/3*100}%;--item-y:${ITEM_ART[id][1]/2*100}%"></div><h3>${x.name}</h3><p>${x.rule}<br>${x.shape.length}マス</p><b>${price}G</b></button>`}).join('')||'<p>売り切れだ。</p>';document.querySelectorAll('.shop-item').forEach(el=>el.addEventListener('click',()=>{if(el.disabled)return;let id=el.dataset.id,price=Number(el.dataset.price),before=state.gold;if(!Number.isFinite(price)||price<0){toast('価格データが不正です');return}if(before<price){toast('ゴールドが足りない');return}el.disabled=true;state.gold=before-price;$('#gold').textContent=String(state.gold);state.inventory.push(makeItem(id));META.stats.shopBuys++;checkMeta();checkCollector();el.remove();toast(`${ITEMS[id].name}を${price}Gで購入（${before}G → ${state.gold}G）`)},{once:true}));$('#leaveShop').onclick=continueRun}
function continueRun(){show('prepScreen');renderAll()}
function toast(text){let el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800)}
function pulse(selector,cls){let el=$(selector);el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls);setTimeout(()=>el.classList.remove(cls),300)}
function safeProtectedUids(){let safe=new Set(BACKPACKS[state.backpack].safe||[]),uids=new Set;state.inventory.filter(item=>item.insured).forEach(item=>uids.add(item.uid));Object.entries(state.placed).forEach(([anchor,p])=>{let cells=itemCells(anchor,p).map(c=>c.y*6+c.x);if(cells.length&&cells.every(cell=>safe.has(cell)))uids.add(itemAt(p.index).uid)});return uids}
function returnItems(items,failed){let stored=0;items.filter(item=>item.origin!=='supply').forEach(item=>{let saved=normalizeItem(item);saved.heirloom=false;saved.insured=false;saved.origin='vault';if(failed&&saved.scars.length<3){let available=Object.keys(SCAR_TYPES).filter(type=>!saved.scars.some(s=>s.type===type)),type=available[Math.floor(Math.random()*available.length)];if(type)saved.scars=[...saved.scars,{type,floor:state.floor,dungeon:state.dungeon,at:Date.now()}]}let i=META.stash.findIndex(old=>old.uid===saved.uid);if(i>=0){META.stash[i]=saved;stored++}else if(META.stash.length<vaultCapacity()){META.stash.push(saved);stored++}});checkMeta();return stored}
let pendingEnd=null,recoverySelected=[];
function endGame(win){let dungeon=currentDungeon(),dungeonIndex=DUNGEONS.findIndex(d=>d.id===dungeon.id),unlocked=false;if(win){META.stats.wins++;META.dungeonClears[dungeon.id]=(META.dungeonClears[dungeon.id]||0)+1;if(META.dungeonsUnlocked===dungeonIndex+1&&META.dungeonsUnlocked<DUNGEONS.length){META.dungeonsUnlocked++;unlocked=true}if(Object.keys(state.placed).length<=2)unlock('minimalist');if(state.hp===1)unlock('last_stand');checkMeta()}let safe=safeProtectedUids(),eligible=state.inventory.filter(item=>item.origin!=='supply'),mandatory=eligible.filter(item=>item.origin==='heirloom'||safe.has(item.uid)||win&&item.origin==='vault'),optional=win?eligible.filter(item=>item.origin==='loot'&&!safe.has(item.uid)):[],recovered=win?state.gold:Math.floor(state.gold*.25);pendingEnd={win,dungeon,unlocked,recovered,mandatory};if(win&&optional.length){recoverySelected=[];$('#recoveryChoices').innerHTML=optional.map(item=>`<button class="recovery-choice" data-uid="${item.uid}"><b>${ITEMS[item.templateId].icon} ${ITEMS[item.templateId].name}</b><small>${ITEMS[item.templateId].rule}</small></button>`).join('');document.querySelectorAll('.recovery-choice').forEach(button=>button.onclick=()=>{let uid=button.dataset.uid;if(recoverySelected.includes(uid))recoverySelected=recoverySelected.filter(x=>x!==uid);else if(recoverySelected.length<2)recoverySelected.push(uid);else{toast('追加戦果は2個まで');return}button.classList.toggle('selected',recoverySelected.includes(uid));$('#recoveryCapacity').textContent=`追加戦果 ${recoverySelected.length} / 2　保管庫空き ${Math.max(0,vaultCapacity()-META.stash.length)}枠`});$('#recoveryCapacity').textContent=`追加戦果 0 / 2　保管庫空き ${Math.max(0,vaultCapacity()-META.stash.length)}枠`;show('recoveryScreen');return}finishEndGame([])}
function finishEndGame(selected){if(!pendingEnd)return;let {win,dungeon,unlocked,recovered,mandatory}=pendingEnd,chosen=state.inventory.filter(item=>selected.includes(item.uid)),stored=returnItems([...mandatory,...chosen],!win);META.baseGold+=recovered;META.selectedCarryUids=(state.departingCarryUids||[]).filter(uid=>META.stash.some(item=>item.uid===uid));if(!META.stash.some(item=>item.uid===META.selectedHeirloomUid))META.selectedHeirloomUid=null;saveMeta();show('gameOver');$('#endTitle').textContent=win?`${dungeon.name} 踏破成功！`:'探索終了';$('#endText').textContent=win?`${recovered}Gを持ち帰り、家宝・持込品・安全戦果を含む${stored}個を保管した。${unlocked?'次のダンジョンが解禁された。':''}`:`${dungeon.name} 第${state.floor}階層で力尽きた。${recovered}Gと保護された装備${stored}個を回収した。安全マス外の持込品は失われた。`;pendingEnd=null}
function renderMeta(){let found=SECRETS.filter(s=>META.unlocked[s.id]).length;$('#metaRuns').textContent=META.stats.runs;$('#metaWins').textContent=META.stats.wins;$('#secretCount').textContent=`${found} / ${SECRETS.length}`;$('#masteryList').innerHTML=Object.entries(EVOLUTIONS).map(([id,e])=>{let n=META.mastery[id]||0,done=n>=e.need;return `<div class="mastery-entry"><div class="mastery-head"><b class="${done?'evolved':''}">${done?'★ '+e.name:ITEMS[id].baseName||ITEMS[id].name}</b><span>${Math.min(n,e.need)} / ${e.need}</span></div><div class="mastery-bar"><i style="width:${Math.min(100,n/e.need*100)}%"></i></div><small>${done?e.bonus:'使用するたび記憶が蓄積される'}</small></div>`}).join('');$('#secretList').innerHTML=SECRETS.map(s=>{let open=META.unlocked[s.id];return `<div class="secret-entry ${open?'unlocked':'locked'}"><b>${open?'✦ '+s.name:'◆ ？？？？？？'}</b><small>${open?s.hint+' / '+s.reward:'条件も報酬も隠されている'}</small></div>`}).join('');$('#roleArchive').innerHTML=Object.entries(ROLES).filter(([id])=>META.roles[id]).map(([,r])=>`<span class="role-chip ${r.advanced?'advanced':''} ${r.hidden?'hidden-role':''}">${r.icon} ${r.name}</span>`).join('');$('#rumorList').innerHTML=RUMORS.map(([name,text,need])=>`<div class="rumor"><b>${META.stats.cards>=need?name:'？？？'}</b><br>${META.stats.cards>=need?text:`あと${need-META.stats.cards}回カードを使えば噂が聞こえる`}</div>`).join('')}
$('#openMeta').onclick=()=>{let current=document.querySelector('.screen:not(.hidden)');state.metaReturn=current?current.id:'prepScreen';renderMeta();show('metaScreen')};
$('#closeMeta').onclick=()=>show(state.metaReturn||'prepScreen');
let titleClicks=0;document.querySelector('h1').onclick=()=>{titleClicks++;if(titleClicks===7){unlock('whisper');document.querySelector('h1').textContent='PACK REMEMBERS';setTimeout(()=>document.querySelector('h1').innerHTML='PACK<span>SPIRE</span>',1400)}};
$('#newExpedition').onclick=reset;
$('#openLoadoutHub').onclick=renderVaultHub;
$('#openStatusHub').onclick=renderStatus;
$('#openCompendiumHub').onclick=()=>renderCompendium('roles');
document.querySelectorAll('#compendiumTabs button').forEach(button=>button.onclick=()=>renderCompendium(button.dataset.tab));
document.addEventListener('click',event=>{let item=event.target.closest?.('.shop-item');if(item&&state&&state.gold>=Number(item.dataset.price))discoverItem(item.dataset.id)},true);
$('#confirmCharacter').onclick=()=>{META.character={...characterDraft};saveMeta();enterHub();toast('探索者の姿を記憶した')};
$('#openFacilities').onclick=()=>$('#facilityModal').classList.remove('hidden');
$('#closeFacilities').onclick=()=>$('#facilityModal').classList.add('hidden');
$('#facilityModal').onclick=event=>{if(event.target.id==='facilityModal')event.currentTarget.classList.add('hidden')};
$('#openForge').onclick=()=>{$('#facilityModal').classList.add('hidden');renderForge()};
$('#openFaction').onclick=()=>{$('#facilityModal').classList.add('hidden');renderFactionFacility()};
$('#upgradeHubVault').onclick=()=>{if(META.vaultLevel>=3)return;let cost=50*(META.vaultLevel+1);if(META.baseGold<cost){toast('拠点の保管金が足りない');return}META.baseGold-=cost;META.vaultLevel++;saveMeta();renderVaultHub();toast(`保管庫を${vaultCapacity()}枠へ拡張した`)};
document.querySelectorAll('.back-to-hub').forEach(button=>button.onclick=enterHub);
$('#backToHubFromDungeon').onclick=enterHub;
$('#backToDungeon').onclick=()=>{renderDungeonSelection();show('dungeonScreen')};
$('#openArchiveHub').onclick=()=>$('#openMeta').click();
$('#upgradeVault').onclick=upgradeVault;
$('#restart').onclick=enterHub;
$('#confirmRecovery').onclick=()=>finishEndGame(recoverySelected);
enterHub();
