const ITEMS = {
  sword:{name:'欠けた剣',icon:'⚔',type:'weapon',shape:[[0,0],[0,1]],desc:'斬撃を2枚生成',rule:'盾に隣接：斬撃+1',cards:['slash','slash']},
  shield:{name:'旅人の盾',icon:'⬟',type:'armor',shape:[[0,0],[1,0]],desc:'防御を2枚生成',rule:'武器に隣接：防御+2',cards:['guard','guard']},
  ember:{name:'熾火のルーン',icon:'✦',type:'rune',shape:[[0,0]],desc:'火花を生成',rule:'武器に隣接：その攻撃+2',cards:['spark']},
  herb:{name:'薬草袋',icon:'❧',type:'supply',shape:[[0,0]],desc:'応急手当を生成',rule:'上端に配置：回復+3',cards:['mend']},
  dagger:{name:'連撃の短剣',icon:'†',type:'weapon',shape:[[0,0]],desc:'刺突を2枚生成',rule:'他の武器に隣接：刺突+2',cards:['stab','stab']},
  plate:{name:'古い胸当て',icon:'▣',type:'armor',shape:[[0,0],[1,0],[0,1]],desc:'堅牢を生成',rule:'下端に接触：防御+5',cards:['brace']},
  crystal:{name:'共鳴結晶',icon:'◇',type:'rune',shape:[[0,0],[0,1]],desc:'整流を生成',rule:'隣接装備のカードコスト-1',cards:['focus']},
  bomb:{name:'煤けた爆弾',icon:'●',type:'supply',shape:[[0,0]],desc:'使い切りの大ダメージ',rule:'右端に配置：爆薬+5',cards:['bomb']},
  spear:{name:'折畳み槍',icon:'↟',type:'weapon',shape:[[0,0],[0,1],[0,2]],desc:'貫通突きを生成',rule:'上端から縦置き：威力+6',cards:['pierce']},
  buckler:{name:'歯車の小盾',icon:'◉',type:'armor',shape:[[0,0]],desc:'受け流しを生成',rule:'ルーンに隣接：防御+3',cards:['parry']},
  flask:{name:'錬金フラスコ',icon:'⚗',type:'supply',shape:[[0,0],[1,0]],desc:'酸液を生成',rule:'爆弾に隣接：酸液+4',cards:['acid']},
  charm:{name:'風読みの護符',icon:'☘',type:'rune',shape:[[0,0]],desc:'追い風を生成',rule:'左端に配置：追い風を強化',cards:['tailwind']},
  cursed_blade:{name:'飢えた呪剣',icon:'☠',type:'weapon',shape:[[0,0],[0,1]],desc:'強力だが周囲を蝕む',rule:'外せない・周囲のカードコスト+1',cards:['devour']}
};
const CARDS={
 slash:{name:'斬撃',type:'attack',cost:1,text:'敵に7ダメージ。',damage:7},
 guard:{name:'防御',type:'skill',cost:1,text:'6ブロックを得る。',block:6},
 spark:{name:'火花',type:'power',cost:1,text:'4ダメージ。次の攻撃+3。',damage:4,buff:3},
 mend:{name:'応急手当',type:'skill',cost:1,text:'HPを4回復する。',heal:4},
 stab:{name:'刺突',type:'attack',cost:0,text:'敵に3ダメージ。',damage:3},
 brace:{name:'堅牢',type:'skill',cost:2,text:'13ブロックを得る。',block:13},
 focus:{name:'整流',type:'power',cost:0,text:'エネルギーを1得る。',energy:1},
 bomb:{name:'爆薬',type:'attack',cost:2,text:'敵に15ダメージ。',damage:15,exhaust:true},
 pierce:{name:'貫通突き',type:'attack',cost:2,text:'敵に11ダメージ。',damage:11},
 parry:{name:'受け流し',type:'skill',cost:0,text:'3ブロックを得る。',block:3},
 acid:{name:'酸液',type:'attack',cost:1,text:'敵に6ダメージ。',damage:6},
 tailwind:{name:'追い風',type:'power',cost:1,text:'エネルギーを1得て4ブロック。',energy:1,block:4},
 devour:{name:'貪食斬り',type:'attack',cost:1,text:'敵に13ダメージ。自身に2ダメージ。',damage:13,selfDamage:2},
 inferno:{name:'焔断ち',type:'attack',cost:2,text:'敵に18ダメージ。',damage:18},
 echoWall:{name:'反響障壁',type:'skill',cost:1,text:'12ブロックを得る。',block:12},
 starBomb:{name:'星喰い爆薬',type:'attack',cost:2,text:'敵に24ダメージ。',damage:24,exhaust:true},
 geometry:{name:'陣形戦術',type:'skill',cost:1,text:'配置に応じて攻撃と防御。',damage:0,block:0}
};
const ENEMIES=[
 {floor:1,name:'鉄殻の番兵',hp:34,moves:[{label:'⚔ 8 ダメージ',damage:8},{label:'⬟ 構えて ⚔ 5',damage:5,armor:6}]},
 {floor:1,name:'洞穴ネズミの群れ',hp:29,moves:[{label:'⚔ 4 × 2',damage:8},{label:'⚔ 6 ダメージ',damage:6}]},
 {floor:1,name:'錆びた荷運び人形',hp:38,moves:[{label:'⚔ 10 ダメージ',damage:10},{label:'… 様子を見る',damage:0}]},
 {floor:2,name:'胞子の魔術師',hp:45,moves:[{label:'⚔ 7 ダメージ',damage:7},{label:'☠ 11 ダメージ',damage:11}]},
 {floor:2,name:'鎧喰い虫',hp:50,moves:[{label:'⚔ 9 ダメージ',damage:9},{label:'⚔ 5 × 2',damage:10}]},
 {floor:2,name:'虚ろな騎士',hp:54,moves:[{label:'⚔ 13 ダメージ',damage:13},{label:'⬟ 構えて ⚔ 6',damage:6,armor:8}]},
 {floor:3,boss:true,name:'荷喰らい',hp:72,moves:[{label:'⚔ 12 ダメージ',damage:12},{label:'⚔ 6 × 2',damage:12},{label:'☠ 17 ダメージ',damage:17}]}
];
const EVOLUTIONS={sword:{need:100,name:'黒鉄の百斬剣',bonus:'斬撃の基礎威力+3'},dagger:{need:75,name:'千手の短剣',bonus:'刺突の基礎威力+2'},spear:{need:60,name:'天穿つ折畳み槍',bonus:'貫通突きのコスト-1'}};
const ROLES={
 warrior:{name:'戦士',icon:'⚔',kind:'基本職',desc:'すべての武器攻撃+1。最大HP+2。',hp:2},
 guardian:{name:'守護兵',icon:'⬟',kind:'基本職',desc:'防御カード+2。最大HP+2。',hp:2},
 scout:{name:'斥候',icon:'➶',kind:'基本職',desc:'短剣と槍の攻撃+2。初期ゴールド+5。',gold:5},
 artificer:{name:'工匠',icon:'⚙',kind:'基本職',desc:'道具由来の数値効果+2。',effect:2},
 blade_master:{name:'剣聖',icon:'♰',kind:'上級職',desc:'剣と短剣の攻撃+4。最大HP+3。',hp:3,advanced:true},
 bulwark:{name:'城塞騎士',icon:'▦',kind:'上級職',desc:'防御カード+5。最大HP+4。',hp:4,advanced:true},
 hunter:{name:'魔獣狩り',icon:'⌁',kind:'上級職',desc:'短剣と槍の攻撃+4。初期ゴールド+8。',gold:8,advanced:true},
 grand_artificer:{name:'錬装術師',icon:'⚗',kind:'上級職',desc:'道具由来の数値効果+5。最大HP+2。',hp:2,advanced:true},
 arsenal_lord:{name:'万兵の王',icon:'♛',kind:'隠し職',desc:'全武器攻撃+3。初期ゴールド+5。',gold:5,hidden:true,hint:'三種の刃を一度に所有する'},
 pack_saint:{name:'不動の聖者',icon:'✜',kind:'隠し職',desc:'防御+4、回復+3。最大HP+5。',hp:5,hidden:true,hint:'三種の盾を同時に詰める'},
 rune_weaver:{name:'境界の織手',icon:'⌘',kind:'隠し職',desc:'ルーン由来カードがコスト0。最大HP+2。',hp:2,hidden:true,hint:'対角の隅を二つのルーンで結ぶ'},
 grid_dancer:{name:'盤上舞踏家',icon:'※',kind:'隠し職',desc:'0コストカードの攻撃・防御+3。',hidden:true,hint:'四つの異種装備で中央の正方形を作る'}
};
const BACKPACKS={standard:{name:'探索者の鞄',desc:'癖のない標準型。'},merchant:{name:'行商人の鞄',desc:'商店価格20%引き。',shop:.8},arcane:{name:'魔導鞄',desc:'ルーン由来カードの数値効果+2。',rune:2},coffin:{name:'棺型ケース',desc:'下端のカードの数値効果+2。',bottom:2},living:{name:'生きている鞄',desc:'戦闘後、配置した装備がランダムに回転する。',living:true}};
const CONTRACTS={fury:{name:'焦燥の契約',desc:'敵の攻撃+2 / 報酬金+50%',enemyDamage:2,gold:1.5},blind:{name:'盲目の契約',desc:'敵の一部行動予告を隠す',blind:true},fragile:{name:'脆弱の契約',desc:'最大HP-8 / 契約ポイント+1',hp:-8},no_sort:{name:'封印の契約',desc:'戦闘中整理禁止 / 報酬金+30%',noSort:true,gold:1.3}};
const FACTIONS=[{id:'iron',name:'鉄殻軍',desc:'防具報酬が出やすく、敵の防御+3'},{id:'spore',name:'胞子教団',desc:'戦闘後の回復+2、敵のHP+5'},{id:'guild',name:'荷造り師組合',desc:'商店が安く、イベントが増える'},{id:'void',name:'虚無の巡礼者',desc:'呪い装備が出現し、獲得金+25%'}];
const RUMORS=[['剣と火','欠けた刃を熾火へ寄せれば、存在しない一枚が生まれる。',0],['反響する壁','盾と紫の結晶は、互いの不足を埋める。',15],['星を喰う調合','爆薬の隣でフラスコを傾けよ。',30],['境界線','ルーンには向きがある。矢印の先へ魔力が流れる。',5],['不動の者','三種の防具を同時に収めた者へ、聖者は応える。',40],['四角形の舞','異なる四分類の基点で正方形を作れ。',60],['対角の織手','二つのルーンで鞄の対角を結べ。',75],['呪いの市場','虚無の巡礼者が支配する階では、重さのない剣に注意せよ。',20]];
const PROMOTIONS={warrior:'blade_master',guardian:'bulwark',scout:'hunter',artificer:'grand_artificer'};
const ITEM_ART={sword:[0,0],shield:[1,0],ember:[2,0],herb:[3,0],dagger:[0,1],plate:[1,1],crystal:[2,1],bomb:[3,1],spear:[0,2],buckler:[1,2],flask:[2,2],charm:[3,2],cursed_blade:[0,1]};
const ROLE_ART={warrior:[0,0],guardian:[1,0],scout:[2,0],artificer:[3,0],blade_master:[0,1],bulwark:[1,1],hunter:[2,1],grand_artificer:[3,1],arsenal_lord:[0,2],pack_saint:[1,2],rune_weaver:[2,2],grid_dancer:[3,2]};
const ENEMY_ART={'鉄殻の番兵':['600% 200%','0% 0%'],'洞穴ネズミの群れ':['600% 200%','20% 0%'],'錆びた荷運び人形':['600% 200%','40% 0%'],'胞子の魔術師':['600% 200%','60% 0%'],'鎧喰い虫':['300% 200%','0% 100%'],'虚ろな騎士':['300% 200%','50% 100%'],'荷喰らい':['300% 100%','100% 50%']};
function sheetPos([x,y],cols=4,rows=3){return `${x/(cols-1)*100}% ${y/(rows-1)*100}%`}
function itemArtStyle(id){return `background-position:${sheetPos(ITEM_ART[id])}`}
function roleArtStyle(id){let p=ROLE_ART[id]||[0,0];return `--role-x:${p[0]/3*100}%;--role-y:${p[1]/2*100}%`}
const SECRETS=[
 {id:'first_card',name:'最初の一手',hint:'カードを初めて使用する',reward:'秘密の記録を解禁'},
 {id:'blade_100',name:'百斬の記憶',hint:'欠けた剣を100回使用する',reward:'欠けた剣が恒久進化'},
 {id:'dagger_75',name:'千の手数',hint:'連撃の短剣を75回使用する',reward:'短剣が恒久進化'},
 {id:'spear_60',name:'天を穿つ',hint:'折畳み槍を60回使用する',reward:'槍が恒久進化'},
 {id:'first_win',name:'荷喰らいの沈黙',hint:'ランを初めて踏破する',reward:'初期最大HP+3'},
 {id:'three_wins',name:'熟練の荷造り師',hint:'3回踏破する',reward:'初期ゴールド+10'},
 {id:'rotator',name:'四次元の詰め方',hint:'アイテムを50回回転する',reward:'初期ゴールド+2'},
 {id:'merchant',name:'上得意',hint:'商品を5個購入する',reward:'初期ゴールド+5'},
 {id:'eventer',name:'好奇心は身を救う',hint:'イベントを10回経験する',reward:'初期最大HP+2'},
 {id:'organizer',name:'戦場の荷造り師',hint:'戦闘中整理を20回行う',reward:'初期最大HP+2'},
 {id:'perfect_weight',name:'一分の隙間もなく',hint:'24マスを完全に埋めて出発する',reward:'初期ゴールド+3'},
 {id:'collector',name:'持てるだけの記憶',hint:'一度に装備を10種類所有する',reward:'初期最大HP+1'},
 {id:'minimalist',name:'軽装踏破',hint:'装備2個以下でボスを倒す',reward:'初期ゴールド+7'},
 {id:'last_stand',name:'紙一重',hint:'HP1でボスを倒す',reward:'初期最大HP+3'},
 {id:'edge_master',name:'四辺の儀式',hint:'バックパックの四辺すべてに装備を触れさせる',reward:'初期最大HP+2'},
 {id:'whisper',name:'塔はこちらを見ている',hint:'タイトルに秘密がある',reward:'初期ゴールド+1'}
];
function loadMeta(){try{return JSON.parse(localStorage.getItem('packspire_meta_v1'))||{}}catch{return{}}}
let META=loadMeta();META.mastery=META.mastery||{};META.unlocked=META.unlocked||{};META.roles=Object.assign({warrior:true,guardian:true,scout:true,artificer:true},META.roles||{});META.stats=Object.assign({runs:0,wins:0,cards:0,rotations:0,shopBuys:0,events:0,organizes:0},META.stats||{});
function saveMeta(){try{localStorage.setItem('packspire_meta_v1',JSON.stringify(META))}catch{}}
function unlock(id){if(META.unlocked[id])return;META.unlocked[id]=Date.now();saveMeta();let s=SECRETS.find(x=>x.id===id);if(s)toast(`秘密発見「${s.name}」— ${s.reward}`)}
function isEvolved(id){return !!EVOLUTIONS[id]&&(META.mastery[id]||0)>=EVOLUTIONS[id].need}
function metaMaxHp(){return 42+(META.unlocked.first_win?3:0)+(META.unlocked.eventer?2:0)+(META.unlocked.organizer?2:0)+(META.unlocked.collector?1:0)+(META.unlocked.last_stand?3:0)+(META.unlocked.edge_master?2:0)}
function metaGold(){return 24+(META.unlocked.three_wins?10:0)+(META.unlocked.merchant?5:0)+(META.unlocked.perfect_weight?3:0)+(META.unlocked.minimalist?7:0)+(META.unlocked.whisper?1:0)+(META.unlocked.rotator?2:0)}
function checkMeta(){if(META.stats.cards>=1)unlock('first_card');if((META.mastery.sword||0)>=100)unlock('blade_100');if((META.mastery.dagger||0)>=75)unlock('dagger_75');if((META.mastery.spear||0)>=60)unlock('spear_60');if(META.stats.wins>=1)unlock('first_win');if(META.stats.wins>=3)unlock('three_wins');if(META.stats.rotations>=50)unlock('rotator');if(META.stats.shopBuys>=5)unlock('merchant');if(META.stats.events>=10)unlock('eventer');if(META.stats.organizes>=20)unlock('organizer');saveMeta()}
function unlockRole(id,reason){if(META.roles[id])return;META.roles[id]=true;saveMeta();toast(`隠し役職「${ROLES[id].name}」解禁 — ${reason}`)}
let state;
const $=s=>document.querySelector(s);
function reset(){Object.entries(ITEMS).forEach(([id,x])=>{if(x.baseName===undefined)x.baseName=x.name;x.name=isEvolved(id)?EVOLUTIONS[id].name:x.baseName});META.stats.runs++;saveMeta();let maxHp=metaMaxHp();state={floor:1,hp:maxHp,maxHp,gold:metaGold(),role:null,roleLevel:1,backpack:'standard',contracts:[],faction:FACTIONS[Math.floor(Math.random()*FACTIONS.length)],inventory:['sword','shield','ember','herb'],placed:{},durability:{},jammed:[],selected:null,selectedPlaced:null,rotations:{},drag:null,organizing:false,organizeUsed:false,organizesRun:0,enemy:null,targetPart:null,draw:[],discard:[],hand:[],energy:3,block:0,attackBuff:0,move:0,metaReturn:'roleScreen'};renderRoles();show('roleScreen');renderAll()}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$('#'+id).classList.remove('hidden')}
function renderAll(){
 $('#floor').textContent=state.floor;$('#playerHp').textContent=state.hp;$('#gold').textContent=state.gold;$('#roleName').textContent=state.role?`${ROLES[state.role].name} Lv.${state.roleLevel}`:'未選択';
 $('#inventory').innerHTML=state.inventory.map((id,i)=>{let x=ITEMS[id],placed=Object.values(state.placed).some(p=>p.index===i),shape=getShape(x,state.rotations[i]||0);return `<div class="inventory-item ${state.selected===i?'selected':''} ${placed?'placed':''}" data-i="${i}" draggable="${!placed}"><div class="item-icon art-icon" style="${itemArtStyle(id)}">${x.icon}</div><div class="item-info"><b>${x.name}</b><small>${x.desc}</small><small class="item-rule">${x.rule}</small></div><div>${shapeHtml(shape,x.type)}<div class="item-size">${x.shape.length}マス</div></div></div>`}).join('');
 document.querySelectorAll('.inventory-item').forEach(x=>{x.onclick=()=>{let i=+x.dataset.i;if(Object.values(state.placed).some(p=>p.index===i))return;state.selected=state.selected===i?null:i;state.selectedPlaced=null;renderAll()};x.ondragstart=e=>{let i=+x.dataset.i;if(x.classList.contains('placed')){e.preventDefault();return}state.drag={kind:'inventory',index:i};state.selected=i;state.selectedPlaced=null;e.dataTransfer.effectAllowed='move'}});
 renderPack();renderDeck();$('#startBattle').innerHTML=state.organizing?'整理を確定 <span>↩</span>':'戦闘を開始 <span>→</span>';
}
function renderRoles(){let order=Object.keys(ROLES);$('#roleChoices').innerHTML=order.map(id=>{let r=ROLES[id],open=META.roles[id];return `<div class="role-card ${open?'':'locked'}" data-role="${id}">${open?`<div class="role-art" style="${roleArtStyle(id)}"></div>`:''}<span class="role-kind">${open?r.kind:'UNKNOWN'}</span><div class="role-icon ${open?'has-art':''}">${open?r.icon:'？'}</div><h3>${open?r.name:'未発見の役職'}</h3><p>${open?r.desc:(r.advanced?'転職によって解禁される':'特殊な条件で解禁される')}</p>${open?'<span class="role-level">選択可能</span>':''}</div>`}).join('');document.querySelectorAll('.role-card:not(.locked)').forEach(el=>el.onclick=()=>chooseRole(el.dataset.role))}
function chooseRole(id){state.role=id;let r=ROLES[id];state.maxHp+=r.hp||0;state.hp=state.maxHp;state.gold+=r.gold||0;renderExpedition();show('expeditionScreen');renderAll();toast(`${r.name}として遠征準備を始める`)}
function renderExpedition(){$('#backpackChoices').innerHTML=Object.entries(BACKPACKS).map(([id,p])=>`<div class="pack-choice ${state.backpack===id?'selected':''}" data-id="${id}"><b>${p.name}</b><small>${p.desc}</small></div>`).join('');document.querySelectorAll('.pack-choice').forEach(el=>el.onclick=()=>{state.backpack=el.dataset.id;renderExpedition()});$('#contractChoices').innerHTML=Object.entries(CONTRACTS).map(([id,c])=>`<div class="contract-choice ${state.contracts.includes(id)?'selected':''}" data-id="${id}"><b>${c.name}</b><small>${c.desc}</small></div>`).join('');document.querySelectorAll('.contract-choice').forEach(el=>el.onclick=()=>{let id=el.dataset.id;state.contracts=state.contracts.includes(id)?state.contracts.filter(x=>x!==id):[...state.contracts,id];renderExpedition()});$('#factionPreview').innerHTML=`今回の支配勢力：<b>${state.faction.name}</b><br>${state.faction.desc}`}
$('#beginExpedition').onclick=()=>{let hp=state.contracts.reduce((n,id)=>n+(CONTRACTS[id].hp||0),0);state.maxHp=Math.max(12,state.maxHp+hp);state.hp=Math.min(state.hp,state.maxHp);META.stats.contractPoints=(META.stats.contractPoints||0)+state.contracts.length;saveMeta();show('prepScreen');renderAll();toast(`${BACKPACKS[state.backpack].name}で遠征開始`)};
function renderPack(){
 $('#pack').innerHTML=Array.from({length:24},(_,i)=>`<div class="cell" data-cell="${i}"></div>`).join('');
 Object.entries(state.placed).forEach(([anchor,p])=>{let id=state.inventory[p.index],item=ITEMS[id],shape=getShape(item,p.rotation||0),dur=state.durability[p.index]??6;shape.forEach((pos,j)=>{let c=(+anchor)+pos[1]*6+pos[0],el=document.querySelector(`[data-cell="${c}"]`);el.innerHTML=`<div draggable="true" class="placed-item ${item.type} ${j===0?'art-piece':''} ${dur<=0?'broken':''} ${state.jammed.includes(p.index)?'jammed':''} ${state.selectedPlaced===anchor?'selected-piece':''}" style="${j===0?itemArtStyle(id):''}" data-anchor="${anchor}" data-dx="${pos[0]}" data-dy="${pos[1]}">${j===0?'':item.icon}<small>${j===0?item.name:''}</small>${j===0?`<small class="durability">耐久 ${dur}/6</small><span class="connector-arrow">${['↑','→','↓','←'][p.rotation||0]}</span>`:''}</div>`})});
 document.querySelectorAll('.cell').forEach(c=>{c.onclick=e=>{let piece=e.target.closest('.placed-item');if(piece){state.selectedPlaced=piece.dataset.anchor;state.selected=null;renderAll();return}placeAt(+c.dataset.cell)};c.ondragover=e=>{e.preventDefault();c.classList.add('drag-over')};c.ondragleave=()=>c.classList.remove('drag-over');c.ondrop=e=>{e.preventDefault();c.classList.remove('drag-over');dropAt(+c.dataset.cell)}});
 document.querySelectorAll('.placed-item').forEach(p=>{p.ondragstart=e=>{state.drag={kind:'placed',anchor:p.dataset.anchor,dx:+p.dataset.dx,dy:+p.dataset.dy};state.selectedPlaced=p.dataset.anchor;e.dataTransfer.effectAllowed='move'};p.oncontextmenu=e=>{e.preventDefault();let q=state.placed[p.dataset.anchor];if(q&&state.inventory[q.index]==='cursed_blade'){message('呪いが絡みつき、取り外せません');return}delete state.placed[p.dataset.anchor];state.selectedPlaced=null;message('アイテムを取り外しました');renderAll()}});
 $('#rotateItem').disabled=state.selected===null&&state.selectedPlaced===null;
}
function getShape(item,rotation=0){let pts=item.shape.map(([x,y])=>[x,y]);for(let n=0;n<rotation%4;n++)pts=pts.map(([x,y])=>[-y,x]);let minX=Math.min(...pts.map(p=>p[0])),minY=Math.min(...pts.map(p=>p[1]));return pts.map(([x,y])=>[x-minX,y-minY])}
function shapeHtml(shape,type){let w=Math.max(...shape.map(p=>p[0]))+1,h=Math.max(...shape.map(p=>p[1]))+1,set=new Set(shape.map(p=>p.join(','))),cells='';for(let y=0;y<h;y++)for(let x=0;x<w;x++)cells+=`<i class="shape-pixel ${set.has(x+','+y)?'on '+type:''}"></i>`;return `<div class="shape-preview" title="${w}×${h} / ${shape.length}マス" style="grid-template-columns:repeat(${w},9px)">${cells}</div>`}
function canPlace(cell,index,rotation,ignoreAnchor=null){let item=ITEMS[state.inventory[index]],shape=getShape(item,rotation),x=cell%6,y=Math.floor(cell/6),occupied=new Set();Object.entries(state.placed).forEach(([a,p])=>{if(a===String(ignoreAnchor))return;getShape(ITEMS[state.inventory[p.index]],p.rotation||0).forEach(o=>occupied.add(+a+o[1]*6+o[0]))});let cells=shape.map(o=>[x+o[0],y+o[1]]);return !cells.some(([a,b])=>a<0||b<0||a>5||b>3||occupied.has(b*6+a))}
function placeAt(cell){if(state.selected===null)return;let rotation=state.rotations[state.selected]||0;if(!canPlace(cell,state.selected,rotation)){message('そこには入りません');return}state.placed[cell]={index:state.selected,rotation};state.durability[state.selected]??=6;state.selected=null;state.selectedPlaced=String(cell);message('配置しました');renderAll()}
function dropAt(cell){if(!state.drag)return;if(state.drag.kind==='inventory'){state.selected=state.drag.index;placeAt(cell)}else{let old=state.drag.anchor,p=state.placed[old],anchor=cell-state.drag.dy*6-state.drag.dx;if(p&&anchor>=0&&canPlace(anchor,p.index,p.rotation||0,old)){delete state.placed[old];state.placed[anchor]=p;state.selectedPlaced=String(anchor);message('移動しました');renderAll()}else message('そこには移動できません')}state.drag=null}
function message(text){$('#packMessage').textContent=text}
function recordRotation(){META.stats.rotations++;checkMeta()}
$('#rotateItem').onclick=()=>{if(state.selected!==null){state.rotations[state.selected]=((state.rotations[state.selected]||0)+1)%4;recordRotation();message('配置前のアイテムを回転しました');renderAll();return}if(state.selectedPlaced!==null){let a=state.selectedPlaced,p=state.placed[a],next=((p.rotation||0)+1)%4;if(canPlace(+a,p.index,next,a)){p.rotation=next;recordRotation();message('アイテムを回転しました');renderAll()}else message('この位置では回転できません')}};
function itemCells(anchor,p){return getShape(ITEMS[state.inventory[p.index]],p.rotation||0).map(([x,y])=>({x:(+anchor)%6+x,y:Math.floor((+anchor)/6)+y}))}
function areAdjacent(a,pa,b,pb){return itemCells(a,pa).some(c=>itemCells(b,pb).some(d=>Math.abs(c.x-d.x)+Math.abs(c.y-d.y)===1))}
function deckData(){
 let cards=[],synergy=[],activeAnchors=new Set(),entries=Object.entries(state.placed);
 entries.forEach(([a,p])=>{let sourceId=state.inventory[p.index],item=ITEMS[sourceId];item.cards.forEach(id=>cards.push({...CARDS[id],id,source:item.name,sourceId,sourceAnchor:a}))});
 const own=(a)=>cards.filter(c=>c.sourceAnchor===a), activate=(a,text)=>{activeAnchors.add(a);synergy.push({active:true,text})}, inactive=(item)=>synergy.push({active:false,text:`${item.icon} ${item.rule}`});
 entries.forEach(([a,p])=>{
  let item=ITEMS[state.inventory[p.index]],neighbors=entries.filter(([b,q])=>b!==a&&areAdjacent(a,p,b,q)),active=false;
  if(state.inventory[p.index]==='sword'&&neighbors.some(([,q])=>state.inventory[q.index]==='shield')){own(a).forEach(c=>c.damage+=1);activate(a,'⚔ 剣 × 盾：斬撃 +1');active=true}
  if(state.inventory[p.index]==='shield'&&neighbors.some(([,q])=>ITEMS[state.inventory[q.index]].type==='weapon')){own(a).forEach(c=>c.block+=2);activate(a,'⬟ 盾 × 武器：防御 +2');active=true}
  if(state.inventory[p.index]==='ember'){let weapons=neighbors.filter(([,q])=>ITEMS[state.inventory[q.index]].type==='weapon');weapons.forEach(([b])=>{own(b).forEach(c=>{if(c.damage)c.damage+=2});activeAnchors.add(b)});if(weapons.length){activate(a,`✦ 熾火：隣接武器 ${weapons.length}個を強化`);active=true}}
  if(state.inventory[p.index]==='herb'&&itemCells(a,p).some(c=>c.y===0)){own(a).forEach(c=>c.heal+=3);activate(a,'❧ 取り出し口：回復 +3');active=true}
  if(state.inventory[p.index]==='dagger'&&neighbors.some(([,q])=>ITEMS[state.inventory[q.index]].type==='weapon')){own(a).forEach(c=>c.damage+=2);activate(a,'† 武器連携：刺突 +2');active=true}
  if(state.inventory[p.index]==='plate'&&itemCells(a,p).some(c=>c.y===3)){own(a).forEach(c=>c.block+=5);activate(a,'▣ 重心安定：防御 +5');active=true}
  if(state.inventory[p.index]==='crystal'){if(neighbors.length){neighbors.forEach(([b])=>{own(b).forEach(c=>c.cost=Math.max(0,c.cost-1));activeAnchors.add(b)});activate(a,`◇ 共鳴：隣接装備 ${neighbors.length}個を軽量化`);active=true}}
  if(state.inventory[p.index]==='bomb'&&itemCells(a,p).some(c=>c.x===5)){own(a).forEach(c=>c.damage+=5);activate(a,'● 即応配置：爆薬 +5');active=true}
  if(state.inventory[p.index]==='spear'&&itemCells(a,p).some(c=>c.y===0)&&getShape(item,p.rotation||0).every(c=>c.x===0)){own(a).forEach(c=>c.damage+=6);activate(a,'↟ 縦貫通：貫通突き +6');active=true}
  if(state.inventory[p.index]==='buckler'&&neighbors.some(([,q])=>ITEMS[state.inventory[q.index]].type==='rune')){own(a).forEach(c=>c.block+=3);activate(a,'◉ 魔力受け：防御 +3');active=true}
  if(state.inventory[p.index]==='flask'&&neighbors.some(([,q])=>state.inventory[q.index]==='bomb')){own(a).forEach(c=>c.damage+=4);activate(a,'⚗ 爆薬調合：酸液 +4');active=true}
  if(state.inventory[p.index]==='charm'&&itemCells(a,p).some(c=>c.x===0)){own(a).forEach(c=>{if(c.block)c.block+=3;c.cost=0});activate(a,'☘ 風の通り道：コスト0・防御+3');active=true}
  if(!active)inactive(item);
 });
 entries.forEach(([a,p])=>{let id=state.inventory[p.index];if(!isEvolved(id))return;if(id==='sword')own(a).forEach(c=>{if(c.damage)c.damage+=3});if(id==='dagger')own(a).forEach(c=>{if(c.damage)c.damage+=2});if(id==='spear')own(a).forEach(c=>c.cost=Math.max(0,c.cost-1));activate(a,`★ ${EVOLUTIONS[id].name}：${EVOLUTIONS[id].bonus}`)});
 const find=id=>entries.find(([,p])=>state.inventory[p.index]===id), fuse=(a,b,card,name)=>{let x=find(a),y=find(b);if(x&&y&&areAdjacent(x[0],x[1],y[0],y[1])){cards.push({...CARDS[card],id:card,source:name,sourceId:a,sourceAnchor:x[0]});synergy.push({active:true,text:`合成発動：${name}`});activeAnchors.add(x[0]);activeAnchors.add(y[0])}};
 fuse('sword','ember','inferno','焔断ち');fuse('shield','crystal','echoWall','反響障壁');fuse('bomb','flask','starBomb','星喰い爆薬');
 let topWeapons=entries.filter(([a,p])=>ITEMS[state.inventory[p.index]].type==='weapon'&&itemCells(a,p).some(c=>c.y===0)).length,edgeArmor=entries.filter(([a,p])=>ITEMS[state.inventory[p.index]].type==='armor'&&itemCells(a,p).some(c=>c.x===0||c.x===5)).length;
 if(entries.length){cards.push({...CARDS.geometry,id:'geometry',source:'バックパック陣形',sourceId:'formation',damage:topWeapons*2,block:edgeArmor*2,text:`上段武器×${topWeapons}で${topWeapons*2}ダメージ、端の防具×${edgeArmor}で${edgeArmor*2}ブロック。`})}
 entries.forEach(([a,p])=>{let id=state.inventory[p.index],dur=state.durability[p.index]??6;if(dur<=0)own(a).forEach(c=>{if(c.damage)c.damage=Math.ceil(c.damage/2);if(c.block)c.block=Math.ceil(c.block/2)});if(state.jammed.includes(p.index))own(a).forEach(c=>c.cost+=1);if(id==='cursed_blade'){entries.filter(([b,q])=>b!==a&&areAdjacent(a,p,b,q)).forEach(([b])=>own(b).forEach(c=>c.cost+=1))}});
 entries.filter(([,p])=>ITEMS[state.inventory[p.index]].type==='rune').forEach(([a,p])=>{let cell=itemCells(a,p)[0],dir=[[0,-1],[1,0],[0,1],[-1,0]][p.rotation||0],tx=cell.x+dir[0],ty=cell.y+dir[1],target=entries.find(([b,q])=>itemCells(b,q).some(c=>c.x===tx&&c.y===ty));if(target){own(target[0]).forEach(c=>{if(c.damage)c.damage+=2;if(c.block)c.block+=2});activate(a,'接続方向一致：対象カード+2')}});
 let bag=BACKPACKS[state.backpack];cards.forEach(c=>{let sourceEntry=entries.find(([,p])=>state.inventory[p.index]===c.sourceId);if(bag.rune&&ITEMS[c.sourceId]?.type==='rune'){if(c.damage)c.damage+=bag.rune;if(c.block)c.block+=bag.rune}if(bag.bottom&&sourceEntry&&itemCells(sourceEntry[0],sourceEntry[1]).some(x=>x.y===3)){if(c.damage)c.damage+=bag.bottom;if(c.block)c.block+=bag.bottom}});
 applyRoleBonuses(cards);
 cards.forEach(c=>{if(c.damage)c.text=c.text.replace(/\d+ダメージ/,c.damage+'ダメージ');if(c.block)c.text=c.text.replace(/\d+ブロック/,c.block+'ブロック');if(c.heal)c.text=c.text.replace(/HPを\d+回復/,`HPを${c.heal}回復`)});
 return{cards,synergy,activeAnchors}
}
function applyRoleBonuses(cards){if(!state.role)return;let role=state.role,lvl=Math.max(0,state.roleLevel-1),weapon=c=>ITEMS[c.sourceId]?.type==='weapon',armor=c=>ITEMS[c.sourceId]?.type==='armor',supply=c=>ITEMS[c.sourceId]?.type==='supply',rune=c=>ITEMS[c.sourceId]?.type==='rune';cards.forEach(c=>{
 if(role==='warrior'&&weapon(c)&&c.damage)c.damage+=1+lvl;
 if(role==='guardian'&&c.block)c.block+=2+lvl;
 if(role==='scout'&&['dagger','spear'].includes(c.sourceId)&&c.damage)c.damage+=2+lvl;
 if(role==='artificer'&&supply(c)){if(c.damage)c.damage+=2+lvl;if(c.block)c.block+=2+lvl;if(c.heal)c.heal+=2+lvl}
 if(role==='blade_master'&&['sword','dagger'].includes(c.sourceId)&&c.damage)c.damage+=4+lvl;
 if(role==='bulwark'&&c.block)c.block+=5+lvl;
 if(role==='hunter'&&['dagger','spear'].includes(c.sourceId)&&c.damage)c.damage+=4+lvl;
 if(role==='grand_artificer'&&supply(c)){if(c.damage)c.damage+=5+lvl;if(c.block)c.block+=5+lvl;if(c.heal)c.heal+=5+lvl}
 if(role==='arsenal_lord'&&weapon(c)&&c.damage)c.damage+=3+lvl;
 if(role==='pack_saint'){if(c.block)c.block+=4+lvl;if(c.heal)c.heal+=3+lvl}
 if(role==='rune_weaver'&&rune(c))c.cost=0;
 if(role==='grid_dancer'&&c.cost===0){if(c.damage)c.damage+=3+lvl;if(c.block)c.block+=3+lvl}
 })}
function renderDeck(){let d=deckData();$('#deckCount').textContent=d.cards.length;$('#deckPreview').innerHTML=d.cards.map(c=>`<div class="mini-card ${c.type}"><span>${c.name}</span><b>${c.cost} ◈</b></div>`).join('')||'<p class="hint">装備からカードが生成されます</p>';$('#synergies').innerHTML=d.synergy.map(s=>`<div class="synergy-line ${s.active?'':'inactive'}">${s.active?'LINK! ':'○ '}${s.text}</div>`).join('');document.querySelectorAll('.placed-item').forEach(el=>el.classList.toggle('active-link',d.activeAnchors.has(el.dataset.anchor)))}
$('#clearPack').onclick=()=>{state.placed=Object.fromEntries(Object.entries(state.placed).filter(([,p])=>state.inventory[p.index]==='cursed_blade'));state.selected=null;state.selectedPlaced=null;message(Object.keys(state.placed).length?'呪い装備だけは外せません':'すべて取り外しました');renderAll()};
$('#startBattle').onclick=()=>{let d=deckData(),cursed=state.inventory.map((id,i)=>id==='cursed_blade'?i:-1).filter(i=>i>=0);if(cursed.some(i=>!Object.values(state.placed).some(p=>p.index===i))){message('呪い装備が出発を拒んでいます。必ず配置してください');return}if(d.cards.length<4){message('最低4枚のカードが必要です');return}let cells=Object.entries(state.placed).flatMap(([a,p])=>itemCells(a,p));if(new Set(cells.map(c=>`${c.x},${c.y}`)).size===24)unlock('perfect_weight');if(cells.some(c=>c.x===0)&&cells.some(c=>c.x===5)&&cells.some(c=>c.y===0)&&cells.some(c=>c.y===3))unlock('edge_master');checkRoleUnlocks();if(state.organizing){finishOrganize(d.cards);return}startBattle(d.cards)};
function startBattle(cards){show('battleScreen');let pool=ENEMIES.filter(e=>e.floor===state.floor),base=pool[Math.floor(Math.random()*pool.length)],bonusHp=state.faction.id==='spore'?5:0,contractDamage=state.contracts.reduce((n,id)=>n+(CONTRACTS[id].enemyDamage||0),0);state.enemy={...base,moves:base.moves.map(m=>({...m,damage:m.damage+contractDamage,armor:(m.armor||0)+(state.faction.id==='iron'?3:0)})),hp:base.hp+bonusHp,maxHp:base.hp+bonusHp,block:0};if(base.boss)state.enemy.parts=[{id:'jaw',name:'貪欲の顎',hp:18,maxHp:18},{id:'cargo',name:'背の宝箱',hp:15,maxHp:15},{id:'core',name:'呪いの核',hp:20,maxHp:20}];state.targetPart=null;state.jammed=[];state.draw=shuffle(cards.map((c,i)=>({...c,uid:Date.now()+i})));state.discard=[];state.hand=[];state.energy=3;state.block=0;state.move=0;state.organizeUsed=false;draw(5);toast(`${state.enemy.name}が現れた`);renderBattle()}
function finishOrganize(cards){state.organizing=false;state.organizeUsed=true;state.hand=[];state.discard=[];state.draw=shuffle(cards.map((c,i)=>({...c,uid:Date.now()+i})));draw(5);show('battleScreen');toast('荷物を組み替え、デッキを再構築した');renderBattle()}
function shuffle(a){return a.sort(()=>Math.random()-.5)}
function draw(n){while(n--){if(!state.draw.length){state.draw=shuffle(state.discard);state.discard=[]}if(state.draw.length)state.hand.push(state.draw.pop())}}
function renderBattle(){let e=state.enemy,move=e.moves[state.move%e.moves.length],ea=ENEMY_ART[e.name]||ENEMY_ART['鉄殻の番兵'];$('#battleScreen').classList.remove('dungeon-floor-1','dungeon-floor-2','dungeon-floor-3');$('#battleScreen').classList.add('battle-screen-art',`dungeon-floor-${state.floor}`);$('#playerPortrait').setAttribute('style',roleArtStyle(state.role));$('#enemyPortrait').style.backgroundSize=ea[0];$('#enemyPortrait').style.backgroundPosition=ea[1];$('#battlePlayerHp').textContent=state.hp;$('#playerBlock').textContent=state.block;$('#playerBar').style.width=state.hp/state.maxHp*100+'%';$('#enemyName').textContent=e.name;$('#enemyType').textContent=`FLOOR ${state.floor}${e.boss?' — BOSS':''} / ${state.faction.name}`;$('#enemyHp').textContent=Math.max(0,e.hp);$('#enemyMaxHp').textContent=e.maxHp;$('#enemyBar').style.width=Math.max(0,e.hp/e.maxHp*100)+'%';let hidden=state.contracts.includes('blind')&&state.move%2===1;$('#intent').textContent=hidden?'次の行動: ？？？':('次の行動: '+move.label+(e.block?`　◆${e.block}`:''));$('#bossParts').innerHTML=e.parts?e.parts.map(p=>`<button class="boss-part ${state.targetPart===p.id?'selected':''} ${p.hp<=0?'destroyed':''}" data-id="${p.id}" ${p.hp<=0?'disabled':''}>${p.name} ${Math.max(0,p.hp)}/${p.maxHp}</button>`).join(''):'';document.querySelectorAll('.boss-part').forEach(b=>b.onclick=()=>{state.targetPart=state.targetPart===b.dataset.id?null:b.dataset.id;renderBattle()});$('#energy').textContent=state.energy;$('#drawCount').textContent=state.draw.length;$('#discardCount').textContent=state.discard.length;$('#organizePack').disabled=state.organizeUsed||state.energy<1||state.contracts.includes('no_sort');$('#hand').innerHTML=state.hand.map((c,i)=>`<div class="card ${c.type} ${c.cost>state.energy?'disabled':''}" data-i="${i}"><span class="cost">${c.cost}</span><b>${c.name}</b><p>${c.text}</p><em>${c.source}</em></div>`).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>playCard(+c.dataset.i))}
function registerUse(id){META.stats.cards++;if(id){META.mastery[id]=(META.mastery[id]||0)+1;if(isEvolved(id)&&EVOLUTIONS[id])ITEMS[id].name=EVOLUTIONS[id].name}checkMeta()}
function playCard(i){let c=state.hand[i];if(!c||c.cost>state.energy)return;state.energy-=c.cost;registerUse(c.sourceId);let src=Object.values(state.placed).find(p=>state.inventory[p.index]===c.sourceId),justBroke=false;if(src&&c.sourceId!=='formation'){state.durability[src.index]=Math.max(0,(state.durability[src.index]??6)-1);justBroke=state.durability[src.index]===0}let msg=c.name+'：';if(c.damage){let raw=c.damage+state.attackBuff,absorbed=Math.min(raw,state.enemy.block||0),dmg=raw-absorbed;state.enemy.block=Math.max(0,(state.enemy.block||0)-raw);state.attackBuff=0;if(state.targetPart&&state.enemy.parts){let part=state.enemy.parts.find(p=>p.id===state.targetPart&&p.hp>0);if(part){part.hp-=dmg;msg+=`${part.name}へ${dmg}ダメージ `;if(part.hp<=0){msg+='【部位破壊】 ';if(part.id==='cargo')state.gold+=25;if(part.id==='jaw')state.enemy.moves.forEach(m=>m.damage=Math.max(0,m.damage-3));if(part.id==='core'){state.enemy.maxHp-=10;state.enemy.hp=Math.min(state.enemy.hp,state.enemy.maxHp)}}state.targetPart=null}else state.enemy.hp-=dmg}else{state.enemy.hp-=dmg;msg+=`${dmg}ダメージ `}pulse('.enemy-card','hit')}if(c.block){state.block+=c.block;msg+=`${c.block}防御 `}if(c.heal){let old=state.hp;state.hp=Math.min(state.maxHp,state.hp+c.heal);msg+=`${state.hp-old}回復 `}if(c.selfDamage){state.hp=Math.max(1,state.hp-c.selfDamage);msg+=`反動${c.selfDamage} `}if(c.buff){state.attackBuff+=c.buff;msg+='次の攻撃強化 '}if(c.energy){state.energy+=c.energy;msg+=`エネルギー+${c.energy} `}if(justBroke){[...state.hand,...state.draw,...state.discard].filter(x=>x.sourceId===c.sourceId).forEach(x=>{if(x.damage)x.damage=Math.ceil(x.damage/2);if(x.block)x.block=Math.ceil(x.block/2)});msg+='【装備破損】 '}state.hand.splice(i,1);if(!c.exhaust)state.discard.push(c);$('#battleLog').textContent=msg;if(state.enemy.hp<=0){winBattle();return}renderBattle()}
$('#organizePack').onclick=()=>{if(state.organizeUsed||state.energy<1||state.contracts.includes('no_sort'))return;state.energy--;state.organizing=true;state.organizesRun++;META.stats.organizes++;checkMeta();show('prepScreen');renderAll();message('戦闘中整理：配置を変更して「整理を確定」してください')};
function adjustJammedCost(delta){let ids=state.jammed.map(i=>state.inventory[i]);[...state.hand,...state.draw,...state.discard].forEach(c=>{if(ids.includes(c.sourceId))c.cost=Math.max(0,c.cost+delta)})}
$('#endTurn').onclick=()=>{let move=state.enemy.moves[state.move%state.enemy.moves.length],hit=Math.max(0,move.damage-state.block);state.hp-=hit;state.block=0;state.enemy.block=move.armor||0;state.discard.push(...state.hand);state.hand=[];state.move++;state.organizeUsed=false;adjustJammedCost(-1);let equipped=Object.values(state.placed);state.jammed=[];if(equipped.length&&Math.random()<.65){let victim=equipped[Math.floor(Math.random()*equipped.length)];state.jammed=[victim.index]}if(state.enemy.parts?.some(p=>p.id==='core'&&p.hp>0))state.enemy.hp=Math.min(state.enemy.maxHp,state.enemy.hp+3);pulse('.player-card','hit');if(state.hp<=0){endGame(false);return}state.energy=3;draw(5);adjustJammedCost(1);$('#battleLog').textContent=`${state.enemy.name}の攻撃。${hit}ダメージ。${state.jammed.length?'装備1個が妨害された。':''}`;renderBattle()};
function winBattle(){let mult=state.contracts.reduce((n,id)=>n*(CONTRACTS[id].gold||1),1)*(state.faction.id==='void'?1.25:1);state.gold+=Math.round((12+state.floor*3)*mult);state.hp=Math.min(state.maxHp,state.hp+3+(state.faction.id==='spore'?2:0));state.roleLevel=Math.min(5,state.roleLevel+1);if(state.floor===3){endGame(true);return}show('rewardScreen');let pool=['dagger','plate','crystal','bomb','spear','buckler','flask','charm',...(state.faction.id==='void'?['cursed_blade']:[])].filter(x=>!state.inventory.includes(x));if(state.faction.id==='iron')pool.push('plate','buckler');let opts=[...new Set(shuffle(pool))].slice(0,3);$('#rewards').innerHTML=opts.map(id=>{let x=ITEMS[id];return `<div class="reward" data-id="${id}"><div class="big-icon art-reward" style="--item-x:${ITEM_ART[id][0]/3*100}%;--item-y:${ITEM_ART[id][1]/2*100}%"></div><h3>${x.name}</h3><p>${x.desc}<br>${x.rule}<br>${x.shape.length}マス</p></div>`}).join('');document.querySelectorAll('.reward').forEach(r=>r.onclick=()=>{state.inventory.push(r.dataset.id);checkCollector();state.floor++;if(BACKPACKS[state.backpack].living)Object.entries(state.placed).forEach(([a,p])=>{let next=Math.floor(Math.random()*4);if(canPlace(+a,p.index,next,a))p.rotation=next});state.selectedPlaced=null;showMap()})}
const ROUTES={event:{icon:'?',name:'未知の物音',desc:'利益か災いか'},shop:{icon:'♜',name:'行商人',desc:'ゴールドで装備を購入'},rest:{icon:'♨',name:'野営地',desc:'HPを回復'},scavenge:{icon:'✧',name:'崩れた保管庫',desc:'HPを賭けて物資を探す'},guild:{icon:'♝',name:'転職の祭壇',desc:'Lv.3で上級職へ転職'}};
function showMap(){show('mapScreen');let types=state.floor===3?['guild',...shuffle(['event','shop','rest','scavenge']).slice(0,2)]:shuffle(['event','shop','rest','scavenge','guild']).slice(0,3);$('#mapNodes').innerHTML=types.map(t=>{let r=ROUTES[t];return `<div class="map-node" data-type="${t}"><div class="node-icon">${r.icon}</div><b>${r.name}</b><small>${r.desc}</small></div>`}).join('');document.querySelectorAll('.map-node').forEach(n=>n.onclick=()=>enterRoute(n.dataset.type))}
function enterRoute(type){if(type==='guild'){openGuild();return}if(type==='shop'){openShop();return}if(type==='rest'){let heal=Math.min(12,state.maxHp-state.hp);state.hp+=heal;Object.keys(state.durability).forEach(i=>state.durability[i]=6);toast(`${heal} HP回復し、全装備を修理した`);continueRun();return}if(type==='scavenge'){state.hp=Math.max(1,state.hp-6);state.gold+=24;toast('6 HPを失い、24Gを発見した');continueRun();return}openEvent()}
function openGuild(){show('eventScreen');$('#eventIcon').textContent='♝';$('#eventTitle').textContent='転職の祭壇';let next=PROMOTIONS[state.role];if(next&&state.roleLevel>=3){$('#eventText').textContent=`${ROLES[state.role].name} Lv.${state.roleLevel}の経験が、新たな道を開いている。`;$('#eventChoices').innerHTML=`<button class="event-choice" id="promoteRole">${ROLES[next].icon} ${ROLES[next].name}へ転職</button><button class="event-choice" id="keepRole">現在の役職を極める</button>`;$('#promoteRole').onclick=()=>{META.roles[next]=true;saveMeta();state.role=next;let r=ROLES[next];state.maxHp+=r.hp||0;state.hp=Math.min(state.maxHp,state.hp+(r.hp||0));state.gold+=r.gold||0;toast(`上級職「${r.name}」を恒久解禁した`);continueRun()};$('#keepRole').onclick=()=>{state.roleLevel++;toast('役職レベルが1上がった');continueRun()}}else{$('#eventText').textContent=next?'まだ経験が足りない。Lv.3で上級職への道が開く。':'この役職には定められた上級職がない。祭壇は能力を磨いた。';$('#eventChoices').innerHTML='<button class="event-choice" id="trainRole">修練して先へ進む</button>';$('#trainRole').onclick=()=>{state.roleLevel++;toast('役職レベルが1上がった');continueRun()}}}
const EVENTS=[
 {icon:'☽',title:'囁く井戸',text:'底から「重いものを寄越せ」と声が響く。',choices:[{label:'10Gを投げる',effect:()=>{if(state.gold<10)return false;state.gold-=10;state.maxHp+=5;state.hp+=5;toast('最大HP +5') }},{label:'立ち去る',effect:()=>toast('何も起こらなかった')}]},
 {icon:'⚙',title:'壊れた昇降機',text:'危険な近道と、遠回りの階段がある。',choices:[{label:'昇降機を使う（50%）',effect:()=>{if(Math.random()<.5){state.gold+=30;toast('30Gを発見した')}else{state.hp=Math.max(1,state.hp-9);toast('落下して9ダメージ')}}},{label:'階段を使う（HP+4）',effect:()=>{state.hp=Math.min(state.maxHp,state.hp+4);toast('慎重に進み4HP回復')}}]},
 {icon:'✦',title:'荷造り師の亡霊',text:'亡霊は装備の傷を見つめ、手を差し出した。',choices:[{label:'8Gで全装備を修理',effect:()=>{if(state.gold<8)return false;state.gold-=8;Object.keys(state.durability).forEach(i=>state.durability[i]=6);toast('全装備の耐久度が回復した')}},{label:'断る',effect:()=>toast('亡霊は消えた')}]},
 {icon:'♞',title:'ライバル探索者',text:'同じ戦利品を狙う探索者が道を塞いだ。',choices:[{label:'決闘する（HP-5、35G）',effect:()=>{state.hp=Math.max(1,state.hp-5);state.gold+=35;toast('ライバルを退けた')}},{label:'物資を交換する（15G）',effect:()=>{if(state.gold<15)return false;state.gold-=15;Object.keys(state.durability).forEach(i=>state.durability[i]=6);toast('装備を修理してもらった')}}]}];
function openEvent(){show('eventScreen');let e=EVENTS[Math.floor(Math.random()*EVENTS.length)];$('#eventIcon').textContent=e.icon;$('#eventTitle').textContent=e.title;$('#eventText').textContent=e.text;$('#eventChoices').innerHTML=e.choices.map((c,i)=>`<button class="event-choice" data-i="${i}">${c.label}</button>`).join('');document.querySelectorAll('.event-choice').forEach(b=>b.onclick=()=>{let ok=e.choices[+b.dataset.i].effect();if(ok===false){toast('ゴールドが足りない');return}META.stats.events++;checkMeta();continueRun()})}
function checkCollector(){if(state.inventory.length>=10)unlock('collector');if(['sword','dagger','spear'].every(id=>state.inventory.includes(id)))unlockRole('arsenal_lord','剣・短剣・槍を一度に集めた')}
function checkRoleUnlocks(){let entries=Object.entries(state.placed),ids=entries.map(([,p])=>state.inventory[p.index]);if(['shield','plate','buckler'].every(id=>ids.includes(id)))unlockRole('pack_saint','三種の防具を同時に配置した');let runes=entries.filter(([,p])=>['ember','crystal'].includes(state.inventory[p.index]));if(runes.length===2){let corners=[[0,0],[5,3],[5,0],[0,3]],hits=runes.map(([a,p])=>itemCells(a,p).filter(c=>corners.some(k=>k[0]===c.x&&k[1]===c.y)));if(hits[0].some(a=>hits[1].some(b=>a.x+b.x===5&&a.y+b.y===3)))unlockRole('rune_weaver','二つのルーンで対角線を結んだ')}let byAnchor=new Map(entries.map(([a,p])=>[+a,ITEMS[state.inventory[p.index]].type]));for(let y=0;y<3;y++)for(let x=0;x<5;x++){let q=y*6+x,square=[q,q+1,q+6,q+7];if(square.every(n=>byAnchor.has(n))&&new Set(square.map(n=>byAnchor.get(n))).size===4)unlockRole('grid_dancer','異種装備の基点で2×2の正方形を作った')}}
function openShop(){show('shopScreen');let ids=shuffle(Object.keys(ITEMS).filter(id=>!state.inventory.includes(id)&&id!=='cursed_blade')).slice(0,3),discount=(BACKPACKS[state.backpack].shop||1)*(state.faction.id==='guild'?.85:1);$('#shopItems').innerHTML=ids.map(id=>{let x=ITEMS[id],price=Math.round((14+x.shape.length*4)*discount);return `<div class="reward shop-item" data-id="${id}" data-price="${price}"><div class="big-icon art-reward" style="--item-x:${ITEM_ART[id][0]/3*100}%;--item-y:${ITEM_ART[id][1]/2*100}%"></div><h3>${x.name}</h3><p>${x.rule}<br>${x.shape.length}マス</p><b>${price}G</b></div>`}).join('')||'<p>売り切れだ。</p>';document.querySelectorAll('.shop-item').forEach(el=>el.onclick=()=>{let price=+el.dataset.price;if(state.gold<price){toast('ゴールドが足りない');return}state.gold-=price;state.inventory.push(el.dataset.id);META.stats.shopBuys++;checkMeta();checkCollector();el.remove();toast(`${ITEMS[el.dataset.id].name}を購入した`)});$('#leaveShop').onclick=continueRun}
function continueRun(){show('prepScreen');renderAll()}
function toast(text){let el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800)}
function pulse(selector,cls){let el=$(selector);el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls);setTimeout(()=>el.classList.remove(cls),300)}
function endGame(win){if(win){META.stats.wins++;if(Object.keys(state.placed).length<=2)unlock('minimalist');if(state.hp===1)unlock('last_stand');checkMeta()}saveMeta();show('gameOver');$('#endTitle').textContent=win?'踏破成功！':'探索終了';$('#endText').textContent=win?`荷喰らいを討伐し、${state.gold}Gを持ち帰った。記憶庫に新たな記録が刻まれた。`:`第${state.floor}階層で力尽きた。使用回数と発見した秘密は記憶庫に残る。`}
function renderMeta(){let found=SECRETS.filter(s=>META.unlocked[s.id]).length;$('#metaRuns').textContent=META.stats.runs;$('#metaWins').textContent=META.stats.wins;$('#secretCount').textContent=`${found} / ${SECRETS.length}`;$('#masteryList').innerHTML=Object.entries(EVOLUTIONS).map(([id,e])=>{let n=META.mastery[id]||0,done=n>=e.need;return `<div class="mastery-entry"><div class="mastery-head"><b class="${done?'evolved':''}">${done?'★ '+e.name:ITEMS[id].baseName||ITEMS[id].name}</b><span>${Math.min(n,e.need)} / ${e.need}</span></div><div class="mastery-bar"><i style="width:${Math.min(100,n/e.need*100)}%"></i></div><small>${done?e.bonus:'使用するたび記憶が蓄積される'}</small></div>`}).join('');$('#secretList').innerHTML=SECRETS.map(s=>{let open=META.unlocked[s.id];return `<div class="secret-entry ${open?'unlocked':'locked'}"><b>${open?'✦ '+s.name:'◆ ？？？？？？'}</b><small>${open?s.hint+' / '+s.reward:'条件も報酬も隠されている'}</small></div>`}).join('');$('#roleArchive').innerHTML=Object.entries(ROLES).filter(([id])=>META.roles[id]).map(([,r])=>`<span class="role-chip ${r.advanced?'advanced':''} ${r.hidden?'hidden-role':''}">${r.icon} ${r.name}</span>`).join('');$('#rumorList').innerHTML=RUMORS.map(([name,text,need])=>`<div class="rumor"><b>${META.stats.cards>=need?name:'？？？'}</b><br>${META.stats.cards>=need?text:`あと${need-META.stats.cards}回カードを使えば噂が聞こえる`}</div>`).join('')}
$('#openMeta').onclick=()=>{let current=document.querySelector('.screen:not(.hidden)');state.metaReturn=current?current.id:'prepScreen';renderMeta();show('metaScreen')};
$('#closeMeta').onclick=()=>show(state.metaReturn||'prepScreen');
let titleClicks=0;document.querySelector('h1').onclick=()=>{titleClicks++;if(titleClicks===7){unlock('whisper');document.querySelector('h1').textContent='PACK REMEMBERS';setTimeout(()=>document.querySelector('h1').innerHTML='PACK<span>SPIRE</span>',1400)}};
$('#restart').onclick=reset;
reset();
