using System.Linq;
using UnityEngine;
using UnityEngine.UIElements;

namespace Packspire {
public sealed partial class PackspireUiFoundation {
 void BuildExpedition(){
  var meta=game.UiMeta;int unlocked=Mathf.Clamp(meta.dungeonsUnlocked,1,GameCatalog.Dungeons.Length);if(string.IsNullOrEmpty(selectedDungeonId)||!GameCatalog.Dungeons.Take(unlocked).Any(x=>x.id==selectedDungeonId))selectedDungeonId=GameCatalog.Dungeons[0].id;
  var desk=TabletopDesk("ps-expedition-workspace");screenRoot.Add(desk);var tray=Container("ps-expedition-case");desk.Add(tray);var selected=GameCatalog.Dungeons.First(x=>x.id==selectedDungeonId);tray.Add(PackspireUiFactory.Title("遠征準備"));tray.Add(Atlas(game.UiDungeonArt,DungeonUv(selected.id),"ps-expedition-selected-art"));tray.Add(PackspireUiFactory.Title(selected.name));tray.Add(PackspireUiFactory.Body(selected.description));tray.Add(PackspireUiFactory.Body($"敵HP ×{selected.hpScale:0.00}　追加攻撃 {selected.damage}　報酬 ×{selected.goldScale:0.00}"));
  tray.Add(PackspireUiFactory.Title("使用する荷造り"));var loadouts=Container("ps-loadout-tabs");foreach(var loadout in meta.loadouts){var entry=loadout;var button=PackspireUiFactory.Button(entry.name,()=>{game.UiSelectLoadout(entry.id);BuildExpeditionAgain();});if(entry.id==meta.selectedLoadoutId)button.AddToClassList("ps-selected");loadouts.Add(button);}tray.Add(loadouts);var active=LoadoutSystem.Active(meta);tray.Add(PackspireUiFactory.Body($"{BackpackName(active.backpack)}　配置 {active.slots.Count}　カード {active.deck.Count}"));var launch=PackspireUiFactory.Button("この地図へ遠征する",()=>game.UiStartExpedition(selected.id));launch.AddToClassList("ps-primary-action");tray.Add(launch);
  var rack=new ScrollView();rack.AddToClassList("ps-map-roll-rack");desk.Add(rack);for(int i=0;i<GameCatalog.Dungeons.Length;i++){var dungeon=GameCatalog.Dungeons[i];bool available=i<unlocked;var roll=new Button(()=>{if(available){selectedDungeonId=dungeon.id;BuildExpeditionAgain();}});roll.AddToClassList("ps-map-roll");if(dungeon.id==selectedDungeonId)roll.AddToClassList("ps-selected");if(!available)roll.AddToClassList("ps-locked");roll.Add(Atlas(game.UiDungeonArt,DungeonUv(dungeon.id),"ps-map-roll-seal"));roll.Add(new Label(available?dungeon.name:"封印された地図"));rack.Add(roll);}desk.Add(TabletopBack());
 }
 void BuildExpeditionAgain(){screenRoot.Clear();BuildExpedition();}

 void BuildPacking(){
  var run=game.UiRun;if(run==null){game.UiNavigate(ScreenId.Hub);return;}if(!string.IsNullOrEmpty(selectedPackingUid)&&!run.inventory.Any(x=>x.uid==selectedPackingUid))selectedPackingUid="";
  var desk=TabletopDesk("ps-packing-workspace");screenRoot.Add(desk);var left=Container("ps-canvas-packing-mat ps-packing-page");var right=new ScrollView();right.AddToClassList("ps-equipment-tray");right.AddToClassList("ps-packing-detail-page");desk.Add(left);desk.Add(right);left.Add(PackspireUiFactory.Title("荷造り布"));
  var loadouts=Container("ps-loadout-tabs");foreach(var loadout in game.UiMeta.loadouts){var entry=loadout;var button=PackspireUiFactory.Button(entry.name,()=>{game.UiOpenPackingLoadout(entry.id);selectedPackingUid="";BuildPackingAgain();});if(entry.id==game.UiMeta.selectedLoadoutId)button.AddToClassList("ps-selected");loadouts.Add(button);}left.Add(loadouts);
  var bags=Container("ps-bag-tabs");foreach(var bag in GameCatalog.Backpacks){var entry=bag;var button=PackspireUiFactory.Button(entry.name,()=>{game.UiPackingSetBackpack(entry.id);BuildPackingAgain();});if(entry.id==run.backpack)button.AddToClassList("ps-selected");bags.Add(button);}left.Add(bags);
  var tools=Container("ps-packing-tools");tools.Add(PackspireUiFactory.Button("↻ 回転",()=>{packingRotation=(packingRotation+1)%4;BuildPackingAgain();}));tools.Add(PackspireUiFactory.Button("選択解除",()=>{selectedPackingUid="";packingRotation=0;BuildPackingAgain();}));var remove=PackspireUiFactory.Button("バッグから外す",()=>{game.UiPackingRemove(selectedPackingUid);BuildPackingAgain();});remove.SetEnabled(!string.IsNullOrEmpty(selectedPackingUid)&&run.placements.Any(x=>x.itemUid==selectedPackingUid));tools.Add(remove);left.Add(tools);
  var packingHint=PackspireUiFactory.Body("装備を選び、置きたいマスを押してください。薄い色は収納面の属性です。");packingHint.AddToClassList("ps-packing-hint");left.Add(packingHint);left.Add(BuildBackpackGrid(run));
  right.Add(PackspireUiFactory.Title("所持装備"));var inventory=Container("ps-packing-inventory");foreach(var item in run.inventory){var entry=item;bool placed=run.placements.Any(x=>x.itemUid==entry.uid);var tile=AtlasButton(game.UiEquipmentArt,ItemUv(entry.templateId),(placed?"● ":"")+GameCatalog.Items[entry.templateId].name,entry.uid==selectedPackingUid,()=>{selectedPackingUid=entry.uid;packingRotation=run.placements.FirstOrDefault(x=>x.itemUid==entry.uid)?.rotation??0;BuildPackingAgain();});inventory.Add(tile);}right.Add(inventory);
  var selected=run.inventory.FirstOrDefault(x=>x.uid==selectedPackingUid);
  if(selected!=null){
   var def=GameCatalog.Items[selected.templateId];
   string elements=string.Join("・",def.cells.Select((cell,i)=>ElementLabel(selected.colors!=null&&i<selected.colors.Count?selected.colors[i]:cell.element)));
   right.Add(PackspireUiFactory.Title(def.name));
   right.Add(PackspireUiFactory.Body(def.description+"\n属性　"+elements));
   if(!string.IsNullOrEmpty(def.linkRule))right.Add(PackspireUiFactory.Body("LINK　"+def.linkRule));
  }
  var build=BackpackSystem.Build(run);right.Add(PackspireUiFactory.Title($"戦闘へ持ち込むカード　{run.selectedCardSlots.Count}/{LoadoutSystem.EquipmentCardLimit}"));var cards=Container("ps-card-choice-list");foreach(var card in build.candidates){var entry=card;bool chosen=run.selectedCardSlots.Contains(entry.slotKey);var button=PackspireUiFactory.Card($"{(chosen?"●":"○")} {entry.name}　{entry.cost}EN",entry.text,()=>{game.UiPackingToggleCard(entry.slotKey);BuildPackingAgain();});if(chosen)button.AddToClassList("ps-selected");if(!chosen&&run.selectedCardSlots.Count>=LoadoutSystem.EquipmentCardLimit)button.SetEnabled(false);cards.Add(button);}right.Add(cards);
  right.Add(PackspireUiFactory.Title("発動中の効果"));right.Add(PackspireUiFactory.Body($"火 {build.colors[Element.Fire]}　水 {build.colors[Element.Water]}　風 {build.colors[Element.Wind]}　土 {build.colors[Element.Earth]}\n"+(build.links.Count==0?"LINKなし":string.Join("／",build.links))));
  var save=PackspireUiFactory.Button("この荷造りを保存",()=>game.UiPackingSave());save.AddToClassList("ps-primary-action");right.Add(save);if(game.UiPackingAtBase)desk.Add(TabletopBack());
 }
 VisualElement BuildBackpackGrid(RunState run){var grid=Container("ps-backpack-grid");for(int index=0;index<24;index++){int cellIndex=index;var occupant=PlacementAt(run,index);var cell=new Button(()=>{if(!string.IsNullOrEmpty(selectedPackingUid)){if(!game.UiPackingPlace(selectedPackingUid,cellIndex,packingRotation))ShowToast("その位置には配置できません");}else if(occupant!=null){selectedPackingUid=occupant.itemUid;packingRotation=occupant.rotation;}BuildPackingAgain();});cell.AddToClassList("ps-backpack-cell");cell.AddToClassList("ps-element-"+GameCatalog.Board[index].ToString().ToLowerInvariant());if(occupant!=null){var item=run.inventory.FirstOrDefault(x=>x.uid==occupant.itemUid);if(item!=null){cell.tooltip=GameCatalog.Items[item.templateId].name;cell.Add(Atlas(game.UiEquipmentArt,ItemUv(item.templateId),"ps-cell-item"));var element=CellElementAt(run,occupant,index);bool match=element.HasValue&&element.Value==GameCatalog.Board[index];cell.AddToClassList(match?"ps-cell-match":"ps-cell-mismatch");if(match){var mark=new Label("◆");mark.AddToClassList("ps-match-mark");cell.Add(mark);}if(item.uid==selectedPackingUid)cell.AddToClassList("ps-cell-selected");}}grid.Add(cell);}return grid;}
 Placement PlacementAt(RunState run,int index){int x=index%6,y=index/6;foreach(var placement in run.placements){var item=run.inventory.FirstOrDefault(i=>i.uid==placement.itemUid);if(item==null)continue;int ax=placement.anchor%6,ay=placement.anchor/6;if(BackpackSystem.Layout(GameCatalog.Items[item.templateId],placement.rotation,item).Any(c=>ax+c.pos.x==x&&ay+c.pos.y==y))return placement;}return null;}
 Element? CellElementAt(RunState run,Placement placement,int index){var item=run.inventory.FirstOrDefault(i=>i.uid==placement.itemUid);if(item==null)return null;int x=index%6,y=index/6,ax=placement.anchor%6,ay=placement.anchor/6;foreach(var cell in BackpackSystem.Layout(GameCatalog.Items[item.templateId],placement.rotation,item))if(ax+cell.pos.x==x&&ay+cell.pos.y==y)return cell.element;return null;}
 void BuildPackingAgain(){screenRoot.Clear();BuildPacking();}
}
}
