using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Packspire {
public partial class PackspireGame : MonoBehaviour {


 public static PackspireGame Instance { get; private set; }
 MetaSave meta; RunState run; DungeonMap map; BattleState battle; ScreenId screen; Vector2 scroll; string selectedUid="",message="",hubHover="",selectedRoleId="",selectedFactionId="",selectedDungeonId="",selectedCompendiumId=""; int selectedRotation,compendiumTab,packingDetailTab,selectedMapNodeId=-1,mapEventNodeId=-1,mapLoadoutTab; bool packingAtBase,illustratedStylesApplied,mapEventOverlay,mapLoadoutOverlay,developerPanel; GUIStyle title,header,body,button,card,hotspot,hubLabel,hubLabelHover,topChip,cellButton,navButton,navSelected,screenTitle,screenSubtitle,badge,centerBody,bookEntryStyle,bookEntryHoverStyle,bookEntrySelectedStyle; Texture2D factionArt,hubArt,characterArt,equipmentArt,roleArt,enemyArt,dungeonArt,menuBackdrop,panelTex,buttonTex,hoverTex,cellClearTex,navTex,navSelectedTex,badgeTex,homeTileTex,homeTileHoverTex,homePrimaryTex,homePrimaryHoverTex,uiActionNormal,uiActionHover,uiActionDanger,uiBackCard,uiNavNormal,uiNavSelected,uiTabCard,uiChipCard,minimalButtonTex,minimalHoverTex,infoChipTex,homeBarPrimary,homeBarSecondary,mapTerrain,mapRoad,bookSpread,bookClearTex,bookHoverTex,bookSelectedTex,bookChipTex,scrollMapUi,battleTableUi,backpackLeatherTex,backpackPocketTex,mapNodeCircleTex; Texture2D[] homeCardArt,navIconArt,combatCardFrames; Font uiFont,titleFont,gameFont;
 readonly Color bg=new(.09f,.12f,.095f),panel=new(.16f,.20f,.165f),gold=new(.94f,.75f,.35f),ink=new(.97f,.95f,.88f);
 ScreenId lastVisualScreen; bool visualScreenTracked;
 Texture2D bookButtonTex,bookButtonHoverTex,bookButtonSelectedTex,bookRuleTex,bookScrollTrackTex,bookScrollThumbTex,battleMeterTrackTex,battleHpTex,battleBlockTex,battleStatusBuffTex,battleStatusDebuffTex;
 public ScreenId UiScreen=>screen; public MetaSave UiMeta=>meta; public bool UiDeveloperPanelOpen=>developerPanel; public Texture2D UiHubArt=>hubArt; public Texture2D UiCharacterArt=>characterArt; public Texture2D UiEquipmentArt=>equipmentArt; public Texture2D UiRoleArt=>roleArt; public Texture2D UiEnemyArt=>enemyArt; public Texture2D UiDungeonArt=>dungeonArt; public Texture2D UiFactionArt=>factionArt; public Texture2D UiBookArt=>bookSpread;
 public RunState UiRun=>run; public string UiMessage=>message; public bool UiPackingAtBase=>packingAtBase;
 string rewardSelectionId="",shopSelectionId="";
 void Awake(){if(Instance!=null&&Instance!=this){Destroy(gameObject);return;}Instance=this;DontDestroyOnLoad(gameObject);meta=SaveSystem.Load();factionArt=Resources.Load<Texture2D>("Art/faction-hub-sheet");hubArt=Resources.Load<Texture2D>("Art/UI/hub-courtyard-v1");menuBackdrop=Resources.Load<Texture2D>("Art/UI/fantasy-menu-backdrop-v1");characterArt=Resources.Load<Texture2D>("Art/character-creator-sheet");equipmentArt=Resources.Load<Texture2D>("Art/equipment-sheet");roleArt=Resources.Load<Texture2D>("Art/roles-sheet");enemyArt=Resources.Load<Texture2D>("Art/enemy-sheet");dungeonArt=Resources.Load<Texture2D>("Art/dungeon-sheet");uiFont=Resources.Load<Font>("Fonts/KleeOne-Regular");titleFont=Resources.Load<Font>("Fonts/KleeOne-SemiBold");screen=meta.characterMade?ScreenId.Hub:ScreenId.Character;Application.targetFrameRate=60;}
 void OnDestroy(){if(Instance==this)Instance=null;}
 void Update(){if(Input.GetKeyDown(KeyCode.F10))UiToggleDeveloperPanel();if(!visualScreenTracked){lastVisualScreen=screen;visualScreenTracked=true;return;}if(lastVisualScreen==screen)return;var previous=lastVisualScreen;lastVisualScreen=screen;PackspireUiFoundation.Instance?.PlayFor(previous,screen);}
 public void UiNavigate(ScreenId target){mapEventOverlay=false;mapLoadoutOverlay=false;if(target==ScreenId.Pack)OpenPacking();else{if(target==ScreenId.Hub||target==ScreenId.Status||target==ScreenId.Vault||target==ScreenId.Faction||target==ScreenId.Expedition||target==ScreenId.Compendium)run=null;screen=target;scroll=Vector2.zero;}}
 public void UiToggleDeveloperPanel(){developerPanel=!developerPanel;}
 public string UiRoleMilestone(string roleId,bool maximum)=>RoleMilestoneText(roleId,maximum);
 public void UiSelectHeirloom(string uid){if(meta.stash.Any(x=>x.uid==uid)){meta.selectedHeirloomUid=uid;SaveSystem.Save(meta);}}
 public bool UiTemper(string uid){var item=meta.stash.FirstOrDefault(x=>x.uid==uid);if(item==null||item.temper>=5)return false;int price=30*(item.temper+1);if(meta.baseGold<price)return false;meta.baseGold-=price;item.temper++;SaveSystem.Save(meta);return true;}
 public bool UiChangeFaction(string id){if(meta.currentFaction==id)return true;if(!GameCatalog.Factions.Any(x=>x.id==id)||meta.baseGold<20)return false;meta.baseGold-=20;meta.currentFaction=id;SaveSystem.Save(meta);return true;}
 public void UiSelectLoadout(string id){LoadoutSystem.Select(meta,id);SaveSystem.Save(meta);}
 public void UiStartExpedition(string dungeonId){StartRun(dungeonId);}
 public void UiSetAppearance(int bodyValue,int hairValue){meta.body=Mathf.Clamp(bodyValue,0,3);meta.hair=Mathf.Clamp(hairValue,0,2);}
 public void UiFinishCharacter(){meta.characterMade=true;SaveSystem.Save(meta);screen=ScreenId.Hub;scroll=Vector2.zero;}
 public void UiOpenPackingLoadout(string id){LoadoutSystem.Select(meta,id);OpenPacking();}
 public bool UiPackingPlace(string uid,int anchor,int rotation){if(run==null)return false;var item=run.inventory.FirstOrDefault(x=>x.uid==uid);if(item==null||!BackpackSystem.CanPlace(run,item,anchor,rotation,uid))return false;var old=run.placements.FirstOrDefault(x=>x.itemUid==uid);if(old!=null)run.placements.Remove(old);run.placements.Add(new Placement(uid,anchor,rotation));return true;}
 public void UiPackingRemove(string uid){if(run==null)return;var placement=run.placements.FirstOrDefault(x=>x.itemUid==uid);if(placement!=null)run.placements.Remove(placement);}
 public void UiPackingSetBackpack(string id){if(run==null||!GameCatalog.Backpacks.Any(x=>x.id==id))return;run.backpack=id;}
 public void UiPackingToggleCard(string slot){if(run==null)return;if(run.selectedCardSlots.Contains(slot))run.selectedCardSlots.Remove(slot);else if(run.selectedCardSlots.Count<LoadoutSystem.EquipmentCardLimit)run.selectedCardSlots.Add(slot);}
 public void UiPackingSave(){if(run==null)return;LoadoutSystem.Capture(meta,run);meta.selectedBackpack=run.backpack;SaveSystem.Save(meta);screen=packingAtBase?ScreenId.Hub:ScreenId.Map;}
 public void UiTakeReward(string itemId){if(run==null||!GameCatalog.Items.ContainsKey(itemId))return;run.lootBag.Add(new ItemInstance(itemId){identified=false});rewardSelectionId="";screen=ScreenId.Map;}
 public bool UiBuy(string itemId){if(run==null||!GameCatalog.Items.TryGetValue(itemId,out var item))return false;int price=14+item.cells.Length*4;if(run.gold<price)return false;run.gold-=price;run.lootBag.Add(new ItemInstance(itemId){identified=false});message=$"購入完了：{item.name}　残金 {run.gold}G";return true;}
 public void UiReturnToMap(){screen=ScreenId.Map;}
 public void UiResolveEvent(int choice){if(run==null)return;if(choice==0){run.hp=Mathf.Max(1,run.hp-6);run.gold+=24;}else if(choice==1)foreach(var item in run.inventory)item.durability=6;screen=ScreenId.Map;}
 public void UiReturnToHub(){run=null;screen=ScreenId.Hub;scroll=Vector2.zero;}
 void OpenPacking(){run=LoadoutSystem.CreateRun(meta,"");packingAtBase=true;selectedUid="";message="荷造りセットを編集";screen=ScreenId.Pack;}
 void StartRun(string dungeon){try{message="ダンジョンを生成中…";run=LoadoutSystem.CreateRun(meta,dungeon);packingAtBase=false;map=DungeonSystem.Generate(dungeon);if(map==null||map.zones==null||map.zones.Count==0)throw new Exception("区域データを生成できませんでした");screen=ScreenId.Map;selectedUid="";scroll=Vector2.zero;message=$"区域1：{DungeonSystem.CurrentZone(map).name}へ進入";}catch(Exception ex){run=null;map=null;screen=ScreenId.Expedition;message="遠征開始エラー："+ex.Message;Debug.LogException(ex);}}
 void EnterNode(MapNode n){if(n.cleared&&n.type!="shop")return;if(n.type=="battle"||n.type=="boss"){StartBattle(n.type=="boss");return;}if(n.type=="gate"){message="区域門へ到達した";return;}if(n.type=="shop"){screen=ScreenId.Shop;return;}if(n.type=="event"||n.type=="treasure"){n.cleared=true;mapEventNodeId=n.id;mapEventOverlay=true;message=n.type=="treasure"?"封じられた戦利品を発見":"記憶の揺らぎが道を覆った";return;}if(n.type=="rest"){n.cleared=true;run.hp=Mathf.Min(run.maxHp,run.hp+12);foreach(var i in run.inventory)i.durability=6;message="野営して回復・修理した";}else n.cleared=true;}
 void StartBattle(bool boss){var dungeon=GameCatalog.Dungeons.First(x=>x.id==run.dungeon);var pool=GameCatalog.Enemies.Where(x=>boss?x.tier==3:x.tier==Mathf.Min(2,1+run.battlesWon/3)).ToArray();battle=BattleSystem.Begin(run,pool[UnityEngine.Random.Range(0,pool.Length)],dungeon.hpScale);screen=ScreenId.Battle;}
 void WinBattle(){run.battlesWon++;run.gold+=12+run.battlesWon*3;run.hp=Mathf.Min(run.maxHp,run.hp+3);if(map!=null){var fought=map.nodes.FirstOrDefault(n=>n.id==map.current);if(fought!=null)fought.cleared=true;}if(battle.enemy.tier==3){FinishRun(true);return;}screen=ScreenId.Reward;}
 void FinishRun(bool win){if(win){meta.wins++;meta.baseGold+=run.gold;foreach(var item in run.inventory.Concat(run.lootBag)){var saved=meta.stash.FirstOrDefault(x=>x.uid==item.uid);if(saved==null)meta.stash.Add(CloneItem(item));else{saved.durability=item.durability;saved.uses=item.uses;saved.temper=item.temper;saved.scars=item.scars;saved.history=item.history;}}}else{var heir=run.inventory.FirstOrDefault(x=>x.uid==run.heirloomUid);if(heir!=null){heir.history.defeats++;heir.scars.Add(new ScarRecord{type="defeat",dungeon=run.dungeon,floor=run.battlesWon,timestamp=DateTimeOffset.UtcNow.ToUnixTimeSeconds()});var saved=meta.stash.FirstOrDefault(x=>x.uid==heir.uid);if(saved!=null){saved.scars=heir.scars;saved.history=heir.history;}}}meta.runs++;SaveSystem.Save(meta);message=win?"遠征成功。戦利品をすべて保管しました":"探索終了。戦利品と獲得ゴールドは持ち帰れません";screen=ScreenId.GameOver;}
 void AdvanceZone(){if(DungeonSystem.AdvanceZone(map)){message=$"区域 {map.currentZone+1}：{DungeonSystem.CurrentZone(map).name}へ進入";scroll=Vector2.zero;}}
 string RoleMilestoneText(string id,bool maximum){if(id.Contains("guardian")||id.Contains("bulwark")||id.Contains("knight"))return maximum?"戦闘開始時に防御を得て、余剰防御を次のターンへ一部持ち越す。":"防御カードを連続使用すると次の防御効果が上昇する。";if(id.Contains("scout")||id.Contains("hunter")||id.Contains("blade")||id.Contains("dancer"))return maximum?"各戦闘で最初に使う0コストカードを複製する。":"異なる装備由来のカードを続けて使うと追加ドロー。";if(id.Contains("artificer")||id.Contains("rune")||id.Contains("channeler"))return maximum?"戦闘中に最初に使うルーン・道具カードの耐久を消費しない。":"属性一致が3色以上なら戦闘開始時にエネルギーを得る。";return maximum?"武器カードを一定回数使うたび、ラン中の攻撃力が成長する。":"同じ武器由来のカードを続けて使うと追加ダメージ。";}
 ItemInstance CloneItem(ItemInstance x)=>JsonUtility.FromJson<ItemInstance>(JsonUtility.ToJson(x));
}
}
