using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Packspire {
public partial class PackspireGame : MonoBehaviour {
 string NodeName(string type)=>type=="battle"?"戦闘":type=="boss"?"区域主":type=="gate"?"区域門":type=="shop"?"商人":type=="rest"?"野営":type=="treasure"?"宝物":type=="event"?"イベント":type=="entrance"?"入口":"未踏";
 void DrawMapEventOverlay(){Rect full=new(0,0,Screen.width,Screen.height);GUI.color=new Color(.006f,.008f,.009f,.74f);GUI.DrawTexture(full,Texture2D.whiteTexture);GUI.color=Color.white;DrawEventMist(full);var node=map?.nodes.FirstOrDefault(x=>x.id==mapEventNodeId);bool treasure=node!=null&&node.type=="treasure";Rect panel=new(Screen.width*.145f,Screen.height*.095f,Screen.width*.71f,Screen.height*.80f);GUI.color=new Color(.015f,.016f,.014f,.97f);GUI.DrawTexture(panel,Texture2D.whiteTexture);GUI.color=Color.white;DrawOutline(panel,new Color(.67f,.48f,.20f,.92f),3);GUI.Label(new Rect(panel.x+28,panel.y+18,panel.width-56,44),treasure?"封印された遺物":"記憶の揺らぎ",new GUIStyle(screenTitle){fontSize=Mathf.RoundToInt(Mathf.Clamp(Screen.width*.021f,25f,36f)),fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter,normal={textColor=new Color(.96f,.82f,.52f)}});GUI.Label(new Rect(panel.x+40,panel.y+61,panel.width-80,25),treasure?"地図の上へ、所有者を失った記憶が滲み出している。":"周囲の道が黒い靄に沈み、まだ記されていない選択だけが浮かび上がる。",new GUIStyle(body){fontSize=15,alignment=TextAnchor.MiddleCenter,normal={textColor=new Color(.77f,.74f,.66f)}});float leftW=panel.width*.43f;Rect scene=new(panel.x+30,panel.y+102,leftW-42,panel.height-142);GUI.color=new Color(.50f,.44f,.36f,.78f);DrawDungeonArt(scene,run.dungeon);GUI.color=treasure?new Color(.45f,.27f,.04f,.28f):new Color(.20f,.03f,.28f,.38f);GUI.DrawTexture(scene,Texture2D.whiteTexture);GUI.color=Color.white;DrawOutline(scene,new Color(.58f,.41f,.19f,.82f),2);GUI.Label(new Rect(scene.x,scene.center.y-50,scene.width,100),treasure?"✦":"？",new GUIStyle(title){fontSize=68,fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter,normal={textColor=new Color(1f,.82f,.38f,.88f)}});GUI.Label(new Rect(scene.x+18,scene.yMax-88,scene.width-36,68),treasure?"錆びた封印の奥で、何かがこちらの気配を待っている。":"紫の残光が呼吸するように明滅し、探索者の記憶へ触れようとしている。",new GUIStyle(body){fontSize=14,wordWrap=true,alignment=TextAnchor.MiddleCenter,normal={textColor=new Color(.92f,.87f,.75f)}});float rightX=panel.x+leftW+18,rightW=panel.xMax-rightX-30,choiceH=(panel.height-142-22)/3f;if(DrawOverlayChoice(new Rect(rightX,panel.y+102,rightW,choiceH),"代償を支払う","HP -6　／　24Gを獲得",new Color(.58f,.17f,.18f))){run.hp=Mathf.Max(1,run.hp-6);run.gold+=24;CloseMapEvent("代償を払い、24Gを得た");}if(DrawOverlayChoice(new Rect(rightX,panel.y+102+choiceH+11,rightW,choiceH),"残響を修復する","すべての装備の耐久を回復",new Color(.18f,.45f,.36f))){foreach(var item in run.inventory)item.durability=6;CloseMapEvent("残響が装備を修復した");}if(DrawOverlayChoice(new Rect(rightX,panel.y+102+(choiceH+11)*2,rightW,choiceH),"靄を振り払う","何も得ず、地図の探索へ戻る",new Color(.42f,.34f,.24f)))CloseMapEvent("黒い靄を振り払い、探索へ戻った");}
 void DrawEventMist(Rect full){Rect[] clouds={new(-80,full.height*.10f,full.width*.46f,full.height*.30f),new(full.width*.62f,full.height*.05f,full.width*.45f,full.height*.33f),new(-120,full.height*.62f,full.width*.52f,full.height*.35f),new(full.width*.66f,full.height*.60f,full.width*.44f,full.height*.36f),new(full.width*.25f,-80,full.width*.50f,full.height*.25f),new(full.width*.26f,full.height*.78f,full.width*.49f,full.height*.27f)};foreach(var cloud in clouds){GUI.color=new Color(0,0,0,.42f);GUI.DrawTexture(cloud,bookChipTex,ScaleMode.StretchToFill,true);}GUI.color=Color.white;}
 bool DrawOverlayChoice(Rect rect,string label,string effect,Color accent){bool hover=rect.Contains(UnityEngine.Event.current.mousePosition);GUI.color=hover?new Color(.12f,.11f,.09f,.99f):new Color(.055f,.052f,.045f,.96f);GUI.DrawTexture(rect,Texture2D.whiteTexture);GUI.color=accent;GUI.DrawTexture(new Rect(rect.x,rect.y,Us(7),rect.height),Texture2D.whiteTexture);GUI.color=Color.white;DrawOutline(rect,hover?new Color(.83f,.62f,.28f):new Color(.39f,.31f,.20f),hover?3:1);GUI.Label(new Rect(rect.x+Us(26),rect.y+Us(13),rect.width-Us(52),Us(36)),label,new GUIStyle(header){fontSize=Fs(21),fontStyle=FontStyle.Bold,normal={textColor=new Color(.95f,.84f,.62f)}});GUI.Label(new Rect(rect.x+Us(27),rect.y+Us(52),rect.width-Us(54),rect.height-Us(64)),effect,new GUIStyle(body){fontSize=Fs(17),wordWrap=true,normal={textColor=new Color(.80f,.78f,.70f)}});return GUI.Button(rect,GUIContent.none,hotspot);}
 void CloseMapEvent(string result){mapEventOverlay=false;mapEventNodeId=-1;message=result;selectedMapNodeId=map.current;}
 void MapScrollScreen(){
  var dungeon=GameCatalog.Dungeons.First(x=>x.id==run.dungeon);var zone=DungeonSystem.CurrentZone(map);if(selectedMapNodeId<0||!map.nodes.Any(n=>n.id==selectedMapNodeId))selectedMapNodeId=map.current;
  Color inkColor=new(.20f,.105f,.045f),muted=new(.38f,.24f,.12f);Rect headerRect=new(Screen.width*.09f,Screen.height*.025f,Screen.width*.82f,Screen.height*.145f);GUI.Box(headerRect,GUIContent.none,new GUIStyle(){normal={background=bookChipTex},border=new RectOffset(14,14,14,14)});
  GUI.Label(new Rect(headerRect.x+Us(24),headerRect.y+Us(8),headerRect.width*.61f,Us(40)),$"{dungeon.name}　―　第{map.currentZone+1}区域 {zone.name}",new GUIStyle(screenTitle){fontSize=Fs(27),fontStyle=FontStyle.Bold,clipping=TextClipping.Overflow,normal={textColor=inkColor}});
  GUI.Label(new Rect(headerRect.x+Us(25),headerRect.y+Us(48),headerRect.width*.57f,Us(30)),$"踏破 {map.nodes.Count(n=>n.visited)}/{map.nodes.Count}　　戦闘 {DungeonSystem.ClearedBattles(map)}/{zone.requiredBattles}　　戦利品 {run.lootBag.Count}",new GUIStyle(body){fontSize=Fs(17),fontStyle=FontStyle.Bold,clipping=TextClipping.Overflow,normal={textColor=muted}});
  GUI.Label(new Rect(headerRect.x+Us(25),headerRect.yMax-Us(38),headerRect.width*.57f,Us(27)),string.IsNullOrEmpty(message)?"地図上の円を選び、下の行動欄で移動します。":message,new GUIStyle(screenSubtitle){fontSize=Fs(15),fontStyle=FontStyle.Bold,clipping=TextClipping.Overflow,normal={textColor=muted}});
  GUI.Label(new Rect(headerRect.xMax-headerRect.width*.27f,headerRect.y+Us(18),headerRect.width*.23f,Us(30)),"探索圧力は地図右下の方位盤に記録",new GUIStyle(screenSubtitle){fontSize=Fs(13),fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter,normal={textColor=muted}});
  Rect area=new(Screen.width*.075f,Screen.height*.175f,Screen.width*.85f,Screen.height*.585f);DrawMapTerrain(area);GUI.color=new Color(.22f,.12f,.035f,.12f);GUI.DrawTexture(area,Texture2D.whiteTexture);GUI.color=Color.white;DrawOutline(area,new Color(.48f,.27f,.08f,.82f),3);
  foreach(var edge in map.edges){var a=map.nodes.FirstOrDefault(n=>n.id==edge.a);var b=map.nodes.FirstOrDefault(n=>n.id==edge.b);if(a==null||b==null||!a.revealed||!b.revealed)continue;DrawMapRoadV2(MapPoint(area,a),MapPoint(area,b),edge.a==map.current||edge.b==map.current);}
  foreach(var n in map.nodes){Vector2 center=MapPoint(area,n);bool landmark=n.landmark;float size=landmark?Us(68):Us(52);Rect r=new(center.x-size*.5f,center.y-size*.5f,size,size);if(!n.revealed){GUI.color=new Color(.18f,.12f,.07f,.42f);GUI.DrawTexture(new Rect(center.x-Us(5),center.y-Us(5),Us(10),Us(10)),mapNodeCircleTex);GUI.color=Color.white;continue;}bool available=n.id==map.current||(DungeonSystem.Connected(map,map.current,n.id)&&DungeonSystem.CanMove(map,n.id));Color c=n.id==map.current?new Color(.85f,.58f,.15f):n.cleared?new Color(.20f,.42f,.25f):MapNodeColor(n.type);DrawMapNodeMedallion(r,n,c,available);GUI.enabled=available&&!mapEventOverlay&&!mapLoadoutOverlay;if(GUI.Button(r,GUIContent.none,hotspot))selectedMapNodeId=n.id;GUI.enabled=true;if(n.id==selectedMapNodeId)DrawCircleRing(r,new Color(1f,.75f,.24f),3);if(n.id==map.current)DrawMapPlayerToken(new Rect(r.center.x-Us(24),r.y-Us(42),Us(48),Us(62)));}
  DrawMapCompass(new Rect(area.xMax-Us(238),area.yMax-Us(218),Us(220),Us(200)));
  Rect action=new(Screen.width*.075f,Screen.height*.77f,Screen.width*.85f,Screen.height*.205f);GUI.Box(action,GUIContent.none,new GUIStyle(){normal={background=bookChipTex},border=new RectOffset(14,14,14,14)});var selected=map.nodes.FirstOrDefault(n=>n.id==selectedMapNodeId)??map.nodes.First(n=>n.id==map.current);GUI.Label(new Rect(action.x+Us(22),action.y+Us(8),action.width*.40f,Us(34)),selected.name,new GUIStyle(header){fontSize=Fs(22),fontStyle=FontStyle.Bold,clipping=TextClipping.Overflow,normal={textColor=inkColor}});GUI.Label(new Rect(action.x+Us(22),action.y+Us(42),action.width*.44f,Us(31)),$"{NodeName(selected.type)}　{(selected.cleared?"探索済み":"未探索")}　／　現在地：{map.nodes.First(n=>n.id==map.current).name}",new GUIStyle(body){fontSize=Fs(15),fontStyle=FontStyle.Bold,clipping=TextClipping.Overflow,normal={textColor=muted}});GUI.Label(new Rect(action.x+action.width*.48f,action.y+Us(8),action.width*.49f,Us(30)),"移動時の変化　"+NodeEffectPreview(selected),new GUIStyle(body){fontSize=Fs(15),fontStyle=FontStyle.Bold,clipping=TextClipping.Overflow,normal={textColor=inkColor}});GUI.Label(new Rect(action.x+action.width*.48f,action.y+Us(39),action.width*.49f,Us(31)),AxisForecastSummary(),new GUIStyle(screenSubtitle){fontSize=Fs(13),clipping=TextClipping.Overflow,normal={textColor=muted}});
  if(mapEventOverlay||mapLoadoutOverlay)return;bool transition=map.current==map.exit&&map.currentZone<map.zones.Count-1&&DungeonSystem.ExitUnlocked(map);if(transition){DrawMapTransitionButtons(action);return;}
  Rect backRect=new(action.x+Us(22),action.yMax-Us(58),Us(162),Us(48)),packRect=new(action.x+Us(196),action.yMax-Us(58),Us(178),Us(48)),lootRect=new(action.x+Us(386),action.yMax-Us(58),Us(154),Us(48)),moveRect=new(action.xMax-Us(258),action.yMax-Us(62),Us(236),Us(52));GUI.enabled=map.currentZone==0&&map.current==map.entrance;if(GUI.Button(backRect,"遠征を終了",button)){GUI.enabled=true;FinishRun(true);return;}GUI.enabled=true;if(GUI.Button(packRect,"編成カード確認",button)){mapLoadoutTab=0;mapLoadoutOverlay=true;}if(GUI.Button(lootRect,$"戦利品 {run.lootBag.Count}",button)){mapLoadoutTab=1;mapLoadoutOverlay=true;}bool canMove=selected.id!=map.current&&DungeonSystem.Connected(map,map.current,selected.id)&&DungeonSystem.CanMove(map,selected.id);GUI.enabled=canMove;if(GUI.Button(moveRect,canMove?"この地点へ移動":"移動先を選択",new GUIStyle(button){fontSize=Fs(19),fontStyle=FontStyle.Bold})){GUI.enabled=true;if(DungeonSystem.Move(map,selected.id,run)){selectedMapNodeId=map.current;EnterNode(selected);}return;}GUI.enabled=true;
 }
 void DrawMapCompass(Rect rect){GUI.color=new Color(.18f,.10f,.045f,.88f);GUI.DrawTexture(rect,mapNodeCircleTex,ScaleMode.StretchToFill,true);GUI.color=Color.white;DrawCircleRing(rect,new Color(.76f,.55f,.25f,.92f),3);DrawCircleRing(new Rect(rect.x+Us(8),rect.y+Us(8),rect.width-Us(16),rect.height-Us(16)),new Color(.34f,.20f,.09f,.85f),2);GUI.Label(new Rect(rect.x,rect.y+Us(5),rect.width,Us(25)),"探索方位盤",new GUIStyle(header){fontSize=Fs(14),fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter,normal={textColor=new Color(.91f,.75f,.42f)}});DrawAxisTriangle(new Rect(rect.x+Us(12),rect.y+Us(28),rect.width-Us(24),rect.height-Us(35)));}
 string AxisEdgeLabel(int value)=>value>=0?$"極大まで {15-value}":$"極小まで {15+value}";
 string AxisForecastSummary()=>$"境界まで　警戒 {AxisEdgeLabel(run.axes.alert)}　／　崩壊 {AxisEdgeLabel(run.axes.collapse)}　／　侵蝕 {AxisEdgeLabel(run.axes.corruption)}";
 string NodeEffectPreview(MapNode node){int collapse=node.type=="treasure"?2:node.type=="rest"?-1:0,corruption=node.type=="event"?2:node.type=="battle"?1:0;return $"警戒 +1　崩壊 {collapse:+#;-#;±0}　侵蝕 {corruption:+#;-#;±0}";}
 void DrawMapTransitionButtons(Rect action){GUI.Label(new Rect(action.center.x-130,action.y+8,260,28),"区域踏破 ― 次の行動",new GUIStyle(header){fontSize=20,alignment=TextAnchor.MiddleCenter});float w=(action.width-64)/3f,y=action.yMax-59;if(GUI.Button(new Rect(action.x+16,y,w,48),"野営して進む",button)){run.hp=Mathf.Min(run.maxHp,run.hp+8);foreach(var item in run.inventory)item.durability=Mathf.Min(6,item.durability+1);AdvanceZone();selectedMapNodeId=map.current;}if(GUI.Button(new Rect(action.x+24+w,y,w,48),"痕跡を消して進む",button)){run.axes.Change(-2,0,1);AdvanceZone();selectedMapNodeId=map.current;}if(GUI.Button(new Rect(action.x+32+w*2,y,w,48),"残骸を回収して進む",button)){run.gold+=18;run.axes.Change(0,2,0);AdvanceZone();selectedMapNodeId=map.current;}}
 Vector2 MapPoint(Rect area,MapNode node)=>new(area.x+area.width*node.x/100f,area.y+area.height*node.y/100f);
 void DrawMapTerrain(Rect area){if(mapTerrain!=null)GUI.DrawTexture(area,mapTerrain,ScaleMode.ScaleAndCrop,true);else DrawDungeonArt(area,run.dungeon);GUI.color=new Color(1f,.91f,.72f,.15f);GUI.DrawTexture(area,Texture2D.whiteTexture);GUI.color=Color.white;}
 void DrawMapRoadV2(Vector2 start,Vector2 end,bool active){Vector2 delta=end-start;float length=delta.magnitude;if(length<1)return;DrawMapLineV2(start,end,active?new Color(.62f,.42f,.13f,.42f):new Color(.20f,.16f,.10f,.30f),8f);if(mapRoad!=null){Matrix4x4 old=GUI.matrix;GUIUtility.RotateAroundPivot(Mathf.Atan2(delta.y,delta.x)*Mathf.Rad2Deg,start);GUI.color=active?new Color(1f,.86f,.56f,.90f):new Color(.68f,.65f,.55f,.46f);GUI.DrawTextureWithTexCoords(new Rect(start.x,start.y-7f,length,14f),mapRoad,new Rect(0,0,Mathf.Max(1,length/150f),1),true);GUI.color=Color.white;GUI.matrix=old;}else DrawMapLineV2(start,end,new Color(.42f,.36f,.24f,.72f),6f);if(active)DrawMapLineV2(start,end,new Color(1f,.72f,.24f,.62f),2f);}
 void DrawMapLineV2(Vector2 start,Vector2 end,Color color,float width){Vector2 delta=end-start;float length=delta.magnitude;if(length<1)return;Matrix4x4 old=GUI.matrix;GUIUtility.RotateAroundPivot(Mathf.Atan2(delta.y,delta.x)*Mathf.Rad2Deg,start);GUI.color=color;GUI.DrawTexture(new Rect(start.x,start.y-width*.5f,length,width),Texture2D.whiteTexture);GUI.color=Color.white;GUI.matrix=old;}
 string MapNodeIcon(string type)=>type=="battle"?"⚔":type=="boss"?"♛":type=="gate"?"◇":type=="shop"?"◆":type=="rest"?"♥":type=="treasure"?"✦":type=="event"?"?":type=="entrance"?"⌂":"●";
 void DrawMapNodeMedallion(Rect rect,MapNode node,Color color,bool available){Rect shadow=new(rect.x+Us(4),rect.y+Us(5),rect.width,rect.height);GUI.color=new Color(0,0,0,.38f);GUI.DrawTexture(shadow,mapNodeCircleTex,ScaleMode.StretchToFill,true);GUI.color=available?color:new Color(.29f,.27f,.24f,.92f);GUI.DrawTexture(rect,mapNodeCircleTex,ScaleMode.StretchToFill,true);GUI.color=Color.white;GUI.Label(rect,MapNodeIcon(node.type),new GUIStyle(header){fontSize=node.landmark?Fs(27):Fs(23),fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter,normal={textColor=available?Color.white:new Color(.68f,.65f,.58f)}});if(node.cleared){Rect mark=new(rect.xMax-Us(14),rect.y-Us(3),Us(18),Us(18));GUI.color=new Color(.92f,.72f,.30f);GUI.DrawTexture(mark,mapNodeCircleTex);GUI.color=Color.white;GUI.Label(mark,"✓",new GUIStyle(body){fontSize=Fs(11),fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter,normal={textColor=new Color(.29f,.16f,.06f)}});}}
 Color MapNodeColor(string type)=>type=="battle"?new Color(.36f,.12f,.10f,.97f):type=="boss"?new Color(.43f,.08f,.08f,.98f):type=="gate"?new Color(.39f,.28f,.09f,.98f):type=="shop"?new Color(.18f,.29f,.34f,.97f):type=="rest"?new Color(.13f,.31f,.19f,.97f):type=="treasure"?new Color(.42f,.31f,.10f,.97f):type=="event"?new Color(.31f,.18f,.40f,.97f):new Color(.10f,.14f,.11f,.96f);
 void DrawAxisTriangle(Rect rect){Vector2 center=new(rect.center.x,rect.center.y+Us(5)),top=new(rect.center.x,rect.y+Us(15)),left=new(rect.x+Us(30),rect.yMax-Us(22)),right=new(rect.xMax-Us(30),rect.yMax-Us(22));Color grid=new(.34f,.23f,.13f,.46f);for(int i=1;i<=3;i++){float t=i/3f;Vector2 a=Vector2.Lerp(center,top,t),b=Vector2.Lerp(center,right,t),c=Vector2.Lerp(center,left,t);DrawMapLineV2(a,b,grid,1.5f);DrawMapLineV2(b,c,grid,1.5f);DrawMapLineV2(c,a,grid,1.5f);}DrawMapLineV2(center,top,grid,1.5f);DrawMapLineV2(center,left,grid,1.5f);DrawMapLineV2(center,right,grid,1.5f);Vector2 pAlert=Vector2.Lerp(center,top,Mathf.InverseLerp(-15,15,run.axes.alert)),pCollapse=Vector2.Lerp(center,right,Mathf.InverseLerp(-15,15,run.axes.collapse)),pCorruption=Vector2.Lerp(center,left,Mathf.InverseLerp(-15,15,run.axes.corruption));DrawMapLineV2(pAlert,pCollapse,new Color(.72f,.26f,.16f,.92f),Us(4));DrawMapLineV2(pCollapse,pCorruption,new Color(.62f,.35f,.16f,.92f),Us(4));DrawMapLineV2(pCorruption,pAlert,new Color(.47f,.23f,.56f,.92f),Us(4));DrawAxisPoint(pAlert,new Color(.72f,.22f,.15f));DrawAxisPoint(pCollapse,new Color(.68f,.43f,.12f));DrawAxisPoint(pCorruption,new Color(.44f,.20f,.58f));var labelStyle=new GUIStyle(body){fontSize=Fs(13),fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter,clipping=TextClipping.Overflow,normal={textColor=new Color(.24f,.13f,.06f)}};GUI.Label(new Rect(top.x-Us(56),rect.y-Us(1),Us(112),Us(24)),$"警戒 {run.axes.alert:+#;-#;0}",labelStyle);GUI.Label(new Rect(right.x-Us(24),right.y-Us(2),Us(105),Us(24)),$"崩壊 {run.axes.collapse:+#;-#;0}",labelStyle);GUI.Label(new Rect(left.x-Us(82),left.y-Us(2),Us(105),Us(24)),$"侵蝕 {run.axes.corruption:+#;-#;0}",labelStyle);}
 void DrawAxisPoint(Vector2 point,Color color){Rect r=new(point.x-Us(5),point.y-Us(5),Us(10),Us(10));GUI.color=color;GUI.DrawTexture(r,mapNodeCircleTex);GUI.color=Color.white;}
 void DrawCircleRing(Rect rect,Color color,float thickness){for(int i=3;i>=0;i--){Rect r=new(rect.x-Us(5)-i,rect.y-Us(5)-i,rect.width+Us(10)+i*2,rect.height+Us(10)+i*2);GUI.color=new Color(color.r,color.g,color.b,.08f+i*.035f);GUI.DrawTexture(r,mapNodeCircleTex,ScaleMode.StretchToFill,true);}GUI.color=Color.white;}
 void DrawMapPlayerToken(Rect rect){GUI.color=new Color(0,0,0,.42f);GUI.DrawTexture(new Rect(rect.x+Us(4),rect.y+Us(5),rect.width,rect.height),mapNodeCircleTex,ScaleMode.StretchToFill,true);GUI.color=Color.white;GUI.BeginGroup(rect);DrawCharacter(new Rect(-rect.width*.10f,-rect.height*.02f,rect.width*1.20f,rect.height*1.20f),meta.body,meta.hair);GUI.EndGroup();}
 void DrawMapLoadoutOverlay(){Rect full=new(0,0,Screen.width,Screen.height);GUI.color=new Color(.008f,.009f,.008f,.78f);GUI.DrawTexture(full,Texture2D.whiteTexture);GUI.color=Color.white;Rect panel=new(Screen.width*.11f,Screen.height*.075f,Screen.width*.78f,Screen.height*.84f);GUI.DrawTexture(panel,backpackLeatherTex,ScaleMode.StretchToFill,true);Rect page=new(panel.x+Us(22),panel.y+Us(20),panel.width-Us(44),panel.height-Us(40));GUI.Box(page,GUIContent.none,new GUIStyle(){normal={background=bookChipTex},border=new RectOffset(14,14,14,14)});GUI.Label(new Rect(page.x+Us(24),page.y+Us(12),page.width-Us(48),Us(38)),"遠征記録 ― 持ち込み品",new GUIStyle(screenTitle){fontSize=Fs(26),fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleLeft,normal={textColor=new Color(.23f,.12f,.05f)}});float tabW=Us(190);if(GUI.Button(new Rect(page.x+Us(24),page.y+Us(58),tabW,Us(48)),"編成・カード",mapLoadoutTab==0?navSelected:navButton))mapLoadoutTab=0;if(GUI.Button(new Rect(page.x+Us(24)+tabW+Us(10),page.y+Us(58),tabW,Us(48)),$"戦利品 {run.lootBag.Count}",mapLoadoutTab==1?navSelected:navButton))mapLoadoutTab=1;if(GUI.Button(new Rect(page.xMax-Us(148),page.y+Us(16),Us(124),Us(44)),"地図へ戻る",button))mapLoadoutOverlay=false;Rect content=new(page.x+Us(24),page.y+Us(120),page.width-Us(48),page.height-Us(144));if(mapLoadoutTab==0)DrawReadonlyLoadout(content);else DrawReadonlyLoot(content);}
 void DrawReadonlyLoadout(Rect area){var build=BackpackSystem.Build(run);string bag=GameCatalog.Backpacks.FirstOrDefault(x=>x.id==run.backpack)?.name??run.backpack;GUI.Label(new Rect(area.x,area.y,area.width,Us(30)),$"{bag}　／　配置装備 {run.placements.Count}　／　デッキ {build.deck.Count}枚",new GUIStyle(header){fontSize=Fs(19),clipping=TextClipping.Overflow,normal={textColor=new Color(.28f,.15f,.06f)}});float itemSize=Us(82);for(int i=0;i<run.inventory.Count&&i<8;i++){Rect r=new(area.x+i*(itemSize+Us(8)),area.y+Us(42),itemSize,itemSize);DrawItemArt(r,run.inventory[i].templateId);DrawOutline(r,new Color(.48f,.31f,.13f),2);}float cardW=(area.width-Us(45))/4f,cardH=Mathf.Min(Us(178),area.height-Us(155));for(int i=0;i<build.deck.Count&&i<8;i++){int row=i/4,col=i%4;Rect cardRect=new(area.x+col*(cardW+Us(15)),area.y+Us(142)+row*(cardH+Us(12)),cardW,cardH);DrawReadonlyCard(cardRect,build.deck[i]);}}
 void DrawReadonlyCard(Rect rect,CardInstance cardData){GUI.Box(rect,GUIContent.none,bookEntryStyle);Color accent=cardData.type==CardType.Attack?new Color(.62f,.22f,.15f):cardData.type==CardType.Skill?new Color(.16f,.39f,.52f):new Color(.42f,.24f,.52f);GUI.color=accent;GUI.DrawTexture(new Rect(rect.x,rect.y,Us(7),rect.height),Texture2D.whiteTexture);GUI.color=Color.white;GUI.Label(new Rect(rect.x+Us(13),rect.y+Us(8),Us(38),Us(34)),cardData.cost.ToString(),new GUIStyle(header){fontSize=Fs(23),alignment=TextAnchor.MiddleCenter,normal={textColor=accent}});GUI.Label(new Rect(rect.x+Us(54),rect.y+Us(8),rect.width-Us(65),Us(34)),cardData.name,new GUIStyle(header){fontSize=Fs(17),fontStyle=FontStyle.Bold,clipping=TextClipping.Overflow,normal={textColor=new Color(.26f,.14f,.06f)}});GUI.Label(new Rect(rect.x+Us(15),rect.y+Us(50),rect.width-Us(30),rect.height-Us(72)),cardData.text,new GUIStyle(body){fontSize=Fs(14),wordWrap=true,clipping=TextClipping.Overflow,normal={textColor=new Color(.34f,.23f,.14f)}});GUI.Label(new Rect(rect.x+Us(14),rect.yMax-Us(25),rect.width-Us(28),Us(20)),cardData.source,new GUIStyle(screenSubtitle){fontSize=Fs(11),alignment=TextAnchor.MiddleRight,clipping=TextClipping.Overflow,normal={textColor=new Color(.44f,.31f,.20f)}});}
 void DrawReadonlyLoot(Rect area){GUI.Label(new Rect(area.x,area.y,area.width,Us(34)),"この遠征で獲得した戦利品",new GUIStyle(header){fontSize=Fs(20),normal={textColor=new Color(.28f,.15f,.06f)}});if(run.lootBag.Count==0){GUI.Label(new Rect(area.x,area.y+Us(80),area.width,Us(90)),"まだ戦利品はありません\n戦闘報酬や宝物区画で獲得した品がここへ記録されます。",new GUIStyle(body){fontSize=Fs(18),fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter,wordWrap=true,normal={textColor=new Color(.42f,.31f,.20f)}});return;}float size=Mathf.Min(Us(150),(area.width-Us(64))/5f);for(int i=0;i<run.lootBag.Count;i++){int row=i/5,col=i%5;var item=run.lootBag[i];Rect r=new(area.x+col*(size+Us(16)),area.y+Us(48)+row*(size+Us(48)),size,size);DrawItemArt(r,item.templateId);DrawOutline(r,TypeColor(GameCatalog.Items[item.templateId].type),3);GUI.Label(new Rect(r.x-Us(5),r.yMax+Us(5),r.width+Us(10),Us(36)),item.identified?GameCatalog.Items[item.templateId].name:"未鑑定品",new GUIStyle(body){fontSize=Fs(15),fontStyle=FontStyle.Bold,alignment=TextAnchor.UpperCenter,wordWrap=true,clipping=TextClipping.Overflow,normal={textColor=new Color(.29f,.17f,.08f)}});}}
 Color TypeColor(ItemType t)=>t==ItemType.Weapon?new(.54f,.21f,.16f):t==ItemType.Armor?new(.16f,.38f,.48f):t==ItemType.Rune?new(.39f,.22f,.51f):new(.56f,.42f,.14f);
}
}
