using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Packspire {
public class PackspireGame : MonoBehaviour {
 MetaSave meta; RunState run; DungeonMap map; BattleState battle; ScreenId screen; Vector2 scroll; string selectedUid="",message=""; int selectedRotation; GUIStyle title,header,body,button,card; Texture2D factionArt;
 readonly Color bg=new(0.055f,0.07f,0.06f),panel=new(0.10f,0.12f,0.105f),gold=new(0.84f,0.68f,0.35f),ink=new(0.9f,0.89f,0.84f);
 void Awake(){DontDestroyOnLoad(gameObject);meta=SaveSystem.Load();factionArt=Resources.Load<Texture2D>("Art/faction-hub-sheet");screen=meta.characterMade?ScreenId.Hub:ScreenId.Character;Application.targetFrameRate=60;}
 void InitStyles(){if(title!=null)return;title=new GUIStyle(GUI.skin.label){fontSize=34,fontStyle=FontStyle.Bold,normal={textColor=ink}};header=new GUIStyle(GUI.skin.label){fontSize=20,fontStyle=FontStyle.Bold,normal={textColor=gold}};body=new GUIStyle(GUI.skin.label){fontSize=14,wordWrap=true,normal={textColor=ink}};button=new GUIStyle(GUI.skin.button){fontSize=14,alignment=TextAnchor.MiddleLeft,padding=new RectOffset(14,14,10,10)};card=new GUIStyle(GUI.skin.button){fontSize=12,alignment=TextAnchor.UpperLeft,wordWrap=true,padding=new RectOffset(10,10,10,10)};}
 void OnGUI(){InitStyles();GUI.backgroundColor=bg;GUI.Box(new Rect(0,0,Screen.width,Screen.height),GUIContent.none);GUI.backgroundColor=Color.white;GUILayout.BeginArea(new Rect(28,20,Screen.width-56,Screen.height-40));TopBar();scroll=GUILayout.BeginScrollView(scroll);switch(screen){case ScreenId.Character:Character();break;case ScreenId.Hub:Hub();break;case ScreenId.Status:Status();break;case ScreenId.Vault:Vault();break;case ScreenId.Faction:Faction();break;case ScreenId.Expedition:Expedition();break;case ScreenId.Pack:Pack();break;case ScreenId.Map:Map();break;case ScreenId.Battle:Battle();break;case ScreenId.Reward:Reward();break;case ScreenId.Shop:Shop();break;case ScreenId.Event:Event();break;case ScreenId.Compendium:Compendium();break;case ScreenId.GameOver:GameOver();break;}GUILayout.EndScrollView();GUILayout.EndArea();}
 void TopBar(){GUILayout.BeginHorizontal();GUILayout.Label("PACKSPIRE <UNITY>",title);GUILayout.FlexibleSpace();if(run!=null)GUILayout.Label($"HP {run.hp}/{run.maxHp}　{run.gold}G　{GameCatalog.Roles[run.role].name}",header);GUILayout.EndHorizontal();Line();}
 void Character(){GUILayout.Label("キャラクター作成",header);GUILayout.Label("体格と髪型を選択してください。能力差はありません。",body);GUILayout.Space(20);GUILayout.Label("体格",body);GUILayout.BeginHorizontal();for(int i=0;i<4;i++){int n=i;if(GUILayout.Button($"{(i<2?"男性":"女性")}タイプ {(i%2)+1}",button,GUILayout.Height(55)))meta.body=n;}GUILayout.EndHorizontal();GUILayout.Label("髪型",body);GUILayout.BeginHorizontal();string[] hair={"短髪","ミディアム","結び髪"};for(int i=0;i<3;i++){int n=i;if(GUILayout.Button(hair[i],button,GUILayout.Height(55)))meta.hair=n;}GUILayout.EndHorizontal();GUILayout.Space(30);if(GUILayout.Button($"この姿で始める　体格{meta.body+1}／{hair[meta.hair]}",button,GUILayout.Height(65))){meta.characterMade=true;SaveSystem.Save(meta);screen=ScreenId.Hub;}}
 void Hub(){GUILayout.Label($"{Faction(meta.currentFaction).name}の拠点",header);if(factionArt!=null){Rect art=GUILayoutUtility.GetRect(900,260);int index=Array.FindIndex(GameCatalog.Factions,x=>x.id==meta.currentFaction),col=index%2,row=index/2;GUI.DrawTextureWithTexCoords(art,factionArt,new Rect(col*.5f,.5f-row*.5f,.5f,.5f),true);}GUILayout.Label($"中央には{GameCatalog.Roles[meta.currentRole].name}として成長した探索者が立つ。所属、衣装、家宝は永続状態を反映します。",body);GUILayout.Space(16);GUILayout.BeginHorizontal();HubButton("遠征","ダンジョンを選び、支給品と契約を決める。",ScreenId.Expedition);HubButton("保管庫","家宝、バックパック、保管装備を管理。",ScreenId.Vault);HubButton("ステータス","習得役職とレベル効果を確認。",ScreenId.Status);GUILayout.EndHorizontal();GUILayout.BeginHorizontal();HubButton("勢力","勢力関係、貢献度、所属変更。",ScreenId.Faction);HubButton("図鑑","発見した装備、敵、役職。",ScreenId.Compendium);if(GUILayout.Button("セーブ",button,GUILayout.Height(90))){SaveSystem.Save(meta);message="保存しました";}GUILayout.EndHorizontal();GUILayout.Label(message,body);}
 void HubButton(string name,string desc,ScreenId next){if(GUILayout.Button($"{name}\n{desc}",button,GUILayout.Height(110)))screen=next;}
 void Status(){Back();GUILayout.Label($"現在職：{GameCatalog.Roles[meta.currentRole].name}",header);foreach(var level in meta.jobLevels.Where(x=>x.value>0)){var r=GameCatalog.Roles[level.id];GUILayout.BeginVertical(GUI.skin.box);GUILayout.Label($"{r.name}　Lv.{level.value}/{r.maxLevel}",header);GUILayout.Label(r.description,body);GUILayout.Label("Lv.7・最大レベルで専用効果候補を解禁",body);GUILayout.EndVertical();}}
 void Vault(){Back();GUILayout.Label($"保管庫 {meta.stash.Count}/{4+meta.vaultLevel*4}",header);GUILayout.Label($"使用中：{GameCatalog.Backpacks.First(x=>x.id==meta.selectedBackpack).name}",body);GUILayout.BeginHorizontal();foreach(var bag in GameCatalog.Backpacks){if(GUILayout.Button(bag.name,button,GUILayout.Height(55))){meta.selectedBackpack=bag.id;SaveSystem.Save(meta);}}GUILayout.EndHorizontal();foreach(var item in meta.stash){var d=GameCatalog.Items[item.templateId];GUILayout.BeginHorizontal(GUI.skin.box);GUILayout.Label($"{(item.uid==meta.selectedHeirloomUid?"★ ":"")}{d.name} +{item.temper}　耐久{item.durability}/6　使用{item.uses}",body);if(GUILayout.Button("家宝",GUILayout.Width(80)))meta.selectedHeirloomUid=item.uid;if(GUILayout.Button("鍛錬",GUILayout.Width(80))&&meta.baseGold>=30*(item.temper+1)){meta.baseGold-=30*(item.temper+1);item.temper=Mathf.Min(5,item.temper+1);}GUILayout.EndHorizontal();}SaveSystem.Save(meta);}
 void Faction(){Back();GUILayout.Label("勢力関係図",header);GUILayout.Label("片方へ肩入れすると競合勢力の評判が下がります。",body);foreach(var f in GameCatalog.Factions){float rep=meta.factionRep.First(x=>x.id==f.id).value;GUILayout.BeginHorizontal(GUI.skin.box);GUILayout.Label($"{f.name}　貢献 {rep:0}　{f.description}",body);if(GUILayout.Button(meta.currentFaction==f.id?"所属中":"20Gで所属",GUILayout.Width(120))&&meta.currentFaction!=f.id&&meta.baseGold>=20){meta.baseGold-=20;meta.currentFaction=f.id;SaveSystem.Save(meta);}GUILayout.EndHorizontal();}}
 void Expedition(){Back();GUILayout.Label("遠征先",header);for(int i=0;i<GameCatalog.Dungeons.Length;i++){var d=GameCatalog.Dungeons[i];GUI.enabled=i<meta.dungeonsUnlocked;if(GUILayout.Button($"{d.name}\n{d.description}　戦闘{d.battles}回",button,GUILayout.Height(80))){StartRun(d.id);}GUI.enabled=true;}}
 void StartRun(string dungeon){run=new RunState{role=meta.currentRole,faction=meta.currentFaction,backpack=meta.selectedBackpack,dungeon=dungeon,hp=42,maxHp=42,gold=meta.baseGold};var heir=meta.stash.FirstOrDefault(x=>x.uid==meta.selectedHeirloomUid);if(heir!=null)run.inventory.Add(CloneItem(heir));run.inventory.Add(new ItemInstance("sword","supply"));run.inventory.Add(new ItemInstance("herb","supply"));map=DungeonSystem.Generate();screen=ScreenId.Pack;selectedUid="";message="支給品を配置してください";}
 void Pack(){GUILayout.BeginHorizontal();if(GUILayout.Button("← マップ",GUILayout.Width(100)))screen=ScreenId.Map;if(GUILayout.Button("↻ 回転",GUILayout.Width(100)))selectedRotation=(selectedRotation+1)%4;if(GUILayout.Button("選択を外す",GUILayout.Width(110)))selectedUid="";GUILayout.Label(message,body);GUILayout.EndHorizontal();GUILayout.BeginHorizontal();GUILayout.BeginVertical(GUILayout.Width(250));GUILayout.Label("所持品",header);foreach(var item in run.inventory){var d=GameCatalog.Items[item.templateId];bool placed=run.placements.Any(x=>x.itemUid==item.uid);GUI.enabled=!placed;if(GUILayout.Button($"{d.name}\n{d.description}",card,GUILayout.Height(65))){selectedUid=item.uid;selectedRotation=0;}GUI.enabled=true;}GUILayout.EndVertical();GUILayout.Space(18);DrawGrid();GUILayout.Space(18);GUILayout.BeginVertical(GUILayout.Width(300));GUILayout.Label($"生成デッキ {BackpackSystem.BuildDeck(run).Count}枚",header);foreach(var c in BackpackSystem.BuildDeck(run))GUILayout.Label($"{c.name} [{c.cost}]　{c.source}",body);GUILayout.EndVertical();GUILayout.EndHorizontal();if(GUILayout.Button("配置を確定",button,GUILayout.Height(55)))screen=ScreenId.Map;}
void DrawGrid(){GUILayout.BeginVertical(GUILayout.Width(480));GUILayout.Label("6×4 色マスバックパック　◆が外周に触れるとカード化",header);Rect grid=GUILayoutUtility.GetRect(456,304);float cw=grid.width/6,ch=grid.height/4;for(int i=0;i<24;i++){Rect r=new(grid.x+(i%6)*cw,grid.y+(i/6)*ch,cw-3,ch-3);var e=GameCatalog.Board[i];GUI.backgroundColor=ElementColor(e);if(GUI.Button(r,e.ToString()[0].ToString()))TryPlace(i);GUI.backgroundColor=Color.white;}foreach(var p in run.placements.ToList()){var item=run.inventory.First(x=>x.uid==p.itemUid);var def=GameCatalog.Items[item.templateId];var analysis=BackpackSystem.Analyze(item,p);foreach(var cell in BackpackSystem.Layout(def,p.rotation)){int index=p.anchor+cell.pos.y*6+cell.pos.x;Rect r=new(grid.x+(index%6)*cw+5,grid.y+(index/6)*ch+5,cw-13,ch-13);bool match=GameCatalog.Board[index]==cell.element;GUI.backgroundColor=match?Color.white:TypeColor(def.type);if(GUI.Button(r,$"{def.name[0]}{(cell.original==def.handle?"◆":"")}\n{cell.element.ToString()[0]}{(match?" 一致":"")}")){selectedUid=item.uid;selectedRotation=p.rotation;if(UnityEngine.Event.current.button==1){run.placements.Remove(p);message=def.name+"を外しました";}}GUI.backgroundColor=Color.white;}}GUILayout.EndVertical();}
 void TryPlace(int cell){if(string.IsNullOrEmpty(selectedUid))return;var item=run.inventory.FirstOrDefault(x=>x.uid==selectedUid);if(item==null)return;var old=run.placements.FirstOrDefault(x=>x.itemUid==selectedUid);if(BackpackSystem.CanPlace(run,item,cell,selectedRotation,selectedUid)){if(old!=null)run.placements.Remove(old);run.placements.Add(new Placement(item.uid,cell,selectedRotation));message=GameCatalog.Items[item.templateId].name+"を配置";}else message="そこには入りません";}
 void Map(){GUILayout.BeginHorizontal();if(GUILayout.Button("荷造り",GUILayout.Width(100)))screen=ScreenId.Pack;if(GUILayout.Button("入口から帰還",GUILayout.Width(130))&&map.current==12){FinishRun(true);return;}GUILayout.Label($"警戒 {map.alert}　戦闘勝利 {run.battlesWon}",header);GUILayout.EndHorizontal();Rect area=GUILayoutUtility.GetRect(720,520);float w=area.width/6,h=area.height/6;foreach(var n in map.nodes){Rect r=new(area.x+n.x*w+3,area.y+n.y*h+3,w-6,h-6);GUI.enabled=n.revealed&&(n.id==map.current||DungeonSystem.Adjacent(map.current,n.id));GUI.backgroundColor=n.id==map.current?gold:n.visited?new Color(.25f,.35f,.25f):panel;if(GUI.Button(r,n.revealed?n.type:"？")){if(n.id!=map.current&&DungeonSystem.Move(map,n.id))EnterNode(n);}GUI.backgroundColor=Color.white;GUI.enabled=true;}}
 void EnterNode(MapNode n){if(n.type=="battle"||n.type=="boss"){StartBattle(n.type=="boss");return;}if(n.type=="shop"){screen=ScreenId.Shop;return;}if(n.type=="event"||n.type=="treasure"){screen=ScreenId.Event;return;}if(n.type=="rest"){run.hp=Mathf.Min(run.maxHp,run.hp+12);foreach(var i in run.inventory)i.durability=6;message="野営して回復・修理した";}}
 void StartBattle(bool boss){var dungeon=GameCatalog.Dungeons.First(x=>x.id==run.dungeon);var pool=GameCatalog.Enemies.Where(x=>boss?x.tier==3:x.tier==Mathf.Min(2,1+run.battlesWon/3)).ToArray();battle=BattleSystem.Begin(run,pool[UnityEngine.Random.Range(0,pool.Length)],dungeon.hpScale);screen=ScreenId.Battle;}
 void Battle(){var dungeon=GameCatalog.Dungeons.First(x=>x.id==run.dungeon);GUILayout.Label($"{battle.enemy.name}　HP {Mathf.Max(0,battle.enemyHp)}/{battle.enemyMaxHp}",header);GUILayout.Label($"次の攻撃 {battle.enemy.damages[battle.move%battle.enemy.damages.Length]+dungeon.damage}　　自分 HP {run.hp}/{run.maxHp} 防御{run.block} EN{run.energy}",body);GUILayout.Label(battle.log,body);GUILayout.BeginHorizontal();for(int i=0;i<run.hand.Count;i++){int index=i;var c=run.hand[i];GUI.enabled=c.cost<=run.energy;if(GUILayout.Button($"[{c.cost}] {c.name}\n{c.text}\n{c.source}",card,GUILayout.Width(155),GUILayout.Height(150))){if(BattleSystem.Play(run,battle,index)){WinBattle();return;}}GUI.enabled=true;}GUILayout.EndHorizontal();if(GUILayout.Button("ターン終了",button,GUILayout.Height(50))){if(BattleSystem.EndTurn(run,battle,dungeon.damage)){FinishRun(false);return;}}}
 void WinBattle(){run.battlesWon++;run.gold+=12+run.battlesWon*3;run.hp=Mathf.Min(run.maxHp,run.hp+3);if(battle.enemy.tier==3){FinishRun(true);return;}screen=ScreenId.Reward;}
 void Reward(){GUILayout.Label("戦果を1つ選択",header);string[] pool={"dagger","plate","crystal","bomb","spear","buckler","flask","charm"};GUILayout.BeginHorizontal();foreach(var id in pool.OrderBy(_=>UnityEngine.Random.value).Take(3)){if(GUILayout.Button(GameCatalog.Items[id].name,button,GUILayout.Width(220),GUILayout.Height(100))){run.inventory.Add(new ItemInstance(id));screen=ScreenId.Map;}}GUILayout.EndHorizontal();}
 void Shop(){GUILayout.Label("行商人",header);foreach(var id in GameCatalog.Items.Keys.Take(5)){int price=14+GameCatalog.Items[id].cells.Length*4;if(GUILayout.Button($"{GameCatalog.Items[id].name}　{price}G",button)&&run.gold>=price){run.gold-=price;run.inventory.Add(new ItemInstance(id));}}if(GUILayout.Button("戻る",button))screen=ScreenId.Map;}
 void Event(){GUILayout.Label("記憶の揺らぎ",header);GUILayout.Label("古塔の記憶が選択を要求している。",body);if(GUILayout.Button("6HPを支払い24Gを得る",button)){run.hp=Mathf.Max(1,run.hp-6);run.gold+=24;screen=ScreenId.Map;}if(GUILayout.Button("装備を修理する",button)){foreach(var i in run.inventory)i.durability=6;screen=ScreenId.Map;}if(GUILayout.Button("立ち去る",button))screen=ScreenId.Map;}
 void Compendium(){Back();GUILayout.Label("図鑑",header);GUILayout.Label("装備",header);foreach(var i in GameCatalog.Items.Values)GUILayout.Label($"{i.name}｜{i.type}｜{i.cells.Length}マス｜{i.description}",body);GUILayout.Label("役職",header);foreach(var r in GameCatalog.Roles.Values)GUILayout.Label($"{r.name}｜{r.kind}｜{r.description}",body);GUILayout.Label("敵",header);foreach(var e in GameCatalog.Enemies)GUILayout.Label($"{e.name}｜HP{e.hp}",body);}
 void FinishRun(bool win){if(win){meta.wins++;meta.baseGold+=run.gold;foreach(var item in run.inventory.Where(x=>x.origin!="supply")){if(meta.stash.Count<4+meta.vaultLevel*4&&!meta.stash.Any(x=>x.uid==item.uid))meta.stash.Add(CloneItem(item));}}else meta.baseGold+=run.gold/4;meta.runs++;SaveSystem.Save(meta);message=win?"遠征成功。戦果を保管しました":"探索終了。保護されていない装備を失いました";screen=ScreenId.GameOver;}
 void GameOver(){GUILayout.Label(message,header);if(GUILayout.Button("拠点へ戻る",button,GUILayout.Height(60))){run=null;screen=ScreenId.Hub;}}
 void Back(){if(GUILayout.Button("← 拠点",GUILayout.Width(100)))screen=ScreenId.Hub;}
 void Line(){GUILayout.Box(GUIContent.none,GUILayout.ExpandWidth(true),GUILayout.Height(1));}
 FactionDef Faction(string id)=>GameCatalog.Factions.First(x=>x.id==id);
 ItemInstance CloneItem(ItemInstance x)=>JsonUtility.FromJson<ItemInstance>(JsonUtility.ToJson(x));
 Color ElementColor(Element e)=>e==Element.Fire?new(.45f,.16f,.11f):e==Element.Water?new(.10f,.30f,.46f):e==Element.Wind?new(.10f,.38f,.23f):new(.42f,.32f,.10f);
 Color TypeColor(ItemType t)=>t==ItemType.Weapon?new(.55f,.20f,.16f):t==ItemType.Armor?new(.18f,.35f,.44f):t==ItemType.Rune?new(.36f,.20f,.48f):new(.55f,.42f,.14f);
}
}
