using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Packspire {
public class PackspireGame : MonoBehaviour {
 MetaSave meta; RunState run; DungeonMap map; BattleState battle; ScreenId screen; Vector2 scroll; string selectedUid="",message="",hubHover=""; int selectedRotation; bool packingAtBase; GUIStyle title,header,body,button,card,hotspot,hubLabel,hubLabelHover,topChip; Texture2D factionArt,hubArt,characterArt,panelTex,buttonTex,hoverTex; Font uiFont;
 readonly Color bg=new(0.055f,0.07f,0.06f),panel=new(0.10f,0.12f,0.105f),gold=new(0.84f,0.68f,0.35f),ink=new(0.9f,0.89f,0.84f);
 void Awake(){DontDestroyOnLoad(gameObject);meta=SaveSystem.Load();factionArt=Resources.Load<Texture2D>("Art/faction-hub-sheet");hubArt=Resources.Load<Texture2D>("Art/UI/hub-courtyard-v1");characterArt=Resources.Load<Texture2D>("Art/character-creator-sheet");uiFont=Resources.Load<Font>("Fonts/NotoSansJP-VF");screen=meta.characterMade?ScreenId.Hub:ScreenId.Character;Application.targetFrameRate=60;}
 Texture2D Solid(Color color){var t=new Texture2D(1,1);t.SetPixel(0,0,color);t.Apply();return t;}
 void InitStyles(){if(title!=null)return;if(uiFont!=null){GUI.skin.font=uiFont;GUI.skin.label.font=uiFont;GUI.skin.button.font=uiFont;GUI.skin.box.font=uiFont;}panelTex=Solid(new Color(.055f,.045f,.035f,.92f));buttonTex=Solid(new Color(.12f,.095f,.065f,.96f));hoverTex=Solid(new Color(.48f,.31f,.11f,.96f));title=new GUIStyle(GUI.skin.label){font=uiFont,fontSize=30,fontStyle=FontStyle.Bold,normal={textColor=new Color(.96f,.88f,.65f)}};header=new GUIStyle(GUI.skin.label){font=uiFont,fontSize=20,fontStyle=FontStyle.Bold,normal={textColor=gold}};body=new GUIStyle(GUI.skin.label){font=uiFont,fontSize=14,wordWrap=true,normal={textColor=ink}};button=new GUIStyle(GUI.skin.button){font=uiFont,fontSize=15,alignment=TextAnchor.MiddleLeft,padding=new RectOffset(16,16,11,11),normal={background=buttonTex,textColor=ink},hover={background=hoverTex,textColor=Color.white},active={background=hoverTex,textColor=Color.white}};card=new GUIStyle(button){fontSize=12,alignment=TextAnchor.UpperLeft,wordWrap=true,padding=new RectOffset(10,10,10,10)};hotspot=new GUIStyle(GUI.skin.button){font=uiFont,normal={background=Solid(new Color(0,0,0,0))},hover={background=Solid(new Color(1,.72f,.24f,.08f))},active={background=Solid(new Color(1,.72f,.24f,.16f))}};hubLabel=new GUIStyle(GUI.skin.label){font=uiFont,fontSize=16,fontStyle=FontStyle.Bold,alignment=TextAnchor.MiddleCenter,padding=new RectOffset(12,12,7,7),normal={background=panelTex,textColor=new Color(1,.92f,.72f)}};hubLabelHover=new GUIStyle(hubLabel){normal={background=hoverTex,textColor=Color.white}};topChip=new GUIStyle(hubLabel){fontSize=14,alignment=TextAnchor.MiddleLeft};}
 void OnGUI(){InitStyles();DrawScreenBackground();GUILayout.BeginArea(new Rect(28,20,Screen.width-56,Screen.height-40));TopBar();scroll=GUILayout.BeginScrollView(scroll);switch(screen){case ScreenId.Character:Character();break;case ScreenId.Hub:Hub();break;case ScreenId.Status:Status();break;case ScreenId.Vault:Vault();break;case ScreenId.Faction:Faction();break;case ScreenId.Expedition:Expedition();break;case ScreenId.Pack:Pack();break;case ScreenId.Map:Map();break;case ScreenId.Battle:Battle();break;case ScreenId.Reward:Reward();break;case ScreenId.Shop:Shop();break;case ScreenId.Event:Event();break;case ScreenId.Compendium:Compendium();break;case ScreenId.GameOver:GameOver();break;}GUILayout.EndScrollView();GUILayout.EndArea();}
 void DrawScreenBackground(){Rect full=new(0,0,Screen.width,Screen.height);GUI.color=bg;GUI.DrawTexture(full,Texture2D.whiteTexture);GUI.color=Color.white;if(screen!=ScreenId.Hub&&hubArt!=null){GUI.color=new Color(.30f,.28f,.24f,1);GUI.DrawTexture(full,hubArt,ScaleMode.ScaleAndCrop);GUI.color=new Color(0,0,0,.78f);GUI.DrawTexture(full,Texture2D.whiteTexture);GUI.color=Color.white;}}
 void BeginPage(string pageTitle,string subtitle=""){GUILayout.BeginVertical(GUI.skin.box);GUILayout.Label(pageTitle,header);if(!string.IsNullOrEmpty(subtitle))GUILayout.Label(subtitle,body);GUILayout.Space(10);}
 void EndPage(){GUILayout.Space(12);GUILayout.EndVertical();}
 void TopBar(){GUILayout.BeginHorizontal();GUILayout.Label("PACKSPIRE",title,GUILayout.Width(240));GUILayout.FlexibleSpace();if(run!=null)GUILayout.Label($"HP {run.hp}/{run.maxHp}　{run.gold}G　{GameCatalog.Roles[run.role].name}",topChip,GUILayout.Width(330));else if(meta!=null&&meta.characterMade)GUILayout.Label($"{GameCatalog.Roles[meta.currentRole].name}　{meta.baseGold}G　{Faction(meta.currentFaction).name}",topChip,GUILayout.Width(360));GUILayout.EndHorizontal();Line();}
 void Character(){BeginPage("キャラクター作成","探索者の外見を選択してください。体格や髪型による能力差はありません。");GUILayout.BeginHorizontal();GUILayout.BeginVertical(GUILayout.Width(520));GUILayout.Label("体格",header);for(int i=0;i<4;i++){int n=i;string label=$"{(i<2?"男性":"女性")}タイプ {(i%2)+1}";if(GUILayout.Button(meta.body==i?$"● {label}":$"○ {label}",button,GUILayout.Height(54)))meta.body=n;}GUILayout.Space(18);GUILayout.Label("髪型",header);string[] hair={"短髪","ミディアム","結び髪"};for(int i=0;i<3;i++){int n=i;if(GUILayout.Button(meta.hair==i?$"● {hair[i]}":$"○ {hair[i]}",button,GUILayout.Height(54)))meta.hair=n;}GUILayout.Space(24);if(GUILayout.Button($"この姿で始める　{(meta.body<2?"男性":"女性")}／{hair[meta.hair]}",button,GUILayout.Height(68))){meta.characterMade=true;SaveSystem.Save(meta);screen=ScreenId.Hub;}GUILayout.EndVertical();GUILayout.Space(32);Rect preview=GUILayoutUtility.GetRect(520,650,GUILayout.ExpandWidth(true));GUI.DrawTexture(preview,panelTex,ScaleMode.StretchToFill);DrawCharacter(preview,meta.body,meta.hair);GUILayout.EndHorizontal();EndPage();}
 void Hub(){GUILayout.Label($"{Faction(meta.currentFaction).name}の拠点",header);float height=Mathf.Max(620,(Screen.width-82)*9f/16f);Rect art=GUILayoutUtility.GetRect(100,height,GUILayout.ExpandWidth(true));if(hubArt!=null)GUI.DrawTexture(art,hubArt,ScaleMode.ScaleAndCrop);else{GUI.color=new Color(.18f,.15f,.1f);GUI.DrawTexture(art,Texture2D.whiteTexture);GUI.color=Color.white;}Rect hero=new(art.center.x-art.width*.105f,art.y+art.height*.43f,art.width*.21f,art.width*.21f);DrawCharacter(hero,meta.body,meta.hair);hubHover="";HubHotspot(art,new Rect(.02f,.17f,.27f,.42f),"鍛冶場",ScreenId.Vault);HubHotspot(art,new Rect(.01f,.57f,.28f,.38f),"荷造り",ScreenId.Pack);HubHotspot(art,new Rect(.37f,.03f,.25f,.39f),"遠征門",ScreenId.Expedition);HubHotspot(art,new Rect(.75f,.20f,.23f,.36f),"保管庫",ScreenId.Vault);HubHotspot(art,new Rect(.72f,.55f,.27f,.42f),"酒場・図鑑",ScreenId.Compendium);HubHotspot(art,new Rect(.57f,.04f,.24f,.38f),"勢力会館",ScreenId.Faction);HubHotspot(art,new Rect(.39f,.45f,.22f,.43f),GameCatalog.Roles[meta.currentRole].name,ScreenId.Status);}
 void DrawCharacter(Rect target,int bodyIndex,int hairIndex){if(characterArt==null)return;int col=Mathf.Clamp(bodyIndex,0,3),row=Mathf.Clamp(hairIndex,0,2);Rect uv=new(col*.25f,(2-row)/3f,.25f,1f/3f);GUI.DrawTextureWithTexCoords(target,characterArt,uv,true);}
 void HubHotspot(Rect parent,Rect normalized,string label,ScreenId next){Rect r=new(parent.x+parent.width*normalized.x,parent.y+parent.height*normalized.y,parent.width*normalized.width,parent.height*normalized.height);bool hovered=r.Contains(UnityEngine.Event.current.mousePosition);if(hovered)hubHover=label;if(GUI.Button(r,GUIContent.none,hotspot)){if(next==ScreenId.Pack)OpenPacking();else screen=next;}float labelWidth=Mathf.Clamp(r.width*.72f,120,230);Rect plaque=new(r.center.x-labelWidth*.5f,r.yMax-42,labelWidth,36);GUI.Label(plaque,label,hovered?hubLabelHover:hubLabel);}
 void OpenPacking(){run=LoadoutSystem.CreateRun(meta,"");packingAtBase=true;selectedUid="";message="荷造りセットを編集";screen=ScreenId.Pack;}
 void HubButton(string name,string desc,ScreenId next){if(GUILayout.Button($"{name}\n{desc}",button,GUILayout.Height(110)))screen=next;}
 void Status(){Back();BeginPage("役職ステータス",$"現在職：{GameCatalog.Roles[meta.currentRole].name}");foreach(var level in meta.jobLevels.Where(x=>x.value>0)){var r=GameCatalog.Roles[level.id];GUILayout.BeginVertical(GUI.skin.box);GUILayout.Label($"{r.name}　Lv.{level.value}/{r.maxLevel}",header);GUILayout.Label(r.description,body);GUILayout.Label("Lv.7・最大レベルで専用効果候補を解禁",body);GUILayout.EndVertical();}EndPage();}
 void Vault(){Back();var active=LoadoutSystem.Active(meta);BeginPage($"保管庫　{meta.stash.Count}個",$"使用中：{active.name} / {GameCatalog.Backpacks.First(x=>x.id==active.backpack).name}");GUILayout.Label("荷造りセット",header);GUILayout.BeginHorizontal();foreach(var loadout in meta.loadouts){if(GUILayout.Button(loadout.id==meta.selectedLoadoutId?$"● {loadout.name}":loadout.name,button,GUILayout.Height(50)))LoadoutSystem.Select(meta,loadout.id);}GUILayout.EndHorizontal();GUILayout.Space(12);GUILayout.Label("バックパック",header);GUILayout.BeginHorizontal();foreach(var bag in GameCatalog.Backpacks){if(GUILayout.Button(active.backpack==bag.id?$"● {bag.name}":bag.name,button,GUILayout.Height(55))){active.backpack=bag.id;meta.selectedBackpack=bag.id;}}GUILayout.EndHorizontal();GUILayout.Space(12);GUILayout.Label("保管装備",header);foreach(var item in meta.stash){var d=GameCatalog.Items[item.templateId];GUILayout.BeginHorizontal(GUI.skin.box);GUILayout.Label($"{(item.uid==meta.selectedHeirloomUid?"★ ":"")}{d.name} +{item.temper}　耐久{item.durability}/6　使用{item.uses}",body);if(GUILayout.Button("家宝",button,GUILayout.Width(100)))meta.selectedHeirloomUid=item.uid;if(GUILayout.Button("鍛錬",button,GUILayout.Width(100))&&meta.baseGold>=30*(item.temper+1)){meta.baseGold-=30*(item.temper+1);item.temper=Mathf.Min(5,item.temper+1);}GUILayout.EndHorizontal();}EndPage();SaveSystem.Save(meta);}
 void Faction(){Back();BeginPage("勢力関係図","所属変更には20Gが必要です。片方へ肩入れすると、競合勢力との関係にも影響します。");foreach(var f in GameCatalog.Factions){float rep=meta.factionRep.First(x=>x.id==f.id).value;GUILayout.BeginHorizontal(GUI.skin.box);GUILayout.Label($"{f.name}\n貢献 {rep:0}　{f.description}",body,GUILayout.Height(58));if(GUILayout.Button(meta.currentFaction==f.id?"● 所属中":"20Gで所属",button,GUILayout.Width(140),GUILayout.Height(58))&&meta.currentFaction!=f.id&&meta.baseGold>=20){meta.baseGold-=20;meta.currentFaction=f.id;SaveSystem.Save(meta);}GUILayout.EndHorizontal();}EndPage();}
 void Expedition(){Back();BeginPage("遠征準備","使用する荷造りセットと遠征先を選択してください。");GUILayout.Label("荷造りセット",header);GUILayout.BeginHorizontal();foreach(var loadout in meta.loadouts){if(GUILayout.Button(loadout.id==meta.selectedLoadoutId?$"● {loadout.name}":loadout.name,button,GUILayout.Height(52)))LoadoutSystem.Select(meta,loadout.id);}GUILayout.EndHorizontal();var active=LoadoutSystem.Active(meta);GUILayout.Label($"{GameCatalog.Backpacks.First(x=>x.id==active.backpack).name} / 配置{active.slots.Count}個 / 装備カード{active.deck.Count}枚",body);GUILayout.Space(16);GUILayout.Label("遠征先",header);for(int i=0;i<GameCatalog.Dungeons.Length;i++){var d=GameCatalog.Dungeons[i];GUI.enabled=i<meta.dungeonsUnlocked;if(GUILayout.Button($"{d.name}\n{d.description}　戦闘{d.battles}回",button,GUILayout.Height(88))){StartRun(d.id);}GUI.enabled=true;}EndPage();SaveSystem.Save(meta);}
 void StartRun(string dungeon){run=LoadoutSystem.CreateRun(meta,dungeon);packingAtBase=false;map=DungeonSystem.Generate();screen=ScreenId.Pack;selectedUid="";message="編成を確認してください";}
 void Pack(){GUILayout.BeginHorizontal();if(GUILayout.Button(packingAtBase?"← 拠点":"← マップ",GUILayout.Width(100)))screen=packingAtBase?ScreenId.Hub:ScreenId.Map;if(GUILayout.Button("↻ 回転",GUILayout.Width(100)))selectedRotation=(selectedRotation+1)%4;if(GUILayout.Button("選択を外す",GUILayout.Width(110)))selectedUid="";GUILayout.Label(message,body);GUILayout.EndHorizontal();GUILayout.BeginHorizontal();GUILayout.BeginVertical(GUILayout.Width(250));GUILayout.Label("保管装備",header);foreach(var item in run.inventory){var d=GameCatalog.Items[item.templateId];bool placed=run.placements.Any(x=>x.itemUid==item.uid);GUI.enabled=!placed;if(GUILayout.Button($"{d.name}\n{d.description}",card,GUILayout.Height(65))){selectedUid=item.uid;selectedRotation=0;}GUI.enabled=true;}GUILayout.EndVertical();GUILayout.Space(18);DrawGrid();GUILayout.Space(18);GUILayout.BeginVertical(GUILayout.Width(320));var build=BackpackSystem.Build(run);GUILayout.Label($"装備カード {build.deck.Count-build.roleCards.Count}/8　基本カード {build.roleCards.Count}",header);foreach(var c in build.candidates){bool selected=run.selectedCardSlots.Contains(c.slotKey);GUI.enabled=selected||run.selectedCardSlots.Count<LoadoutSystem.EquipmentCardLimit;if(GUILayout.Button($"{(selected?"●":"○")} {c.name} [{c.cost}]\n{c.text}\n{c.source}",card,GUILayout.Height(74))){if(selected)run.selectedCardSlots.Remove(c.slotKey);else run.selectedCardSlots.Add(c.slotKey);}GUI.enabled=true;}GUILayout.Label("発動中リンク",header);foreach(var link in build.links)GUILayout.Label("・"+link,body);GUILayout.EndVertical();GUILayout.EndHorizontal();if(GUILayout.Button("この荷造りを保存",button,GUILayout.Height(55))){LoadoutSystem.Capture(meta,run);SaveSystem.Save(meta);screen=packingAtBase?ScreenId.Hub:ScreenId.Map;}}
void DrawGrid(){GUILayout.BeginVertical(GUILayout.Width(480));GUILayout.Label("6×4 色マスバックパック　配置した装備はすべて有効",header);Rect grid=GUILayoutUtility.GetRect(456,304);float cw=grid.width/6,ch=grid.height/4;for(int i=0;i<24;i++){Rect r=new(grid.x+(i%6)*cw,grid.y+(i/6)*ch,cw-3,ch-3);var e=GameCatalog.Board[i];GUI.backgroundColor=ElementColor(e);if(GUI.Button(r,e.ToString()[0].ToString()))TryPlace(i);GUI.backgroundColor=Color.white;}foreach(var p in run.placements.ToList()){var item=run.inventory.First(x=>x.uid==p.itemUid);var def=GameCatalog.Items[item.templateId];foreach(var cell in BackpackSystem.Layout(def,p.rotation)){int index=p.anchor+cell.pos.y*6+cell.pos.x;Rect r=new(grid.x+(index%6)*cw+5,grid.y+(index/6)*ch+5,cw-13,ch-13);bool match=GameCatalog.Board[index]==cell.element;GUI.backgroundColor=match?Color.white:TypeColor(def.type);if(GUI.Button(r,$"{def.name[0]}\n{cell.element.ToString()[0]}{(match?" 一致":"")}")){selectedUid=item.uid;selectedRotation=p.rotation;if(UnityEngine.Event.current.button==1){run.placements.Remove(p);message=def.name+"を外しました";}}GUI.backgroundColor=Color.white;}}GUILayout.EndVertical();}
 void TryPlace(int cell){if(string.IsNullOrEmpty(selectedUid))return;var item=run.inventory.FirstOrDefault(x=>x.uid==selectedUid);if(item==null)return;var old=run.placements.FirstOrDefault(x=>x.itemUid==selectedUid);if(BackpackSystem.CanPlace(run,item,cell,selectedRotation,selectedUid)){if(old!=null)run.placements.Remove(old);run.placements.Add(new Placement(item.uid,cell,selectedRotation));message=GameCatalog.Items[item.templateId].name+"を配置";}else message="そこには入りません";}
 void Map(){GUILayout.BeginHorizontal();if(GUILayout.Button("荷造り",GUILayout.Width(100)))screen=ScreenId.Pack;if(GUILayout.Button("入口から帰還",GUILayout.Width(130))&&map.current==12){FinishRun(true);return;}GUILayout.Label($"警戒 {run.axes.alert:+#;-#;0}　崩壊 {run.axes.collapse:+#;-#;0}　汚染 {run.axes.corruption:+#;-#;0}　戦闘勝利 {run.battlesWon}",header);GUILayout.EndHorizontal();Rect area=GUILayoutUtility.GetRect(720,520);float w=area.width/6,h=area.height/6;foreach(var n in map.nodes){Rect r=new(area.x+n.x*w+3,area.y+n.y*h+3,w-6,h-6);GUI.enabled=n.revealed&&(n.id==map.current||DungeonSystem.Adjacent(map.current,n.id));GUI.backgroundColor=n.id==map.current?gold:n.visited?new Color(.25f,.35f,.25f):panel;if(GUI.Button(r,n.revealed?n.type:"？")){if(n.id!=map.current&&DungeonSystem.Move(map,n.id,run))EnterNode(n);}GUI.backgroundColor=Color.white;GUI.enabled=true;}}
 void EnterNode(MapNode n){if(n.type=="battle"||n.type=="boss"){StartBattle(n.type=="boss");return;}if(n.type=="shop"){screen=ScreenId.Shop;return;}if(n.type=="event"||n.type=="treasure"){screen=ScreenId.Event;return;}if(n.type=="rest"){run.hp=Mathf.Min(run.maxHp,run.hp+12);foreach(var i in run.inventory)i.durability=6;message="野営して回復・修理した";}}
 void StartBattle(bool boss){var dungeon=GameCatalog.Dungeons.First(x=>x.id==run.dungeon);var pool=GameCatalog.Enemies.Where(x=>boss?x.tier==3:x.tier==Mathf.Min(2,1+run.battlesWon/3)).ToArray();battle=BattleSystem.Begin(run,pool[UnityEngine.Random.Range(0,pool.Length)],dungeon.hpScale);screen=ScreenId.Battle;}
 void Battle(){var dungeon=GameCatalog.Dungeons.First(x=>x.id==run.dungeon);GUILayout.Label($"{battle.enemy.name}　HP {Mathf.Max(0,battle.enemyHp)}/{battle.enemyMaxHp}",header);GUILayout.Label($"次の攻撃 {battle.enemy.damages[battle.move%battle.enemy.damages.Length]+dungeon.damage}　　自分 HP {run.hp}/{run.maxHp} 防御{run.block} EN{run.energy}",body);GUILayout.Label(battle.log,body);if(run.consumables.Count>0){GUILayout.BeginHorizontal();GUILayout.Label("消耗品",body,GUILayout.Width(55));for(int i=0;i<run.consumables.Count;i++){int index=i;if(GUILayout.Button(ConsumableSystem.Name(run.consumables[i]),GUILayout.Width(90))){ConsumableSystem.Use(run,battle,index);if(battle.enemyHp<=0){WinBattle();return;}break;}}GUILayout.EndHorizontal();}GUILayout.BeginHorizontal();for(int i=0;i<run.hand.Count;i++){int index=i;var c=run.hand[i];GUI.enabled=c.cost<=run.energy;if(GUILayout.Button($"[{c.cost}] {c.name}\n{c.text}\n{c.source}",card,GUILayout.Width(155),GUILayout.Height(150))){if(BattleSystem.Play(run,battle,index)){WinBattle();return;}}GUI.enabled=true;}GUILayout.EndHorizontal();if(GUILayout.Button("ターン終了",button,GUILayout.Height(50))){if(BattleSystem.EndTurn(run,battle,dungeon.damage)){FinishRun(false);return;}}}
 void WinBattle(){run.battlesWon++;run.gold+=12+run.battlesWon*3;run.hp=Mathf.Min(run.maxHp,run.hp+3);if(battle.enemy.tier==3){FinishRun(true);return;}screen=ScreenId.Reward;}
 void Reward(){GUILayout.Label("戦果を1つ選択（帰還後に鑑定）",header);string[] pool={"dagger","plate","crystal","bomb","spear","buckler","flask","charm"};GUILayout.BeginHorizontal();foreach(var id in pool.OrderBy(_=>UnityEngine.Random.value).Take(3)){if(GUILayout.Button(GameCatalog.Items[id].name,button,GUILayout.Width(220),GUILayout.Height(100))){run.lootBag.Add(new ItemInstance(id){identified=false});screen=ScreenId.Map;}}GUILayout.EndHorizontal();}
 void Shop(){GUILayout.Label("行商人",header);foreach(var id in GameCatalog.Items.Keys.Take(5)){int price=14+GameCatalog.Items[id].cells.Length*4;if(GUILayout.Button($"{GameCatalog.Items[id].name}　{price}G",button)&&run.gold>=price){run.gold-=price;run.inventory.Add(new ItemInstance(id));}}if(GUILayout.Button("戻る",button))screen=ScreenId.Map;}
 void Event(){GUILayout.Label("記憶の揺らぎ",header);GUILayout.Label("古塔の記憶が選択を要求している。",body);if(GUILayout.Button("6HPを支払い24Gを得る",button)){run.hp=Mathf.Max(1,run.hp-6);run.gold+=24;screen=ScreenId.Map;}if(GUILayout.Button("装備を修理する",button)){foreach(var i in run.inventory)i.durability=6;screen=ScreenId.Map;}if(GUILayout.Button("立ち去る",button))screen=ScreenId.Map;}
 void Compendium(){Back();GUILayout.Label("図鑑",header);GUILayout.Label("装備",header);foreach(var i in GameCatalog.Items.Values)GUILayout.Label($"{i.name}｜{i.type}｜{i.cells.Length}マス｜{i.description}",body);GUILayout.Label("役職",header);foreach(var r in GameCatalog.Roles.Values)GUILayout.Label($"{r.name}｜{r.kind}｜{r.description}",body);GUILayout.Label("敵",header);foreach(var e in GameCatalog.Enemies)GUILayout.Label($"{e.name}｜HP{e.hp}",body);}
 void FinishRun(bool win){if(win){meta.wins++;meta.baseGold+=run.gold;foreach(var item in run.inventory.Concat(run.lootBag)){var saved=meta.stash.FirstOrDefault(x=>x.uid==item.uid);if(saved==null)meta.stash.Add(CloneItem(item));else{saved.durability=item.durability;saved.uses=item.uses;saved.temper=item.temper;saved.scars=item.scars;saved.history=item.history;}}}else{var heir=run.inventory.FirstOrDefault(x=>x.uid==run.heirloomUid);if(heir!=null){heir.history.defeats++;heir.scars.Add(new ScarRecord{type="defeat",dungeon=run.dungeon,floor=run.battlesWon,timestamp=DateTimeOffset.UtcNow.ToUnixTimeSeconds()});var saved=meta.stash.FirstOrDefault(x=>x.uid==heir.uid);if(saved!=null){saved.scars=heir.scars;saved.history=heir.history;}}}meta.runs++;SaveSystem.Save(meta);message=win?"遠征成功。戦利品をすべて保管しました":"探索終了。戦利品と獲得ゴールドは持ち帰れません";screen=ScreenId.GameOver;}
 void GameOver(){GUILayout.Label(message,header);if(GUILayout.Button("拠点へ戻る",button,GUILayout.Height(60))){run=null;screen=ScreenId.Hub;}}
 void Back(){if(GUILayout.Button("← 拠点",GUILayout.Width(100)))screen=ScreenId.Hub;}
 void Line(){GUILayout.Box(GUIContent.none,GUILayout.ExpandWidth(true),GUILayout.Height(1));}
 FactionDef Faction(string id)=>GameCatalog.Factions.First(x=>x.id==id);
 ItemInstance CloneItem(ItemInstance x)=>JsonUtility.FromJson<ItemInstance>(JsonUtility.ToJson(x));
 Color ElementColor(Element e)=>e==Element.Fire?new(.45f,.16f,.11f):e==Element.Water?new(.10f,.30f,.46f):e==Element.Wind?new(.10f,.38f,.23f):new(.42f,.32f,.10f);
 Color TypeColor(ItemType t)=>t==ItemType.Weapon?new(.55f,.20f,.16f):t==ItemType.Armor?new(.18f,.35f,.44f):t==ItemType.Rune?new(.36f,.20f,.48f):new(.55f,.42f,.14f);
}
}
